### ISSUE TITLE
Clearing up ATC code

### ISSUE THREAD

**Issue by mariash** [concourse/concourse#1184]
The goal of this issue:

* improve code maintainability
* improve code readability
* come up with a clear definition for different subjects in the code, what they represent and how they interact with each other with clear responsibilities and interface
* come up with documentation plan for core ATC functionality
* community should feel empowered in making pool requests to ATC

## Come up with core ATC terminology

**Status**: 
**Action plan**: 

- [ ] document current state of main ATC subjects and their interaction
- [ ] have a technical meeting to come up with clear terminology for main ATC components
- [ ] pick a specific component for a more detailed review
- [ ] use this terminology as a guide when refactoring parts of ATC

## Getting rid of db in favor of dbng

**Status**: ongoing
**Action plan**: 

* refactor while working on corresponding story that touches db methods.

**Comment by mariash** [comment]
Current plan is to clean up our action steps (get, task, put). We deleted dependent get step and pass in the result across plans as reference.

We split these three steps (get, task and put) into actions: check, get, task, put. 

What is step? Step is something you see in your pipeline separated by individual header.

Each step can actually consist of several actions. For example, task step can run check action for image resource, get action for image resource and then task action. Splitting steps into actions will allow us to get better visibility into what actions are included in each step. Remove recursion since now we are going to build set of actions before passing them to step. The step that will execute the actions is called ActionsStep. We can also better test each action individually and each action will have a smaller responsibility.

Each action will be defined by RootFSSource, either as BaseResourceTypeRootFSSource (meaning it is created from base resource type) or OutputRootFSSource (meaning it is created as an output from previous action, e.g resource type fetching or task image building). That will allow executioneer to be stupid about what to actually use as rootfs for container and not to drag resource types around across resource/worker packages.

The challenge comes that sometimes we need to figure out what RootFSSource to use on fly. This is in case when config is loaded dynamically (using `file` on a task). In that case executioneer will fetch raw config in atc.Config form, pass that to planner and planner will give back set of action to executionner.

Work in progress work is currently on branch `wip-resource-refactor`. Testflight tests are passing, unit tests are failing as of now.

**Comment by mariash** [comment]
We continued on refactoring getAction/ActionsStep. ActionsStep will take buildDelegate to call methods like Initializing/Finished/Failed whenever one of actions fails. The build step factory constructs the delegate for particular set of actions. For GetPlan it will be GetBuildDelegate. We split ImageFetchingDelegate from BuildDelegate since they don't have to be together, ImageFetchingDelegate just manages image fetching stuff. The plan is to do the same for put and task steps: 1) convert them to actions, 2) pass these actions to ActionsStep, 3) for each of them pass in the delegate to ActionsStep that is specific for that step.

**Comment by andrewedstrom** [comment]
As of today we split out get/put/task steps into actions. 

Actions are being constructed in GardenFactory which takes the plan and constructs the set of actions and passes them to ActionsStep along with BuildEventsDelegate. ActionsStep will call:
* Initializing at the beginning of the step
* ActionCompleted after each action
* Failed if any action fails 
* Finished at the end after all actions succeed. 

This allowed us to simplify Result method on each step to just Succeeded (that returns boolean if step succeeded). 

We also split out FetchConfigAction from TaskAction. The idea is that in future the planner (which is today GardenFactory) will construct FetchConfigAction for steps that need it and FetchConfigAction will be generic for all config types. Testflight tests are passing. We are planning to fix unit tests and merge it to master.

**Comment by andrewedstrom** [comment]
We also want to rethink the delegates interface to maybe always pass the action/step that's being acted upon, and respond accordingly.

**Comment by mariash** [comment]
This issue has gotten pretty big so we are going to split it into some subissues.

1) #1281 which covers the breaking up of the task/get/put steps into actions, and refactoring of the build delegate
2) #1282 for future refactoring of the Resource package
3) #1283 for worker package refactoring
