### ISSUE TITLE
Dashboard Touch-ups

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1727]
Looking at the latest iteration of our dashboard, @Lindsayauchin and I wanted to make a few cosmetic tweaks to the UI

**Top Nav**
- [x] Search bar should be wider (220px) and padding should be equal below and above 
- [x] Search bar border colour #504B4B
- [x] Logo should be horizontally centred in top nav bar
- [x] remove black border from top nav bar

**Bottom Legend bar**
- [x] CLI download icons should have a hover state on the bottom bar. 
[cli_icons.zip](https://github.com/concourse/concourse/files/1402387/cli_icons.zip)

**job tooltip**

- [x] Hovering on links on the dashboard (e.g. a job) will cause chrome to generate the grey URL bar on the bottom left (great) but covers the status bar (bad). Height of the bottom legend should be 65 px to avoid crashing with the grey url bar.

- [x] Hover on job tooltip should float to the rightmost side of the job box. Also, we should add a hover state on the specific job to make it clear that it is the one being selected. Interior border of 5px in the corresponding secondary colour for that job state. 

![dashboard_hoverstate_job_url_legend](https://user-images.githubusercontent.com/27746614/31905455-3f3c9e66-b7fc-11e7-9d05-faf1e90c5b46.png)

**Pipeline Abstraction**
- [x] update animation running colours on the top bar of the pipeline cards and make consistent with the job running animation Values update to: Green #11C560, 419867, Amber #FFB843, #EC9910, Red#ED4B35, #BD3826, Grey #7A7373, #9B9B9B

![dashboard_colour_pallet](https://user-images.githubusercontent.com/27746614/31907300-67cfd348-b801-11e7-9704-9aadebfecf06.png)

**Team**
- [x] Team name name is too low contrast- update to #868585

**Comment by Lindsayauchin** [comment]
Before we accept this issue can we look at the striping on the animations? It looks like it is reversed from the spec. The darker colour should be in the background with the thinner line as the brighter, lighter colour. Also, could we replace ##31A864 with the dark Green#419867 in the spec as well as the Amber #EC9910 to #D58808 ?
