### ISSUE TITLE
Spike: Look into whether authorization providers can be globally configured

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#1800]
Time boxed to **2 days**

Let's consider what would be involved in moving auth providers a level up:
- [x] Take a look at how the current team-scoped auth provider model works

Given the current state of the world, what would be involved in having auth providers moved to the global level. Take the following into consideration:
- [x] Currently auth providers have details about what 'group' of users are able to log into a team; as a user how do I set this with global auth providers
- [x] We want to be able to support showing all of the teams a user is authorized to view; what would be involved in supporting that. Do 'global' auth providers help?
- [x] We want to be able to attribute actions to specific users; does this help or hinder?
- [x] Basic auth is weird in this scenario.. should/could it be 'global' somehow? Maybe as some detail of how team auth is configured?
- [ ] Does the operator configure 'global' auth providers? ( OAuth tokens? Basic Auth users? The set of providers available? )
- [ ] Does this involve two levels of configuration? ( These users can access the Concourse, these users can log into this team )

**Comment by pivotal-jwinters** [comment]
While investigating this spike we looked at our auth(z) implementation and determined that it is probably a good idea to use a third party solution. We've looked at the following libraries and standalone services to handle auth only, authz only or auth+authz workflows:

https://github.com/markbates/goth
https://github.com/cloudfoundry/uaa
https://github.com/coreos/dex
https://github.com/ory/hydra
https://github.com/volatiletech/authboss

Out of all these it looks like `coreos/dex` is probably our best option. It does auth+authz and means we wont have to worry about #1809

The great things about `dex`:
- It handles auth+authz with a pluggable connector interface (similar to our own implementation) with support for [these integrations](https://github.com/coreos/dex/tree/master/connector).

- It standardizes on a `groups` claim to identify some sort of membership from the external source (which in the github case can be a org/team). This means if we use `dex` we can use this claim directly instead of having to do the team verification ourselves. See the [github connector](https://github.com/coreos/dex/blob/master/Documentation/github-connector.md) for an idea of how org/team whitelisting can work. 

- Its written in `go` and it looks like we'll have the option of using it as a standalone service, or even embedding it inside our concourse binary. 

The meh things about `dex`:
- It supports basic auth, but it is strongly discouraged. They really don't want to manage users but they see why its necessary for bootstrapping (kinda similar to us?). https://github.com/coreos/dex/issues/1080 indicates that we might have to push a little if we want our basic auth users to belong to groups/teams.

Don't know yet how this will be configured.
