### ISSUE TITLE
Spike: Figure out the interface required by an auth provider

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#1809]
Timebox: 1 day of [looking at it](https://i.giphy.com/media/ete9HLBYGmXIY/giphy.gif).

Take a look at:
 - [ ] [the current interface for auth providers](https://github.com/concourse/atc/blob/master/auth/provider/provider.go).. just look at it.

[Consider the following:](http://i1.kym-cdn.com/photos/images/newsfeed/000/634/985/2d7.gif)
 - [ ] How does the provider interface need to change to support users?
   -  [ ] are additional methods required to identify the user?
   -  [ ] do the existing providers' underlying APIs support identifying a user?
   -  [ ] do the existing authorization / validation methods need to change to account for users?
   -  [ ] what's the required work to update [basic auth](https://github.com/concourse/atc/blob/master/auth/basic_auth_validator.go) to use the interface
   -  [ ] what happens when an operator configures `no_really_i_dont_want_any_auth`? what user am I when I "log in"?
 - [ ] What impact would #1800 have on the interface an auth provider would conform to

**Comment by pivotal-jwinters** [comment]
I think our decision to move towards `coreos/dex` makes this unecessary.
