### ISSUE TITLE
Make beta route work better

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1830]
When we rolled the dashboard into the `/beta` route there were a few things broken that made it really hard to use. This is a mega-issue to wrap the list of things we should fix:

- [ ] #1801 Bring back login button
- [ ] #1831 Navigating between builds is broken in beta route
- [ ] #1832 Can't click into resources in beta route

**Comment by jama-pivotal** [comment]
Closing for now. Turns out there are some complexities behind the beta route. We know that a lot of existing functionality can't be accessed in the beta route, but its a lot less "fixing" and a lot more "oh we need to implement that page in the context of the new stories". Going to try again with a different approach for stories
