### ISSUE TITLE
Rely on coreos/dex for third party integrations.

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#1888]
## Background
For background on this issue have look at #1886 

## Goal
The goal of this issue is to swap out our existing auth implementation and delegate all the heavy lifting to `coreos/dex`. Making sure all our existing providers will work might take a bit of planning, but maybe we can reach out to the initial provider author to see if they're interested in contributing a connector to `coreos/dex`.

`github`, `gitlab` and `oidc` connectors, should all hopefully just work, we just need to figure out how to map our configuration to `dex` configuration.

`basic auth` can be replicated with what dex calls `static password` configuration. 

`bitbucket` - Need to implement a dex connector. 

`uaa` - this also needs to be implemented as a dex connector. It should probably be called a `cf` connector though because it does verification based on a `cf` org/space membership. *Note:* A `uaa` connector could potentially also exist but it would probably grant access based on uaas own internal group membership.
 
## Skymarshal tasks

- [x] handle command line arguments for configuring dex resources (clients, users, connectors)
- [x] create a login endpoint which issues a authorization_code request to dex, then exchanges it for a concourse token
- [x] create a token endpoint (only password grant type) which will retrieve a token from dex, then exchanges it for a concourse token
- [x] create a logout endpoint which will invalidate your concourse auth cookie (for backwards compatibility, this might not belong in skymarshal)
- [x] create a userinfo endpoint to inspect your concourse token
- [x] re-skin the web templates for concourse
- [x] if no redirect_uri is provided in the login request it should default to /
- [x] add configuration to enable **gitlab** connector
- [x] Allow configuring display name for generic connectors (oauth/oidc)
- [x] dynamically register connector config
- [x] update github configuration to support github enterprise
- [x] proper logging

## Dex tasks

- [x] have webconfig accept a http.filesystem so we can use bindata
- [x] need support for resource owner grant type
- [x] **github** connector should include all groups
- [x] **github** connector should include user login in token
- [x] **cf** connector
- [x] **oidc** connector should forward `groups` from configurable `groups` claims
- [x] **oauth** connector with scope based `groups` claims
- [ ] ~~**bitbucket** connector~~
- [ ] ~~**uaa** connector?~~
- [x] proper logging 
- [ ] figure out what to do with prometheus configuration

## Other tasks
- [x] bosh release changes
- [ ] run dex unit tests alongside other unit tests in our pipeline (as long as we're using a fork)
- [x] testflight
- [x] migrations???

**Comment by vito** [comment]
/cc @SHyx0rmZ (BitBucket provider author, https://github.com/concourse/atc/pull/215) and @dthorsen (LDAP PR author, https://github.com/concourse/atc/pull/202)

This is a new path we're exploring for auth providers. For LDAP, this may mean we'll get it for free (Dex already supports it). BitBucket however is not currently supported. Maybe that could be PRed to Dex?

**Comment by dthorsen** [comment]
Thanks @vito. If this is the preferred direction I will place my work on concourse/atc#202 on hold. I will need to test Dex a bit to see how that might fit into our environment ( I have yet to run Dex ). My use case involves running many instances of concourse so hopefully that wouldn't mean I would need to run many instances of Dex. Having the LDAP auth directly within concourse would have simplified the process of a team standing up a concourse instance. I will comment again after I have stood up Dex and get a feel for its configuration and how that might integrate in our environment.

**Comment by vito** [comment]
@dthorsen We're hoping to use dex as a library, not require users to deploy it. The UX should be just about the same as it is today, just with less maintenance burden in terms of code in Concourse.

**Comment by SHyx0rmZ** [comment]
I'll try and have a deeper look at dex until Monday, the idea sounds good to me.

**Comment by jdimmerman** [comment]
Hey @SHyx0rmZ or @pivotal-jwinters - Do you know if you still plan on implementing this and if so, the basic timeline?  We are considering whether we need to look at deploying UAA to set up ldap integration for now or if we can wait for this.

Thanks!
Jason
Zipcar

**Comment by pivotal-jwinters** [comment]
hey @jdimmerman its still in the works. Not sure about timelines, but its likely measured in months. Its part of our larger goals for auth (#1886) where we move towards a global user model. In the meantime you might want to look to UAA, as you mentioned.

**Comment by jdimmerman** [comment]
OK great to know, thanks @pivotal-jwinters!

**Comment by pivotal-jwinters** [comment]
@Lindsayauchin @sampeinado 

Mind having a look at these screens for the auth flow and making them more concourse-y? 

![screen shot 2018-04-03 at 2 29 06 pm](https://user-images.githubusercontent.com/1072233/38268177-7187545a-374b-11e8-92ac-80888eb95c6c.png)

![screen shot 2018-04-03 at 2 29 10 pm](https://user-images.githubusercontent.com/1072233/38268181-73940edc-374b-11e8-94b4-657b965cbb72.png)

**Comment by pivotal-jwinters** [comment]
Skymarshal server update

- We've introduced user login (instead of team login). You can now log in as a user, and we'll figure out what teams you're on.

- Skymarshal now delegates all requests to dex, then exchanges the dex token for a concourse token. To make this work we've bundled a dex server with skymarshal and removed all existing auth providers in favour of dex connectors.

- Currently only `github` and `local` users (basic auth) are supported. This is mainly just a matter of providing configuration for other dex connectors.

- We're now in the middle of investigation a `cf` connector for dex.

**Comment by Lindsayauchin** [comment]
@pivotal-jwinters Dex login skinned with Concourse UI

![concourse_login_01](https://user-images.githubusercontent.com/27746614/38566699-523464fa-3cb2-11e8-8c95-1d199194a67b.png)
![concourse_login_02](https://user-images.githubusercontent.com/27746614/38566700-5248cd00-3cb2-11e8-9301-d2a5d7b215f5.png)
![concourse_login_00](https://user-images.githubusercontent.com/27746614/38566701-525b6924-3cb2-11e8-9bf3-cde35ec43935.png)

**Comment by Lindsayauchin** [comment]
Updated design to accomidate max 10 login providers 

![concourse_login_00_max_10](https://user-images.githubusercontent.com/27746614/38959197-b8d958ba-432d-11e8-9c78-392e9e721b14.png)
[login_assets_svg.zip](https://github.com/concourse/concourse/files/1925871/login_assets_svg.zip)

**Comment by Lindsayauchin** [comment]
Updated Windows, gitlab, CF logo's [login_white_assets_svg.zip](https://github.com/concourse/concourse/files/1928660/login_white_assets_svg.zip)

**Comment by pivotal-jwinters** [comment]
@SHyx0rmZ have you had a chance to take a look at implementing a bitbucket server connector in dex? The bitbucket cloud connector seems pretty straightforward, but the server connector might be more work since it uses oauth1.

How do most people set up auth in bitbucket server anyway? Based on some googling it looks like a common pattern is to have it delegate to an LDAP server?

**Comment by SHyx0rmZ** [comment]
So, as far as I'm aware out set-up consists of Bitbucket Server being backed by Jira, which then in turn is backed by AD FS (was LDAP before). As we rely on the Bitbucket project membership to figure out who is allowed to access certain pipelines (none of the other systems have the necessary data), we could probably not go for LDAP or similar easily, but at this point I think it's the easier solution.

I don't really see any good way of adding a connector using OAuth 1 to dex, but I also clearly see the need to switch to dex. As we also seem to be phasing out usage of Concourse, I, personally, would be fine with Concourse dropping direct support for Bitbucket Server, as long as no one else is using it.

**Comment by pivotal-jwinters** [comment]
Lets talk about migrations

We're going to fail the up migration if:
- if you're using bitbucket, sorry its no longer supported 😢
- you have teams that use different configuration for the same provider type (e.g. two teams targeting different github enterprises).

We're going to fail the down migration (which we don't officially support btw) if:
- you change any of your teams auth (other than the main team) or add any new teams.
