### ISSUE TITLE
Test a backup and restore of our databases on Prod and Wings

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2094]
Test that we can actually do a backup and restore of the Postgres.

[@cirocosta updates]:

### Manually

- [x] Prod
  - [x] regularly backup with pipeline
  - [x] manually restore to a minimal environment

- ~Wings~
  - ~regularly backup with pipeline~
  - ~manually restore (need to be discussed)~

### Continuouslly

- [x] Continuously take backups
- [ ] Continuously perform a restore

#### Current status

- preparation
  - [x] check what'd be needed to be prepared before going with the backups
    - [x] how big is the prod DB? 40GB
    - [x] would `pg_dump` block whoever is consuming the DB? No
  - [x] manually try a backup
    - [x] have a separate deployment with the credentials as properties for BBR
      - [x] use a separate `instance_group` in order to isolate "machine that performs backups" and "db"
- [x] manual verification
- [ ] pipeline

[gcs]: https://cloud.google.com/storage/

**Comment by making** [comment]
Do you have a plan to support BBR?

**Comment by cirocosta** [comment]
Hi @making ,

We'll be soon finishing the work needed to be considered properly supported - see https://github.com/concourse/concourse/issues/2332.

This issue is about our team-operated Concourse installation consuming those notes and the lessons learned that we'll be sharing in the form of documentation soon.

Does that make sense?

Thanks!

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**
To get the prod/wings backup regularly, we need a pipeline to achieve this. Additionally, Running under the same network as `bbr-atcdb` (bbr backup and restore job) will be easy to do the backup/restore oepration without tunneling or other network workaround to access vms in the deployment.

**Here is the summary of the work today**
- Pipeline has been drafted for concourse production backup. The backup task has been done. What we want to do continue is:
  - timer tigger (schedule the backup)
  - fetch configuration from vault.
  - upload  the backup data to gcs
- Did a research on pg_dump. The backup can run concurrently without blocking any other access to the db.
- Empty password for postgres Issue was found when we try to do backup. https://github.com/concourse/concourse-bosh-release/issues/34

**Comment by cirocosta** [comment]
**DEV NOTE**

Today, @pivotal-bin-ju  and I:

- investigated how the lifecycle of backups work in BBR (see [backuper.go][backuper])
  - it indeed cleans up the result of `pg_dump` where it started the operation (the instance where `bbr-atcdb` is created at)
  - ps.: the result of `pg_dump` is already compressed even though `bbr` creates a `.tar`
- changed the pipeline to perform actual backups
  - stopped in the middle of one of them as we'd be increasing too much the disk size of it
- added time resource to the pipeline to perform periodic backups
- started adding a `gcs` resource to upload the results to a bucket

[backuper]: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/blob/a7dae8c7df8665b04494afe996022bfeeb383d79/orchestrator/backuper.go#L9-L39]

Next steps:

- finish the addition of `gcs` to the pipeline
- create a test deployment that has `bbr-atcdb` (with a large disk) in an instance that is not `db`
  - so that we avoid filling the Db's disk
- update vault config 
  - so that we don't hardcode the creds

Thanks!

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**
Today in the morning @cirocosta and I:
- deployed large disk vm with job `bbr-atcdb` and `database-backup-restorer`. The reason we created the vm with large disk is that the size database of production is about 40G, though the `pg_dump` does the compression, but we still need more space for the backup. 
- bbr backup successfully ran on the large disk vm. The size of the backup file is about 1.4G, compared to the original size of the database 40G, it is pretty nice.

**Next steps:**
- upload the backup to gcp. We've drafted the gcp resource, while it seems we can only upload one file to the bucket. However the backup is a directory which contains a `metadata` file and a tar file which is the actual dump of the database.
- update vault config

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**
@kcmannem and I:
- made the gcs-resource work. In that case we could upload the backup to gcs.
- Due to gcs-resource can handle only one file a time, we tarred `metadata` and backup file.

**Next steps:**
- Discuss the place for the pipeline.
- Refine the pipeline with enabling vault for credentials.
- Discuss the solution for restore

**Comment by YoussB** [comment]
### Dev Notes:
- The pipeline is checked in the ci repo and is currently running in our prod environment.
*Remaining steps:*
- [ ] in order for the pipeline to run we had to manually change the config file to read the correct username, as for some reason the username (read from the bosh link) was incorrect. We need to figure out why this happened.
- [ ] try running a restore on a prod-like environment.

**Comment by zoetian** [comment]
Dev Notes:

@cirocosta and I figured that:

- the default value of `postgresql.role.name:` in file https://github.com/concourse/concourse-bosh-release/blob/92175ab75e908a2367f526dffb78ff262c852983/jobs/bbr-atcdb/spec#L45-L48 is not empty, and always set to atc, whereas in its template file: https://github.com/concourse/concourse-bosh-release/blob/92175ab75e908a2367f526dffb78ff262c852983/jobs/bbr-atcdb/templates/config.json.erb#L47-L49 the if logic would never be hold and fill in the `prostgresql.role.name` from `cdb`. 

Next Step:
- update the test file in: https://github.com/concourse/concourse/blob/master/topgun/bbr_test.go
- update the spec file, and change the default value from "atc" to empty

**Comment by taylorsilva** [comment]
Waiting for PR's to be merged and then this can be closed:

- https://github.com/concourse/concourse-bosh-release/pull/41
- https://github.com/concourse/concourse/pull/4027

**Comment by taylorsilva** [comment]
### Notes about restoring

- we're thinking that we'll want to do the backup-restore'ing of prod right after a prod deployment. We want to do this so we can get a passed constraint on the version that was just deployed, that we can use during restore.
- doesn't need to trigger on prod-deploy finishing, can trigger on a timer instead
- we won't want restore to run if backup failed. Can have restore trigger whenever backup succeeds.
- For restoring:
  - could do a new bosh deployment of a web-only concourse with the `noop` flag
  - do a smoke test with `fly pipelines` as a way to verify there's data there and the restore worked...
  - create an ops-file that removes all workers from the manifest of the prod deployment, and we deploy the result of that ops-file (and maybe... add noop flag, reduce web to 1 instance)

**Comment by pivotal-jamie-klassen** [comment]
Yesterday @taylorsilva and I were trying to iterate on the backup-and-restore pipeline locally using [this bosh-lite docker image](https://hub.docker.com/r/bosh/bosh-lite) added as a docker-compose service alongside the usual docker-compose deployment. We had to bring our own self-signed SSL cert (added to that bosh director container via a volume mount) but were just starting to get some decent feedback. If future test pilots wish to continue taking this approach to developing, feel free to ping me with requests for help or general feelings about the technique!

**Comment by taylorsilva** [comment]
# Issue Status
###### Keep editing this comment with the current status of the issue

***

### Task List

- [ ] Update topgun bbr test to ensure it tests **all** bosh links used in the `bbr-atcdb` job
- [ ] Think about testing the TLS properties. Looks like we don't test TLS between concourse and the database which would need to happen first before we can test the TLS properties in our bbr job

**Comment by pivotal-bin-ju** [comment]
As part of the backup, we need `prod` to include a test pipeline that will be run when the restore is completed

**How to restore prod (in a new cluster)**
1. set up the new cluster with the same version as the prod at the time of the backup
1. make sure cluster has `0` workers so no pipelines are run
1. get the latest backup file from gcs
1. run `bbr restore`
1. run a sql statement on the database to pause the pipelines `UPDATE "public"."pipelines" SET "paused"=TRUE`
1. scale workers to `1`
1. use `fly unpause-pipeline` to unpause our test pipeline
1. check status of the pipeline to confirm cluster is working as expected
@nader-ziada

**Comment by pivotal-jamie-klassen** [comment]
made some progress today, but got a bit blind sided by https://docs.pivotal.io/pivotalcf/2-5/customizing/backup-restore/troubleshooting-bbr.html#structure-mismatch

**Comment by YoussB** [comment]
### Dev Note: 

- added our changes under the ci repo branch `test-restore` 
- the current problem is that restoring to the deployment fails due to the error mentioned be @pivotal-jamie-klassen  in the previous comment.

**Comment by YoussB** [comment]
- The error we had when restoring was: 
`Deployment 'test-restore' does not match the structure of the provided backup`
https://ci.concourse-ci.org/teams/main/pipelines/prod-db-backup/jobs/test-restore/builds/23#L5d20252a:12

**Comment by YoussB** [comment]
- Explanation
The instance groups with the restore scripts in the destination environment don’t match the backup metadata. For example, they may have the wrong number of instances of a particular instance group, or the metadata names an instance group that does not exist in the destination environment.

**Comment by taylorsilva** [comment]
### EOD Notes

- We wanted to see if we could take the prod backup artifacts and restore them onto a smaller prod-like deployment
- We used the `concourse-bosh-deployment` repo and a couple ops-files and created this:
```bash
#!/bin/bash

bosh -e vbox deploy -d concourse concourse.yml \
  -l ../versions.yml \
  --vars-store cluster-creds.yml \
  -o operations/static-web.yml \
  -o operations/basic-auth.yml \
  -o operations/backup-atc.yml \
  -o operations/storage-driver.yml \
  --var local_user.username=admin \
  --var local_user.password=admin \
  --var web_ip=10.244.15.2 \
  --var external_url=http://10.244.15.2:8080 \
  --var network_name=concourse \
  --var web_vm_type=concourse \
  --var db_vm_type=concourse \
  --var db_persistent_disk_type=db \
  --var worker_vm_type=concourse \
  --var deployment_name=concourse \
  --var web_instances=1 \
  --var storage_driver=overlay \
  --var worker_instances=1
```
- NOTE: we forgot that the `5.3.0` bosh release doesn't have the `defaults fix` for the `bbr-atcdb` job, so we had to manually upload the dev release and modify the `concourse.yml` and `versions.yml` to use the dev release on vbox
- Once that deployment was up we stopped the `worker` process to ensure that no pipelines ran and potentially caused havoc on prod for whatever unknown reason (paranoid~~)
- Then we ran the `bbr` command and pointed it to our deployment
```bash
bbr deployment --deployment concourse -u admin -p <secret> --ca-cert /tmp/ca.crt -t 192.168.50.6 restore --artifact-path ~/Downloads/bbr_artifacts\ 2/concourse-prod_20190709T050024Z/
```
- Watched the output of bbr and it eventually failed with this error:
```
pg_restore: dropping CONSTRAINT versioned_resources versioned_resources_pkey
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 3620; 2606 16561 CONSTRAINT versioned_resources versioned_resources_pkey concourse
pg_restore: [archiver (db)] could not execute query: ERROR:  cannot drop constraint versioned_resources_pkey on table public.versioned_resources because other objects depend on it
DETAIL:  constraint build_inputs_versioned_resource_id_fkey on table public.build_inputs depends on index public.versioned_resources_pkey
constraint build_outputs_versioned_resource_id_fkey on table public.build_outputs depends on index public.versioned_resources_pkey
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
    Command was: ALTER TABLE IF EXISTS ONLY public.versioned_resources DROP CONSTRAINT IF EXISTS versioned_resources_pkey;

2019/07/09 21:27:49 You may need to delete the artifact-file that was created before re-running.
exit status 1 - exit code 1
```

We went through the above steps one more time, extra-carefully, (paranoid~~~~~) and got the same error. Need to investigate why we're getting this error and if there's anything we can do about it. Maybe a config value we need to set in the `config.json` in the `bbr-atcdb` job?

**Comment by pivotal-bin-ju** [comment]
**Dev Note**
@YoussB and I  restored on a db only deployment and the new errors are below:
```
pg_restore: creating FK CONSTRAINT "public.worker_task_caches worker_task_caches_worker_name_fkey"
pg_restore: creating FK CONSTRAINT "public.workers workers_team_id_fkey"
pg_restore: creating ACL "public.FUNCTION pg_stat_statements_reset()"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 4619; 0 0 ACL FUNCTION pg_stat_statements_reset() vcap
pg_restore: [archiver (db)] could not execute query: ERROR:  function public.pg_stat_statements_reset() does not exist
    Command was: REVOKE ALL ON FUNCTION public.pg_stat_statements_reset() FROM PUBLIC;
```
With the `SUPERUSER` granted to the users in the deployment, the restore succeeded.
Here the change in the manifest
```yaml
        roles:
          - name: concourse
            password: ((postgres_password))
            permissions: ['SUPERUSER']
```

Here is the output of the restore:
```
[bbr] 2019/07/11 21:44:20 INFO - Starting restore of bbr-prod-test...
[bbr] 2019/07/11 21:44:20 INFO - Validating backup artifact for bbr-prod-test...
[bbr] 2019/07/11 21:44:54 INFO - Looking for scripts
[bbr] 2019/07/11 21:44:57 INFO - db/820e0d90-61f6-41ad-b57f-0f2a2df91169/bbr-atcdb/backup
[bbr] 2019/07/11 21:44:57 INFO - db/820e0d90-61f6-41ad-b57f-0f2a2df91169/bbr-atcdb/restore
[bbr] 2019/07/11 21:44:57 INFO - Copying backup -- 2.6G uncompressed -- for job bbr-atcdb on db/0...
[bbr] 2019/07/11 21:45:36 INFO - Finished copying backup for job bbr-atcdb on db/0.
[bbr] 2019/07/11 21:45:36 INFO - Running pre-restore-lock scripts...
[bbr] 2019/07/11 21:45:36 INFO - Finished running pre-restore-lock scripts.
[bbr] 2019/07/11 21:45:36 INFO - Running restore scripts...
[bbr] 2019/07/11 21:45:36 INFO - Restoring bbr-atcdb on db/820e0d90-61f6-41ad-b57f-0f2a2df91169...
[bbr] 2019/07/11 22:25:52 INFO - Finished restoring bbr-atcdb on db/820e0d90-61f6-41ad-b57f-0f2a2df91169.
[bbr] 2019/07/11 22:25:52 INFO - Finished running restore scripts.
[bbr] 2019/07/11 22:25:52 INFO - Completed restore of bbr-prod-test
[bbr] 2019/07/11 22:25:52 INFO - Running post-restore-unlock scripts...
[bbr] 2019/07/11 22:25:52 INFO - Finished running post-restore-unlock scripts.
```

So the `db-only` deployment works if users like to separate `db` from `concourse` deployment.
For next step, we are going to:
- document more about the `db-only` deployment and the collaboration with `concourse` deployment, and put this into the context `concourse` deployment and `bbr` lifecycle.
- try the `bbr` restore on a exact same cluster - both `concourse version` and `postgres version` are exact the same.

**Comment by scottietremendous** [comment]
**Secondary Acceptance Criteria**

[ ] Update our documentation around bbr with @matthewpereira

**Comment by pivotal-bin-ju** [comment]
After we restored from the concourse backup `concourse/5.3.1-dev.20190706T021536Z.commit.d2a8214` we still had the same error as the above.

```
pg_restore: dropping CONSTRAINT versioned_resources versioned_resources_pkey
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 3608; 2606 16561 CONSTRAINT versioned_resources versioned_resources_pkey concourse
pg_restore: [archiver (db)] could not execute query: ERROR:  cannot drop constraint versioned_resources_pkey on table public.versioned_resources because other objects depend on it
DETAIL:  constraint build_inputs_versioned_resource_id_fkey on table public.build_inputs depends on index public.versioned_resources_pkey
constraint build_outputs_versioned_resource_id_fkey on table public.build_outputs depends on index public.versioned_resources_pkey
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
    Command was: ALTER TABLE IF EXISTS ONLY public.versioned_resources DROP CONSTRAINT IF EXISTS versioned_resources_pkey;
```

So even we have the same version of the concourse and postgresql we still have this problem.

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**
I realized both the `db only` and `full concourse deployment` require users to do something manually for the restore.
I figured this out by adding script in the job `bbr-atcdb` before we executing the restore script from `database-backup-restorer`

Next Steps:
- [ ] Verify the restored environment by executing the test pipeline that we prepared before we did the backup.
- [ ] Integrate the restore to the pipeline `prod-db-backup`.
- [ ] Create pr for restore script in concourse-bosh-release repo (/jobs/bbr-atcdb/templates)

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**

So we verified the restored backup by 

1) adding  test pipelines in prod 
2) trigger the pipeline `prod-db-backup` to create a new backup that includes the test pipelines.
3) `bbr restore` after stop `web` and `worker` jobs.
4) pausing all the pipelines
5) ssh to the `web` and `worker` vms  to start the `web` and `worker`.
6) bosh port-forwarding  to web on the port 8080 by the command `bosh -e prod -d bbr-prod-test ssh web/0 --opts='-L 8080:localhost:8080'`
7) when access the web, we encountered the decryption error: 
```
failed to decrypt data that is encrypted
```
This error may be caused by the empty or wrong `ENCRYPTION_KEY`. Ideally, we should keep this the same as the production.

**Comment by zoetian** [comment]
**Dev Note**

 @cirocosta  and I worked on passing all jobs in the `test-restore` part of the previous pipeline we set. (https://ci.concourse-ci.org/teams/main/pipelines/prod-db-backup).
We managed to fixed all jobs till the first `test-restore-deployment`.

Next Step:
- [ ] modify the `version.yml` for concourse deployment for the current failing job
