### ISSUE TITLE
Concourse Groups bar in the web view should be responsive

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2130]

**Comment by Lindsayauchin** [comment]
## **Proposal:**
@sampeinado and I propose a solution that moves groups out of the top navigation bar and into a new subhead that can expand responsively so we can accommodate both long group names and grow and shrink with the browser. This new subhead area will increase as the number of groups grows and flows to the next row. 

As seen in this example below. 

![pipeline_groups_v1](https://user-images.githubusercontent.com/27746614/38387037-93f6ee52-38e4-11e8-8f2e-d10b5f1cf3a7.png)


Select to display the group in the pipeline view from the group name, unselect group name to hide it from the pipeline view (same as current behaviour). Select ALL groups with the 'all' button. 

![screen shot 2018-04-05 at 3 14 54 pm](https://user-images.githubusercontent.com/27746614/38387057-a387d6ba-38e4-11e8-95e1-82d1ca767205.png)

- [ ] Button style on select: 1px #979797 border, 10 px padding inside, font 12px #ffffff
- [ ] Subhead background colour:#0C1217
- [ ] Button style unselected: 1px #979797 fill, alpha: 10% with 10 px padding inside,  font 12px #ffffff alpha : 40%

**Comment by jama-pivotal** [comment]
All button should be a different issue!

**Comment by jama-pivotal** [comment]
We also don't quite need the Home icon anymore do we @Lindsayauchin ?

**Comment by joshzarrabi** [comment]
This would be *very* useful on releng. Right now we are weary of creating longer group names, which would make things more clear, because of the usability issues.

**Comment by B1Sandmann** [comment]
Hi, to me the proposal from @Lindsayauchin seems to be the best approach. From @jama-pivotal Proposals I'd like variante 2 best but imho all of these approaches might break again if the number of groups grow to much. At least for the time being all these proposals however should be able to solve our issue.
