### ISSUE TITLE
Pinning versions of resources in the web UI

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2508]
This issue is related to #1288, Specifically this story is the web related enhancements required to support #1288 

Looking at possible UI solutions to expose this functionality in the UI I created a small invision prototype to show the flow of pinning/unpinning in the resource page and marking a resource as pinned in the pipeline.

**Prototype:** 
https://pivotal.invisionapp.com/share/B4NN1FJHRPN

## Resource page: 
![2_00_resource_pinned_pipeline_paused](https://user-images.githubusercontent.com/27746614/46309498-8443e180-c58a-11e8-832a-652a7cd60376.png)
- [x] remove pause button
- [x] Change the power icon on version activation to checkmark
- [x] inactive state is represented by `X`
- [x] Add the pin icon (inactive and activate) 

Things to ignore
- [x] the last checked and check interval 
- [x] ignore the refresh icon (force check)

![2_00_resource_pinned](https://user-images.githubusercontent.com/27746614/46309551-a2a9dd00-c58a-11e8-9269-6cfd452f2df0.png)

- [x] On pin this is what the resource looks like, with the non pinned resources faded out
- [x] Notice how the "pin bar" is filled in now beside check interval

## Pipeline: 

State: No resources pinned.

![01_resource_pin](https://user-images.githubusercontent.com/27746614/44420823-ff0deb80-a54c-11e8-88eb-0b9c68248d34.png)

State: one resource pinned
![02_resource_pin](https://user-images.githubusercontent.com/27746614/44420925-3ed4d300-a54d-11e8-80d7-cef7098c1a23.png)
on hover:
![03_resource_pin_dropdown](https://user-images.githubusercontent.com/27746614/44531992-128d9380-a6c0-11e8-98ab-04dde4c518a2.png)

- [ ] Resource pinned notification with counter badge in top nav
- [ ] Dropdown list from the notifaction that lists the resource and version number that are current
- [ ] Users can navigate from the list item to that selected resources page
- [ ] A pin icon will also preceed the name of the resource on the pipeline render

### UI and Assets:

- [x] Pin: [pin_ic.svg.zip](https://github.com/concourse/concourse/files/2307081/pin_ic.svg.zip)
- [x] Close: [x_ic.svg.zip](https://github.com/concourse/concourse/files/2307714/x_ic.svg.zip)
- [x] Checkmark: [checkmark_ic.svg.zip](https://github.com/concourse/concourse/files/2307713/checkmark_ic.svg.zip)

- [x] Teal Hex: #03DAC4

**Comment by Lindsayauchin** [comment]
![2_00_resource_pinned_pipeline_via_cli](https://user-images.githubusercontent.com/27746614/44423792-ffaa8000-a554-11e8-88fe-a7f4544aa9e2.png)

**Comment by vito** [comment]
@jama-pivotal @Lindsayauchin We should get rid of that "pause" button - this new version pinning flow is intended to replace it.

**Comment by jama-pivotal** [comment]
If you pick up this issue please work off the `global-resources` branch, and also make sure to read @vito previous note around remove the "pause" button

**Comment by Lindsayauchin** [comment]
Added a tooltip description to the disabled pin button "enable via CLI"
![screen shot 2018-10-02 at 11 49 26 am](https://user-images.githubusercontent.com/27746614/46360714-fe7f6f00-c639-11e8-84ec-44f4cd436371.png)

**Comment by pivotal-jamie-klassen** [comment]
Thoroughly reading through all this for the first time. Trying to break this into smaller stories -- my hope here is that everything at the top level of indentation below could ostensibly be pursued in parallel (with some caveats around "pinned, regardless of CLI/API"), and stories with dependencies are further indented below their dependended-upon tasks.

1. Style change switching power buttons to checkmarks/X's.
1. pin bar shows whether resource is pinned via CLI
    * display `config_pinned_version`
    * show `pinned in CLI` tooltip
1. versions list has dummy pin icons (all have tooltip `enable via CLI`)
1. add `api_pinned_version` field to `/api/v1/teams/:team/pipelines/:pipeline_name/resources/:resource_name` endpoint
    1. pin bar shows whether resource is pinned via API (display `api_pinned_version`)
    1. versions list shows whether resource is pinned via API (display `api_pinned_version`)
        * clicking pin actually sets pin state
        1. remove pause button

1. pipeline page has pin icon which is brighter in color if there are any pinned resources (regardless of API/CLI)
    1. pin icon has badge that counts pinned resources
    1. hover on pin icon shows dropdown list of pinned versions

1. pipeline render shows pins on pinned resources

NOTES:
@Lindsayauchin @jama-pivotal:
* given a resource is pinned via API, should clicking the pin bar on the resource page unpin it, or just clicking on the relevant pin icon in the version list?
* given a resource is pinned via API, can I pin it to a different version by simply clicking the pin icon for the new version, or do i have to unpin the current version first?
* a few other style questions about the main bar on the resource page
    * vertical dividing lines?
    * different arrow styles?
    * how wide is the pin bar?

@vito:
* there should be a `fly pin-resource` -- I'm planning to write a story for that but might not get around to it today

**Comment by pivotal-jamie-klassen** [comment]
I might consider changing the JSON coming back from `/api/v1/teams/:team/pipelines/:pipeline_name/resources/:resource_name`. @clarafu maybe you can comment, having worked on the related features -- does the API give us a guarantee that a resource is in exactly one of the following states?
1. unpinned
2. pinned via CLI (config_pinned_version)
3. pinned via API (api_pinned_version)


what i'd love to see is rather than
```json
{
    "config_pinned_version": { "version": "foo" }
}
```
or
```json
{
    "api_pinned_version": { "version": "bar" }
}
```

would be something more like

```json
{
    "pinned_version": {
        "version": "foo",
        "config": true
    }
}
```

or

```json
{
    "pinned_version": {
        "version": "bar",
        "config": false
    }
}
```

I just want to ensure I'm not missing some cases where you have a version pinned both in the config and via the API -- maybe `fly` users would want that exposed? @vito perhaps you can comment.

**Comment by pivotal-jamie-klassen** [comment]
@jama-pivotal @Lindsayauchin it occurs to me that, should `fly pin-resource` be implemented, then the language 'pinned in CLI'/'enable via CLI' becomes ambiguous, because a resource version can then be pinned via `fly set-pipeline` where `version` is explicitly declared in the pipeline config, or `fly pin-resource`. Both cases involve the `fly` CLI and the distinction we're really trying to make is whether the version has been pinned by somebody hitting the atc.PinResourceVersion endpoint or by specifying a pinned version in the config (which takes precedence). I think the operative word is not _CLI_ in this case, but something like _pipeline config_, _config YAML_, or _pipeline definition_ -- maybe you folks can comment as to what the best ubiquitous language is (my guess would be 'pipeline config').

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen @jama-pivotal 
"enable via pipeline config" "pinned in pipeline config" is pretty long for a tooltip but, in the interest of avoiding any ambiguity or confusion for the User lets go with it and get feedback.

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin another potentially relevant question is what about mobile users, who cannot hover? Should we be adding click triggers for the various tooltips? at least in this story it doesn't seem like any of the components with tooltips already have any click handlers so it's probably safe.

**Comment by Lindsayauchin** [comment]
We could introduce clicking the link twice for mobile users. Once to see the tooltip and the second to do the action.

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen re: combinations of version enabled/disabled and metadata expanded/collapsed.

Agreed that the version expanded that is not pinned should be dimmed down to a darker display to indicate disabled. Sorry that detail was left out of the design!

![2_00_resource_expanded](https://user-images.githubusercontent.com/27746614/47371041-079db200-d6b5-11e8-80f0-695b06301b73.png)

![2_00_resource_pinned_expanded](https://user-images.githubusercontent.com/27746614/47371042-079db200-d6b5-11e8-9a40-7b0a6ec0a5fd.png)

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin wondering about the background color on the per-version pin icons -- so far all the mockups show a dark grey background on the pin icons. This feels like the right thing to do when the resource has been pinned via the pipeline config (and thus these icons don't do anything, so grey feels "disabled"), but if the resource is unpinned, then maybe a full black background would make these icons feel more "clickable"?

**Comment by pivotal-jamie-klassen** [comment]
"enable" on the pin icon tooltip has felt a bit confusing. It feels like it could either mean "enable this button" or "enable this pin" (like pin the version). Perhaps wording like "disabled due to pipeline config" -- which still begs the question "how/why".

**Comment by Lindsayauchin** [comment]
![screen shot 2018-10-25 at 3 05 08 pm](https://user-images.githubusercontent.com/27746614/47524005-6dca3680-d867-11e8-82c7-3336043c3b12.png)
![screen shot 2018-10-25 at 3 04 53 pm](https://user-images.githubusercontent.com/27746614/47524011-71f65400-d867-11e8-8c07-8852b22ee8a9.png)
![screen shot 2018-10-25 at 3 06 46 pm](https://user-images.githubusercontent.com/27746614/47524080-a1a55c00-d867-11e8-8193-9065bf4cb53f.png)

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen 
As per James whiteboarding this morning. On/off switches are removed. 
Pinning tooltips content should be updated to "static pin" when pin is set in the config and "dynamic pin" when the pin is set in the UI. 

Anything not captured @jama-pivotal ?

Updated screens below. 

<img width="1077" alt="screen shot 2018-10-26 at 11 22 10 am" src="https://user-images.githubusercontent.com/27746614/47577094-133ae400-d914-11e8-9f93-d955cdf2f9ed.png">

<img width="1079" alt="screen shot 2018-10-26 at 11 43 59 am" src="https://user-images.githubusercontent.com/27746614/47577280-74fb4e00-d914-11e8-9b28-c7bbf63bee36.png">

**Comment by pivotal-jamie-klassen** [comment]
### Resource page
- [ ] have an empty pin bar
- [ ] show statically pinned version in pin bar
- [ ] show tooltip on pin bar when statically pinned
- [ ] highlight pinned version in version list
- [ ] dim non-pinned versions in version list

- [ ] remove power button logic (frontend and backend)

### notes
* "static/dynamic" vs "config/api" language should be consistent across the whole codebase

**Comment by pivotal-jamie-klassen** [comment]
Emotional rollercoaster continues:
- [ ] checkboxes for enable/disable
    * always black background
    * check image when enabled, empty box with light grey outline when disabled
    * clicking the box performs the state change
    * row is less opaque when disabled

**Comment by pivotal-jamie-klassen** [comment]
@jama-pivotal @Lindsayauchin Given our changing language preferences, should the tooltips now read `pinned statically` instead of `pinned in pipeline config`/`enable via pipeline config`?

**Comment by pivotal-jamie-klassen** [comment]
@kcmannem and I were working on this story and realized it would be good to show a "transition" state for when you have clicked the pin button, but the API call to pin/unpin is still loading. For the time being we blindly did this:
![screen shot 2018-11-01 at 9 33 19 am](https://user-images.githubusercontent.com/22056320/47854873-559f6d80-ddb9-11e8-8992-6b7a91bf3240.png)
@Lindsayauchin maybe you have a better idea for what the loading state should look like? in particular, the ellipsis on the pin button is not particularly attractive...

**Comment by pivotal-jamie-klassen** [comment]
Another aspect of this story that hasn't yet been documented here is the auth-related behaviours -- we're assuming the following behaviours:
* when unauthenticated, the pin buttons and checkboxes appear as normal, but clicking on them redirects to login.
* when logged in but without the requisite role to pin or enable/disable versions, the pin buttons and checkboxes should be grayed out (I'm assuming the usual 0.5 opacity for now)
@jama-pivotal @Lindsayauchin is this fair?

**Comment by Lindsayauchin** [comment]
@pivotal-jamie-klassen  
Can we use a material design styled indeterminate circular indicator here to show the progress of the request?

![screen shot 2018-11-05 at 9 57 02 am](https://user-images.githubusercontent.com/27746614/48005418-687bb000-e0e1-11e8-9201-bd1b1d03a714.png)

Animaed as below: 
![46361065-c4629d00-c63a-11e8-9088-c83e5bcbbfb1](https://user-images.githubusercontent.com/27746614/48005501-9fea5c80-e0e1-11e8-8ff5-ee471e92a22b.gif)

**Comment by vito** [comment]
We've already got a spinner animation (see in-flight job steps) so we
should probably either reuse that or make both consistent?

**Comment by Lindsayauchin** [comment]
@vito 
![nov-05-2018 13-51-52](https://user-images.githubusercontent.com/27746614/48019681-0a12f980-e102-11e8-92fc-aae8920832ee.gif)
That spinner always seemed like the image is one pixel off so it wobbles a bit. 

There is a proposal to add a loading status to the user in the dashboard when they are waiting between the play and pause steps here https://github.com/concourse/concourse/issues/2645 

In that case, 2645, it would be nice to add a loading spinner that was like the above example so that the transition from the play to pause buttons was clean.

So then updating loading spinners app wide to follow this case would be great for UI consistancy. @pivotal-jamie-klassen thoughts?

**Comment by jama-pivotal** [comment]
Created #2758 to separate out the auth button requirements

**Comment by pivotal-jamie-klassen** [comment]
Another question arises -- on the pipeline page, when you drop down the list of pinned resources, what order should they appear in? Alphabetical by resource name is a natural choice, but maybe in the order they are declared in the pipeline, or just whatever order the `/teams/:team/pipelines/:pipeline/resources` endpoint returns. @Lindsayauchin @jama-pivotal

**Comment by pivotal-jamie-klassen** [comment]
More edge cases for the dropdown on the pipeline page -- does it have a maximum width? it's possible that the version could be quite long. Maybe we should overflow with ellipsis, especially on a narrow (i.e. mobile) screen? I'm not quite sure what that means when the version has multiple keys (maybe each row has its own ellipsis...)

**Comment by pivotal-jamie-klassen** [comment]
Note to self that hovering over pin icon on pipeline page still needs to cause circular light-grey highlighted background

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin it's pretty tough to read a white number against a teal background -- maybe there's a more legible way to set up this badge?
![screen shot 2018-11-07 at 11 46 56 am](https://user-images.githubusercontent.com/22056320/48146419-f04cf000-e282-11e8-8591-8baba44a3e3a.png)

**Comment by Lindsayauchin** [comment]
I was going to save purple for later... but do you want to give this purple a try#8B02FF? : ) 
<img width="1033" alt="screen shot 2018-11-07 at 11 54 33 am" src="https://user-images.githubusercontent.com/27746614/48146844-f42d4200-e283-11e8-9d18-f15955e9e3d5.png">
<img width="839" alt="screen shot 2018-11-07 at 11 53 42 am" src="https://user-images.githubusercontent.com/27746614/48146845-f42d4200-e283-11e8-81ff-fef32a403162.png">

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin inb4 red looks like failure

**Comment by Lindsayauchin** [comment]
Let's go with this purple #5C3BD1.

As we discussed, this morning, lets make the following updates to the UI.

- [ ] background of the pinned resourse on the pipeline view with the white pin icon. 
- [ ] badge notification should be purple not red
- [ ] outline on the pinned version on the resource page should be purple with the white pin icon. 
- [ ] outline on the pinned version in the list should be purple with the white pin icon. 
## Pipeline
![screen shot 2018-11-08 at 12 23 17 pm](https://user-images.githubusercontent.com/27746614/48215834-1f319780-e351-11e8-9440-46887b765955.png)

## Resource page
![screen shot 2018-11-08 at 12 32 14 pm](https://user-images.githubusercontent.com/27746614/48216309-5b192c80-e352-11e8-9d3b-7bb8b3aa8052.png)
