### ISSUE TITLE
Distribute `concourse` binary as tarball containing all dependencies

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2643]
## What challenge are you facing?

Prior to one-big-repo (#2534) we were shipping a single `concourse_(os)_(arch)` binary that baked in all of the below:

* all of Guardian's dependencies (`iptables`, `tar`, `runc`, ...)
* all of the core resource types
* `fly` binaries for all platforms

This made building the `concourse` binary very cumbersome, and forced it to extract all this junk on start. This made local development awkward (no one ever used the `concourse` binary during dev), made workers slow to start (since they had to unpack everything), and forced the binary to version its extracted stuff, resulting in a growing set of resource types as users upgraded their `concourse` binary in-place.

## What would make this better?

With #2574 done, the binary no longer packages up the Guardian dependencies, and instead exec's out to `gdn`. And instead of baking in all the resource types, it's now pointed at a directory containing all of'em.

I don't think we want to lose the convenience of "download this and drop it on your machine", so it might be nice to still have one big `.tgz` that you can extract somewhere and run. And instead of mirroring all the dependencies, maybe our releases can just link to them, since all the resources have their own GitHub releases.

So here are the release assets I'd like to see uploaded:

```
concourse-4.3.0-linux-amd64.tgz:
- ./concourse
- ./gdn
- ./resource-types/...
- ./fly-assets/...

concourse-4.3.0-windows-amd64.tgz:
- ./concourse.exe
- ./fly-assets/...

concourse-4.3.0-darwin-amd64.tgz:
- ./concourse
- ./fly-assets/...

fly-4.3.0-linux-amd64.tgz:
- ./fly

fly-4.3.0-windows-amd64.tgz:
- ./fly.exe

fly-4.3.0-darwin-amd64.tgz:
- ./fly
```

Note that we're mirroring `gdn` in the tarball for convenience, but I don't see a need to mirror it at the toplevel. Same for the resource types. Thankfully these only have to be present in the Linux tarball.

## Are you interested in implementing this yourself?

heck yea dude

**Comment by vito** [comment]
* [x] How to point the `concourse` binary at the `gdn` binary?
  * Let's just instruct the user to install both to `$PATH`?
* [ ] How to point the `concourse` binary at the resource types?
* [ ] How to point the `concourse` binary at the `fly` assets?
* [ ] Build `fly` binaries across all platforms in the pipeline.
  * Where to store them?
* [ ] Build `concourse` binaries across all platforms in the pipeline.
  * Where to store them?
* [ ] Determine the set of "core" resource types that we should ship with.
  * Maybe this should just be the same as today, but we've at least made it easy to point to them from your pipeline now that they're all semver'd.
