### ISSUE TITLE
topgun/k8s: ensure DNS proxying works

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3103]
Hey, 

Right now, by default, users who consume the [Helm Chart](https://github.com/helm/charts/blob/master/stable/concourse/README.md) use the `concourse/concourse:5.0.0` image which makes use of DNS proxy that we set up to allow the garden containers to use the DNS settings from the pod that runs the worker.

https://github.com/concourse/concourse/blob/02a90a4d0e99ca00767bda0b83189215543efe45/ci/dockerfiles/rc/Dockerfile#L19-L21

https://github.com/concourse/concourse/blob/02a90a4d0e99ca00767bda0b83189215543efe45/cmd/concourse/worker_linux.go#L120-L143

https://github.com/concourse/concourse/blob/02a90a4d0e99ca00767bda0b83189215543efe45/cmd/concourse/dns.go#L13-L14

Once the worker gets started, as such variable is configured, a goroutine is created to perform DNS proxying from the garden containers to the resolver configured for the worker pod.

Here's a diagram of what goes on:

```

                                .--> allows us to discover the address of
                                |    other instances in the VPC by name
 VM-----------------------------+-----------
 |                              |
 |    /etc/resolv.conf:         |
 |      nameserver 169.254.169.254    //  instance's metadata server
 |      search c.$GOOGLE_PROJECT_NAME.internal google.internal   
 |     
 |    POD ------------------------------------  (10.11.2.8)
 |    |  
 |    |
 |    |   worker container ....(same net namespace as the whole POD)
 |    |     +concourse worker process (baggageclaim; beacon; dns proxy)
 |    |     +gdn process
 |    |
 |    |
 |    |                         .---> allows us to discover the address of
 |    |                         |     other pods and services accross the cluster
 |    |      /etc/resolv.conf:  |
 |    |        nameserver 10.12.0.10   // kube-dns (or coredns) service address
 |    |        search hush-house.svc.cluster.local svc.cluster.local cluster.local c.cf-concourse-production.internal google.internal
 |    |       
 |    |      garden container ----------------
 |    |      | 
 |    |      |  /etc/resolv.conf:
 |    |      |    nameserver 10.11.2.8   // worker pod address
 |    |      | 


HAVING GARDEN_DNS_PROXY ENABLED

  pod
    /etc/resolv.conf
      nameserver $kube-dns
      search $shaudhs

  container
    /etc/resolv.conf
      nameserver $pod_ip



NOT HAVING GARDEN_DNS_PROXY ENABLED

  pod
    /etc/resolv.conf
      nameserver $kube-dns
      search $shaudhs

  container
    /etc/resolv.conf
      nameserver $kube-dns
      search $shaudhs


```

This issue would then validate:

- whether one can get pods/services' addresses from within a garden container; and
- whether those containers can have the expected connectivity without external routes.

In case we encounter unexpected results, we can then report those back to upstream ([`helm/charts`](https://github.com/helm/charts) so that users don't get confused about it, document the behavior and eventually see with runtime if we can get problems solved (if any found).

**Acceptance Criteria**

- Verify that when you have tasks running, it can reach k8s services. We can perform this verification via a test. 

Thanks!

**Comment by cirocosta** [comment]
Also, I noticed that we don't configure the [`dnsConfig`](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy) field for the `worker` pods that get created through the [`[release]-worker` Statefulset](https://github.com/helm/charts/blob/8e4282c9c05bf246c655a499efc00b35db3f7472/stable/concourse/templates/worker-statefulset.yaml) 🤔

**Comment by cirocosta** [comment]
See https://github.com/concourse/concourse/issues/3610

**Comment by ClumsyPotato** [comment]
I am currently working on a pipline that faces this scenario

I am trying to perform a code analysis with sonarqube inside my pipeline.
I am perfoming the analysis with the maven plugin and i am sending the result to my sonarqube server inside a job.
Concourse and sonarqube are both deployed on kubernetes.

At the beginning i faced the problem that sonarqube server was not reachable from inside the garden runtime.
Then i added 
CONCOURSE_GARDEN_DNS_PROXY_ENABLE  
CONCOURSE_WORKER_GARDEN_DNS_PROXY_ENABLE 

And i was able to to reach the sonarqube server
However i cant resolve services. Will investigate further and post my result if this is interresting for this issue.

**Comment by taylorsilva** [comment]
# Issue Status
###### Keep editing this comment with the current status of the issue

***

### Task List

- [ ] Figure out how to connect to x from `garden`:
  - [ ] other pods
  - [ ] other services (e.g. cloudsql)
- [ ] keep adding to this list...

**Comment by taylorsilva** [comment]
### Dev Notes

- We were looking at https://github.com/concourse/concourse/blob/02a90a4d0e99ca00767bda0b83189215543efe45/ci/dockerfiles/rc/Dockerfile#L19-L21
and wanted to know why there were two environment variables for one setting. We figured out that `CONCOURSE_WORKER_GARDEN_DNS_PROXY_ENABLE` is from an older version of concourse (we think). We're pretty sure `CONCOURSE_GARDEN_DNS_PROXY_ENABLE` is for the current version of concourse because we see it in the `--help` for the worker.

**Comment by cirocosta** [comment]
Hey,

Yesterday, @pivotal-bin-ju and I worked on first manually verifying few scenarios, and then went on with adding the test cases for:

- having dns proxy enabled
  - resolving full address
  - resolving short address
- not having dns proxy enabled
  - resolving full address
  - resolving short address

Something else we could also test is the behavior of `CONCOURSE_GARDEN_DNS_SERVER`, which I'm not 100% on whether it'd completely override the default `/etc/resolv.conf` or append to it :thinking:

Thanks!

**Comment by cirocosta** [comment]
Hey,

Yesterday, @YoussB  and I went forward with the `CONCOURSE_GARDEN_DNS_SERVER` testing to check what's the behavior that we get to.

We also refactored the test to be table-driven so one can more easily reason about all of the possibilities at once.

IIRC we were having some trouble by the end of the day with a possible regression related to pods not starting (possibly related to the environment variables that we set - we changed a bit during refactoring).

Thanks!
