### ISSUE TITLE
Move Concourse resource base images to Bionic

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3266]
With the guidelines around standardizing the base images for the container images we ship around [`ubuntu:bionic`](https://hub.docker.com/_/ubuntu), this issue keeps track of the progress around those.

- [x] check resources not owned by the concourse team (baked resources and external resources).
- [x] Use an ubuntu-based Golang base for our builds
  - [x] review OK
  - [x] PR merged: concourse/concourse#3243
- [x] resources
  - [x] [git-resource](https://github.com/concourse/git-resource)
    - [x] migrate to builder/intermediate images ubuntu:bionic
    - [x] migrate actual image to ubuntu:bionic and build.
    - [x] run image tests successfully.
    - [x] run basic smoke tests.
    - ~~create a test suite for automated tests.~~
    - [x] review OK
    - [x] PR merged: concourse/git-resource#241
    - [x] released
  - ~~[archive](https://github.com/concourse/archive-resource)~~
    - deprecated
  - [x] [bosh-io-release-resource](https://github.com/concourse/bosh-io-release-resource) 
    - [x] review OK
    - [x] PR merged: concourse/bosh-io-release-resource#18
    - [x] released
  - [x] [bosh-io-stemcell-resource](https://github.com/concourse/bosh-io-stemcell-resource) 
    - [x] review OK
    - [x] PR merged: concourse/bosh-io-stemcell-resource#23
    - [x] released
  - [x] [cf-resource](https://github.com/concourse/cf-resource) 
    - [x] review OK
    - [x] PR merged: concourse/cf-resource#69
    - [x] released
  - [x] [github-release-resource](https://github.com/concourse/github-release-resource) 
    - [x] review OK
    - [x] PR merged: concourse/github-release-resource#82
    - [x] released
  - [x] [docker-image-resource](https://github.com/concourse/docker-image-resource) 
    - [x] review OK
    - [x] PR merged: concourse/docker-image-resource#256
    - [x] released
  - [x] [hg-resource](https://github.com/concourse/hg-resource) 
    - [x] review OK
    - [x] PR merged: concourse/hg-resource#11
    - [x] released
  - [x] Decide if we're shipping [mock-resource](https://github.com/concourse/mock-resource)
    - [x] [mock-resource](https://github.com/concourse/mock-resource)
       - [x] review OK
       - [x] PR merged: concourse/mock-resource#2
       - [x] released
  - [x] [pool-resource](https://github.com/concourse/pool-resource) 
    - [x] review OK
    - [x] PR merged: concourse/pool-resource#45
    - [x] released
  - [x] [registry-image-resource](https://github.com/concourse/registry-image-resource) 
    - [x] review OK
    - [x] PR merged: concourse/registry-image-resource#14
    - [x] released
  - [x] [s3-resource](https://github.com/concourse/s3-resource) 
    - [x] review OK
    - [x] PR merged: concourse/s3-resource#120
    - [x] released
  - [x] [semver-resource](https://github.com/concourse/semver-resource) 
    - [x] review OK
    - [x] PR merged: concourse/semver-resource#88
    - [x] released
  - [x] [time-resource](https://github.com/concourse/time-resource) 
    - [x] review OK
    - [x] PR merged: concourse/time-resource#36
    - [x] released
  - [x] [tracker-resource](https://github.com/concourse/tracker-resource) 
    - [x] review OK
    - [x] PR merged: concourse/tracker-resource#24)
    - [x] released
  - [x] Resources that are not shipped with Concourse but would still be impacted by the resource pipeline change:
     - [x] [datadog-event-resource](https://github.com/concourse/datadog-event-resource)
       - [x] review OK
       - [x] PR merged: concourse/datadog-event-resource#7
       - [x] released
     - [x] [concourse-pipeline-resource](https://github.com/concourse/concourse-pipeline-resource)
       - [x] review OK
       - [x] PR merged: concourse/concourse-pipeline-resource#52   
       - [x] released
- [x] update the [pipelines for the resources](https://github.com/concourse/concourse/tree/master/ci/pipelines/resources) to use `ubuntu:bionic` alongside `alpine` 
  - [x] PR merged: concourse/concourse#3364

 Thanks!

---

Note: as a follow up, we might want to add a disclaimer regarding which base image Pivotal supports for enterprise customers.

**Comment by chenbh** [comment]
Notes:
* `ubuntu:bionic` image is much larger than `alpine` (88.1mb vs 5.52mb)
* try to migrate to `wget` as it's about half the size of `curl` when including dependencies (3.7mb vs 11.9mb)

**Comment by jchesterpivotal** [comment]
> * `ubuntu:bionic` image is much larger than `alpine` (88.1mb vs 5.52mb)

These are the uncompressed size in the docker daemon cache. The registry sizes are 32Mb and 3.4Mb respectively. Still a notable ratio, but less striking in absolute terms.

Unless you're downloading from scratch every time, the cost of fetching Ubuntu's layers will be amortised over all of the uses. It's noticeable for the first pull but it's basically a nil-all draw after that.

**Comment by pn-santos** [comment]
I'm curious, what were the reasons to move from alpine to ubuntu? (was it musl related or something else?)

**Comment by vito** [comment]
@pn-santos The core motivation here is that Pivotal has a support agreement with Canonical and by using Ubuntu images we're able to leverage their support for customer issues if needed. 

We were using Alpine because it's tiny, so it wouldn't inflate the `.tgz` distribution. Now that we're planning on extracting them (see comments in #3003) it won't matter as much, though admittedly there will be a bit more disk usage on the workers (but only for whichever resource types are actually used).

We considered using both Alpine for open-source and Ubuntu for customer images but would prefer not to have to maintain both in the long run.

**Comment by cirocosta** [comment]
@vito,

Regarding 

> - [ ] Decide if we're shipping mock-resource ,

we didn't have `mock-resource` shipped in the 4.x series (see https://github.com/concourse/concourse-bosh-release/tree/v4.2.3/packages), but now it's in 5.0 (comes from the [`hoisting of linux dependencies`](https://github.com/concourse/concourse/blob/master/ci/tasks/scripts/hoist-linux-dependencies) from the `dev-image`).

I guess that means that 5.1.0 we'd like to have `mock-resource` also built with `ubuntu` then (assuming we're shipping it with the `mock-resource`). Is that right?

Thanks!
