### ISSUE TITLE
Implement a new scheduler algorithm for determining job input candidates

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3602]
Tentative issue to track known issues with the [current algorithm](https://github.com/concourse/concourse/tree/e7f017be3ad546503412216f20134af2c09b5eaa/atc/db/algorithm) and track any progress/thoughts on a new algorithm to replace it.

Problems with the current algorithm:

* It loads up all versions and build inputs and outputs for the entire pipeline, meaning memory use and network transfer from the DB will increase as this data set grows. This is also slow as it involves a bunch of joins across a ton of data. See #2624, #3487, #3426.
  * We are also careful to cache this so it's only loaded when the data changes, but that can only help so much - periodic jobs or resources will invalidate the cache anyway.
* The algorithm itself is fairly brutal; it's hella optimized but prone to worst-case scenarios where it churns and uses a ton of CPU. And it's difficult to instrument without slowing it down.

An experimental new algorithm lives on the [`algorithm-experiment` branch](https://github.com/concourse/concourse/tree/algorithm-experiment/atc/db/algorithm).

**Comment by chendrix** [comment]
hi, do this plz

**Comment by vito** [comment]
This is going to be dependent on #413.

The new algorithm uses build history as the source of truth, i.e. the latest build for a given job becomes the first candidate to consider for downstream builds. This is different from the old algorithm, which went through *versions*, newest-to-oldest, and tried to find matching sets.

This approach has a ton of benefits, but breaks expectations for the "pin old version -> re-trigger job -> un-pin old version" flow, as the new build's older version will now be the first candidate to consider.

**Comment by vito** [comment]
Quick update: in working support for `version: every` in to this new algorithm we've landed on an approach that should make 'resource causality' (https://github.com/concourse/concourse/issues/1538) much cheaper to query for. We'll be tracking the history of which builds from which jobs "fed into" each build. So now 'causality' can be done by just following that flow through the new `build_pipes` table and collecting the input/output versions along the way. Pretty neat!

**Comment by clarafu** [comment]
Update: We are removing the independent build inputs table which is used by the preparation step (showing resolved inputs for the progress of pending builds) because the way the scheduler worked was it would resolve the inputs independently for the independent build inputs and then did another resolve for all inputs for the next build inputs. This method worked before as we only needed to load up all the versions at the beginning and just compute in memory the inputs twice. But with the new algorithm, we query during the computation of the inputs and doing the resolving of inputs twice will mean doubling the workload.

After some discussion, we decided to have the resolving of all inputs construct a list of input candidates and save either a version or an error for every input. The algorithm will always try to compute every input and after resolving all the inputs, it will determine whether or not to schedule a new pending build depending if all the inputs have valid versions as the candidate. If there is an error within one of the input candidates, then a new pending build will not be scheduled. The error state within the candidate will be shown to the user as well as information about what went wrong (ex. pinned version is missing, the input is vouched for by job 1 and 2 but not 2).

**Comment by vito** [comment]
We're going to make a semantic change to `get` steps with `passed` constraints: the name of the `get` step will now refer to the name of the *output* from the referenced (`passed`) jobs. This way, in situations where the upstream jobs have multiple occurrences of the same resource (i.e. `version` and `final-version`), the name of the `get` step clearly disambiguates it.

This is a backwards-incompatible change, so we'll be bumping to 6.0, which we probably would be doing regardless as the new algorithm's `passed` constraint behavior is already subtly different - this just makes it clearer, because now they *explicitly* refer to job output sets.

To make the migration path easier, we can have static verification so that if you say `get: foo, passed: [a, b, c]` we can validate that the jobs `a`, `b`, and `c` all have an output named `foo`. This would catch scenarios where an input or output was renamed in the upstream jobs but the downstream job only referred to the resource.

**Comment by vito** [comment]
Update for https://github.com/concourse/concourse/issues/3602#issuecomment-484261510: rather than attempting all inputs and saving the partial inputs and collecting all the errors, we're going to just have the algorithm return the first error. It's costly and kind of difficult to present useful information going beyond the first error, so we'll just try to return the first one with as much detail as possible instead.

**Comment by clarafu** [comment]
We decided to save the partial inputs and the resolve error into the `next_build_inputs` table because it will allow us to show in the preparation pending build view the state of each input rather than the overall state of whether the algorithm was able to resolve or not. We will still be returning the first resolve error and setting a static error for all the later inputs that we have not successfully resolved yet. We can later show in the UI a different state (other than the current blocking error state) for the inputs that we have not yet gotten to resolving.

**TODOS:** 
- [ ] Returning the first error we hit in the algorithm and save it into the resolve_error column on the jobs table
    - [ ] Use resolve_error in preparation
- [ ] Implement pinned with passed constraints within the algorithm 

Later Todos:
- [ ] Show a different state for when the resolve error is the have not reached/attempted to resolve this input yet

**Comment by clarafu** [comment]
Added a BuildStatusPreparationSkipped status that can be returned by the build preparation endpoint in order to represent the state of an input that has not been attempted to fully resolve yet because of an error that was reached with a previous input. This state will need to be consumed by the web UI, maybe showing the state as just the input with a greyed out text and no spinning icon?

**Comment by vito** [comment]
Going back on my word for https://github.com/concourse/concourse/issues/3602#issuecomment-489140023, at least for now. I think having `get: x` refer to named outputs introduces a few uncomfortable situations.

1. In general, it makes jobs more tightly coupled. When I say `get: x, resource: y, passed: [a, b, c]` I now have to make sure `a`, `b`, and `c` all use `x` as their name for `y`. While this encourages consistency throughout the pipeline, it's also more to keep in your head, and potentially leads to changing jobs `b` and `c` just because `a` had to rename it (for whatever reason).
1. It makes it impossible to rename an input in a downstream job. `get` with `passed` is effectively "stuck" at whatever name was used at the earliest point in the pipeline. There's no "get output `x` of job `a` renaming it as `z`" syntax - we would have to add it.
1. This would be a backwards-incompatible change, which is fine (that's what semver is for), but it has a migration path that is somewhat difficult to reason about. You would basically have to audit all the names for all `get` steps, because now they have implications outside of the scope of the job. Jobs are currently designed to be fairly isolated and independent, so any trend away from this is cause for concern.

For now, I think we should just stick to today's behavior, which is to always pick the latest version for each resource.

/cc @pivotal-jwinters

**Comment by vito** [comment]
This looks to be a valuable index to add:

```sql
CREATE INDEX deleteme ON builds (job_id, id DESC) where status = 'succeeded';
```

Here's how the `EXPLAIN ANALYZE` looks with/without the index:

```sql
concourse@127:atc> EXPLAIN ANALYZE SELECT b.id FROM builds b WHERE b.job_id = 5 AND b.status = 'succeeded' ORDER BY b.id DESC;                                                             
+----------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                       |
|----------------------------------------------------------------------------------------------------------------------------------|
| Index Only Scan using deleteme on builds b  (cost=0.43..4598.27 rows=4685 width=4) (actual time=0.051..10.511 rows=5184 loops=1) |
|   Index Cond: (job_id = 5)                                                                                                       |
|   Heap Fetches: 1099                                                                                                             |
| Planning Time: 0.160 ms                                                                                                          |
| Execution Time: 10.891 ms                                                                                                        |
+----------------------------------------------------------------------------------------------------------------------------------+
EXPLAIN
Time: 0.088s
concourse@127:atc> DROP INDEX deleteme;                                                                                                                                                    
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
DROP INDEX
Time: 0.063s
concourse@127:atc> EXPLAIN ANALYZE SELECT b.id FROM builds b WHERE b.job_id = 5 AND b.status = 'succeeded' ORDER BY b.id DESC;                                                             
+------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                         |
|------------------------------------------------------------------------------------------------------------------------------------|
| Sort  (cost=16976.91..16988.63 rows=4685 width=4) (actual time=65.040..65.571 rows=5184 loops=1)                                   |
|   Sort Key: id DESC                                                                                                                |
|   Sort Method: quicksort  Memory: 436kB                                                                                            |
|   ->  Bitmap Heap Scan on builds b  (cost=185.63..16691.27 rows=4685 width=4) (actual time=2.725..62.929 rows=5184 loops=1)        |
|         Recheck Cond: (job_id = 5)                                                                                                 |
|         Filter: (status = 'succeeded'::build_status)                                                                               |
|         Rows Removed by Filter: 196                                                                                                |
|         Heap Blocks: exact=5792                                                                                                    |
|         ->  Bitmap Index Scan on builds_job_id  (cost=0.00..184.46 rows=4804 width=0) (actual time=1.629..1.629 rows=6416 loops=1) |
|               Index Cond: (job_id = 5)                                                                                             |
| Planning Time: 0.242 ms                                                                                                            |
| Execution Time: 65.851 ms                                                                                                          |
+------------------------------------------------------------------------------------------------------------------------------------+
EXPLAIN
Time: 0.124s
```

At face value it's a minor improvement but it really adds up. Prior to adding this index to our testing environment the `web` node backend connection pool was maxed out at 32, Postgres was showing high memory usage, etc. Adding the index seems to have improved things pretty dramatically. Unfortunately I can't figure out how to share our dashboard publicly, but here's a link capturing the time range for posterity:

https://app.datadoghq.com/dashboard/e2x-kuz-6md/concourse?screenId=e2x-kuz-6md&screenName=concourse&from_ts=1560047880818&live=false&tile_size=m&to_ts=1560048650000&tpl_var_environment=concourse-algorithm

Here's a screenshot for now:

![image](https://user-images.githubusercontent.com/1880/59154472-d1912080-8a40-11e9-89f9-41290934e78a.png)

A few things to note:

* Per-job scheduling time is now lower than ever.
* The connection pool became unstuck, though it continues to flirt with the 32 cap every now and then.
* The worker container count climbed prior to adding the index - this tends to happen when the connection pool is full as GC can't run.
* DB memory usage went down significantly
* Queries and DB CPU usage went up, but this seems to just be a result of the connection pool un-clogging; it's in the same ballpark it was in before.

**Comment by vito** [comment]
Another thing that may help: currently we query both `build_resource_config_version_inputs` and `build_resource_config_version_outputs` all the time to find versions that were produced by builds. More specifically, we care about succeeded builds for a particular job.

What if we had a single table that made this querying easier, by containing all inputs + outputs, only for succeeded builds, and had a `job_id` column directly on the table so we don't have to join? We could insert into it whenever a build succeeds. A materialized view is tempting here but it'd probably be refreshed way too often. Might be better to just denormalize it.

**Comment by pivotal-jwinters** [comment]
What if we just started adding implicit outputs to the `build_resource_config_version_outputs `?

**Comment by vito** [comment]
> EDIT: Actually on second thought keeping explicit outputs separate seems nicer. I wonder if we can add some better indexing to help us here as well. It just seems like we'd be duplicating a lot of data if we denormalize this table.

Yeah we've actually had problems in the past from putting implicit outputs in there. We used to, but it made it hard to distinguish between them on e.g. the resource page ("inputs to" / "outputs of").

I agree that duplicating the data into this table could be problematic. We'll spike on it and see what the disk usage ends up being. If it ends up being a lot of disk usage but a huge win in terms of scheduling performance we may want to keep iterating on it and find ways to lower the disk usage. The only column I'm really worried about is `version_md5` - maybe we could find an alternate approach to that?

An intermediate step could be to just add `job_id` to the inputs/outputs tables. We'd still need to join to only match succeeded builds though. :/

**Comment by vito** [comment]
One simple idea (from @clarafu): get rid of the input/output tables and just store a boolean column indicating if it's an output.

**Comment by clarafu** [comment]
After adding a cache mechanism to the algorithm through the versions db methods in order to save the number of queries needed to be run within the same scheduler tick, we saw that the web CPU and memory metrics start climbing significantly. 

<img width="726" alt="Screen Shot 2019-06-21 at 2 58 48 PM" src="https://user-images.githubusercontent.com/19290703/59945276-18b1e500-9435-11e9-9003-71ad07063420.png">
<img width="724" alt="Screen Shot 2019-06-21 at 2 58 39 PM" src="https://user-images.githubusercontent.com/19290703/59945278-18b1e500-9435-11e9-9667-acaab5d63ab7.png">

The two graphs show that before the line was the deploy with a caches implemented and after the line was when we removed it. Adding the caches had benefits too, such as less db connections and less DB CPU usage.

<img width="715" alt="Screen Shot 2019-06-21 at 3 00 56 PM" src="https://user-images.githubusercontent.com/19290703/59945372-69c1d900-9435-11e9-99a4-1d0383b009e9.png">
<img width="721" alt="Screen Shot 2019-06-21 at 3 00 47 PM" src="https://user-images.githubusercontent.com/19290703/59945373-69c1d900-9435-11e9-874d-72bde806a240.png">

We are currently trying to see if we can just cache the queries that seem to be the bottleneck, in this case seems to be the SuccessfulBuildOutputs query. We can possibly only cache that query for an hour at a time (and not for just a scheduler tick because build outputs will never change).

**Comment by cirocosta** [comment]
Thanks for sharing, @clarafu !

This reminded me of @pivotal-jamie-klassen sharing some thoughts around the idea of how doing more work in the web nodes instead of the DB could be a way of scaling where it's easy to scale (web nodes, as they're stateless) 🤔

**Comment by pivotal-jamie-klassen** [comment]
@cirocosta I remember bringing that up in reference to @avanier's observation that Postgres is the system's bottleneck.

**Comment by clarafu** [comment]
After deploying the algorithm environment with only caching the build outputs, it looks like database connections seem to be lower 

<img width="715" alt="Screen Shot 2019-06-24 at 1 34 14 PM" src="https://user-images.githubusercontent.com/19290703/60039534-f0202a00-9684-11e9-96d3-19366f9e2a5c.png">

But the web memory usage is higher again and is continuing to climb, I'm assuming it will plateau once most of the build outputs have been cached and it will retain for an hour until the cache gets refreshed. 

<img width="716" alt="Screen Shot 2019-06-24 at 1 34 42 PM" src="https://user-images.githubusercontent.com/19290703/60039599-1776f700-9685-11e9-985b-076883ad081d.png">

On the other hand, the web CPU seems to be very similar to the metrics when we removed caching. 
<img width="720" alt="Screen Shot 2019-06-24 at 1 34 37 PM" src="https://user-images.githubusercontent.com/19290703/60039647-383f4c80-9685-11e9-98ea-b3d53f5e6860.png">

From these metrics, it seems like just caching the build outputs seems to be the best choice (will keep an eye on the memory usage and db connections) since it helps lower the db connections without (too) much overhead.

**Comment by clarafu** [comment]
@cirocosta Ya basically a big part of this new scheduler is to move most of the work to the web nodes because with our drills testing with the 5.3.0 and new algorithm, we found that in 5.3.0 a lot of slowness was caused by the db connections being overrun with the LoadVersionsDB calls taking super long and everything else being delayed because of that.

**Comment by clarafu** [comment]
One thing that is interesting is that there are now two jobs that consistently take longer than other jobs to schedule (the purple and blue line are jobs 5 and 10). 

<img width="721" alt="Screen Shot 2019-06-24 at 1 33 08 PM" src="https://user-images.githubusercontent.com/19290703/60040672-805f6e80-9687-11e9-924d-666073c97bc7.png">

They are both jobs that have quite a few inputs fanning in, we might want to investigate the cause of it because previously, only the purple line was way above the other jobs but now the blue job also takes a lot longer than before. 

<img width="2046" alt="Screen Shot 2019-06-24 at 1 55 41 PM" src="https://user-images.githubusercontent.com/19290703/60040830-dc29f780-9687-11e9-86b7-9cbf2e768c4f.png">

**Comment by vito** [comment]
Here's a fun update: our control environment, running the old algorithm, finally ran out of memory. We knew this was a fundamental flaw with the old algorithm, as the dataset it loads into memory keeps growing and growing. Just never saw it happen.

![image](https://user-images.githubusercontent.com/1880/60187662-eec53d80-97fb-11e9-946e-b73a2d950c5a.png)

The environment is basically dead now - unable to schedule any builds and the `web` VMs are unresponsive.

**Comment by clarafu** [comment]
Investigating the two jobs that take significantly longer than the rest, we figured out that it was because there were jobs that were it's passed constraints that had pending builds that were stuck for days. This was causing the algorithm to not able to find candidates quickly. We created an issue for the pending build bug here #4065. After we manually fixed the pending builds by aborting them, the scheduling time for one of the jobs decreased back down to the rest but the tenth job only decreased by half, making it so the scheduling time was approx 5 seconds while the rest are around 1 s. 

<img width="478" alt="Screen Shot 2019-06-26 at 10 22 42 AM" src="https://user-images.githubusercontent.com/19290703/60187883-61361d80-97fc-11e9-9298-31c1611ce2c5.png">

**Comment by clarafu** [comment]
Interesting thing is that after we manually fixed the stuck pending builds, the web CPU went down by a lot and is approx 700 MB vs before it was around 3 GB. We thought the web CPU was so high because of caching in general, but it was probably because we were caching a loottt of builds due to that stuck pending build.

<img width="1319" alt="Screen Shot 2019-06-26 at 10 28 19 AM" src="https://user-images.githubusercontent.com/19290703/60188376-2c769600-97fd-11e9-8d04-d54991908649.png">

The drop near the end of the graph is probably when we the caches were refreshed an hour after we manually aborted the pending builds. And the web CPU has now been consistently low.

**Comment by clarafu** [comment]
When we were investigating why the tenth job was taking so much longer to schedule than the others, we tried adding a stricter version constraining to the builds that we return for the passed constraint job. This means that we tried to make it so that it will only return builds of the passed job that also had the same versions for all the algorithm candidates that we have determined so far instead of only one candidate which was what we were doing before. 

So now that we found out that the slowness was caused by those stuck pending builds, we decided to remove the version constraining to all candidates (which might have been too complicated) and make it to only constrain the builds that we return to the single version for the candidate we are trying to determine for. After we made that change, the tenth job scheduling time decreased even more and is now takes the same approx time to schedule as the other jobs.
 
<img width="482" alt="Screen Shot 2019-06-26 at 12 15 50 PM" src="https://user-images.githubusercontent.com/19290703/60197136-d7428080-980c-11e9-85e5-03cfd3783191.png">

Also, the db connections decreased because the complicated constraining to all candidates resulted in a lot more queries needed to be run.

<img width="479" alt="Screen Shot 2019-06-26 at 12 15 55 PM" src="https://user-images.githubusercontent.com/19290703/60197188-ede8d780-980c-11e9-8764-8a8dc1d219c5.png">

**Comment by clarafu** [comment]
We also changed the metrics for job scheduling to show a line per job_id and not job name because our deployment had a lot of the same pipelines which means a lot of the same job names. This resulted in the metrics taking into account the scheduling time of all the jobs with the same name, and does not show the scheduling time for each job individually (which would've helped us find the pending builds bug faster). It now looks like this

<img width="481" alt="Screen Shot 2019-06-26 at 12 23 47 PM" src="https://user-images.githubusercontent.com/19290703/60197534-8da66580-980d-11e9-8129-0d036fe4e9fe.png">

**Comment by clarafu** [comment]
I think we are in a pretty good place right now, I will start on cleaning up the branch and doing a few more tests but I think this might be a good time to do a quick summary of interesting things we did to optimize or improve on the algorithm.

- **Optimizing queries** : This was one of the things we did that made the most impact on the performance. Basically we kept a controlled environment that stresses out the scheduler and algorithm in order to show which queries are the bottleneck. We used the `EXPLAIN ANALYZE` to show which part of the query was taking the longest and most of the time we would end up needing to rewrite the query or adding indexes. For example, the original query would join with the `resource_config_versions` table in order to scope the query down to a single version but instead we could rewrite it to not use a join (since the versions table is huge) and use a subquery to `SELECT` that version from the `resource_config_versions` table and use that to scope the query down to the version. There was one case where we ended up adding a whole new table in order to further optimize because of the nature of the query being incredibly slow even with the proper indexes (I'll talk more about this in the `successful_build_versions` section below).

- **Caching**: We tried to cache in memory all the results of queries we made within the algorithm in order to reduce the number of db connections/queries we needed to run (since sometimes the algorithm will recurse and end up calling the same queries), but this resulted in climbing Web memory usage and almost double the CPU so we then decided to just cache the queries that seem to be a bottleneck. The only query we found to be a bottleneck was the query to fetch the build outputs, so as a result we now only cache this build outputs query, and keep the results for 1 hour per build.

- **Jobs max in flight** : We added a jobs max in flight in order to have the ATCs not be scheduling more jobs than it is able to with the number of DB connections it has. We set the number to be 32 but we haven't done enough testing to see if that is a suitable number.

- **DB connection pools** : This seemed to make a huge difference because before we added a separate connection pool for GC, whenever the DB connections were full because of the busy algorithm queries, containers and volumes would start piling up and end up overloading the workers. We ended up adding a separate connection pool for GC that allows a max connection of 1. We also lowered the number of connections allowed for the API because we found that even in large deployments (such as wings) we would see that the highest number of connections it would get to is approx 10 but it usually averages around 2-5 connections. This let us increase the number of connections for the backend. In general I think we want to give different connection pools to each critical piece of Concourse so they don't starve each other, and just base the size of the pool on empirical data.

- **Limiting query results** : As the algorithm testing environment continued to collect more builds and versions and basically grew "older", some of the queries it was running within the algorithm were getting slower and slower. That is because of queries that were asking the DB to return all the builds for a job, and as more and more builds are created, the more rows those queries need to return. So as a result, we added a limit to the number of rows for the queries that ask for builds within a job and will continue to query again for the next set of rows whenever we have finished trying out the first set of builds returned. To clarify with an example, we return the first 100 builds and we then use those 100 builds for the algorithm and if we still haven't found a proper candidate with those 100 builds, we will then query for the next 100 builds after that and will continue with this pattern until we either find a candidate or reach the end of the builds.

- **Successful build versions table** : When we were trying to optimize the algorithm queries, we ran into one query that was run really often but no matter how much we optimized the query it wasn't able to be fast enough to not be a bottleneck. For context, the query was returning the build inputs and outputs for "succeeded" builds that were related to a job. As a result, we ended up creating a new table called `successful_build_versions` which contains all the succeeded build inputs/outputs. Using this new table, the query became a lot faster and no longer became the bottleneck.

- **Job scheduling in parallel** : The scheduler used to schedule each pipeline in parallel, but that would result in problems like one job taking a long time to schedule would end up blocking the other jobs from scheduling. Along with this new algorithm, we switched the scheduler to now schedule jobs in parallel.

- **Max DB CPU** : The DB CPU is maxed but might just be the reality of running 1000 jobs. We have optimized the queries a lot already, and there don't really appear to be any bottlenecks remaining, so at this point it's just a bunch of inexpensive queries.

There might be a few things I'm missing so I'll update this as soon as I remember 😄

**Comment by jchesterpivotal** [comment]
A sidenote about the ongoing work. Using a "[hypothetical indexes](https://github.com/HypoPG/hypopg)" tool can help examine the impact index changes would have on a query plan, without having to actually create the index.

**Comment by kcmannem** [comment]
@clarafu thanks for summarizing this! really cool stuff you guys did.

**Comment by jchesterpivotal** [comment]
>  So as a result, we added a limit to the number of rows for the queries that ask for builds within a job and will continue to query again for the next set of rows whenever we have finished trying out the first set of builds returned. To clarify with an example, we return the first 100 builds and we then use those 100 builds for the algorithm and if we still haven't found a proper candidate with those 100 builds, we will then query for the next 100 builds after that and will continue with this pattern until we either find a candidate or reach the end of the builds.

Do you mean `LIMIT` and `OFFSET`? If so, there are two risks:

1. The database will still fetch everything up to `OFFSET`+`LIMIT` and discard the rows before `OFFSET`. So this query will grow steadily slower as you paginate.
1. The results can change between each query execution, meaning you can either skip or double-count rows.

The usual tool for this is to use a `CURSOR`, which will require dipping into a bit of pl/pgsql.

**Comment by clarafu** [comment]
@jchesterpivotal I didn't know about hypothetical indexes, thats super cool thanks! We used `LIMIT` and a cursor with the `ID` of the last row that we fetched from the last set, we didn't end up using `OFFSET`.

**Comment by jchesterpivotal** [comment]
Do you mean a cursor as in `CURSOR` / `FETCH`? Or more like `SELECT foo FROM bar WHERE id > 200 LIMIT 100`?

**Comment by clarafu** [comment]
We did more of the `SELECT` that you described, sorry I should've clarified that I meant cursor as a general concept and not the postgres `CURSOR`!

**Comment by clarafu** [comment]
Going off my last comment about fixing the tenth job scheduling time (https://github.com/concourse/concourse/issues/3602#issuecomment-505947262), the metrics show that the tenth job was scheduling approx the same amount of time with the other jobs but after a while, it went back to scheduling a lot longer (approx 10 s compared to 1 s).

The last thing that we wanted to try to optimize to make the tenth job schedule as fast as the others was to order the passed jobs within the algorithm to be dependent on the last completed build ID, with the job with the oldest build ID be ordered first. The theory was that if there are two passed jobs, the job that was the last to run has a possibility of not have run with a new version of the input and we want to first pin the input to a version that we know has run with all the passed jobs before. After deploying this change, only after a few hours did we see the tenth job schedule faster.

<img width="476" alt="Screen Shot 2019-07-05 at 4 52 50 PM" src="https://user-images.githubusercontent.com/19290703/60744762-5e969f00-9f45-11e9-8ed8-d52adf491cec.png">

In the metric above, the purple line that suddenly drops in the middle happened a few hours after our deploy with this change. Even though for now the metrics seem to show that the all the jobs now schedule quickly, optimizing by oldest build ID does not ensure that we will always order the jobs properly to make sure that the algorithm does not need to walk over all the builds of a job. We should try to think of a more solid way to order the passed jobs to make sure we first pin to a version that all the jobs have run with. 

Another thing to note is that the last completed build ID that we use to order the passed jobs also include builds that have been aborted, failed, etc. We should actually only take into account successful builds in order to have this ordering work the way it is intended.

**Comment by clarafu** [comment]
The last state that we had the algorithm at was to order the passed jobs by their latest completed build ID, which made the tenth job faster but after a while it started to slow down again. This also isn't a great solution because it depends on the ordering of the passed jobs to make the algorithm more efficient, plus the latest completed build ID might not always be a great indication of which upstream job has not run with a later version of an input.

We decided to remove this ordering and try out a completely different approach to the algorithm for passed constraints. The theory of constraining the returned builds of passed jobs by all the versions that are within our candidates seems like a great idea, because we wouldn't waste time going through builds that we know are going to fail when it hits other inputs like it does now where we only constrain passed job builds returned by a single version candidate. That theory seemed like a good idea but when we actually implemented it a few weeks ago, the overhead of the complexity of the query made it even slower than it was when we constrained to a single version. We decided to come back to this theory but this time try using a jsonb column in the 'successful build outputs' table to store all the build inputs and output versions. This is because we can create an index on a key in the jsonb column and we can query for a subset of the inputs/outputs stored in that column. We deployed using this new jsonb column and querying for passed job builds that match all the version candidates that we have determined so far and the metrics are looking good. After a week, the scheduling time for most of the jobs is around 500-1000 ms which is faster than it has ever been. The scheduling time of the tenth job is now within the same range as all the other jobs.

<img width="488" alt="Screen Shot 2019-07-22 at 10 00 12 PM" src="https://user-images.githubusercontent.com/19290703/61677066-2b396b80-accc-11e9-9ac3-239e2b819e93.png">

The only problem we have been seeing with this new change is this weird sawtooth pattern with the scheduling time that also lines up with the containers on workers being maxed out. 

<img width="480" alt="Screen Shot 2019-07-22 at 10 00 21 PM" src="https://user-images.githubusercontent.com/19290703/61677074-32f91000-accc-11e9-8498-c71c0b2b2ada.png">

<img width="473" alt="Screen Shot 2019-07-22 at 10 00 30 PM" src="https://user-images.githubusercontent.com/19290703/61677076-34c2d380-accc-11e9-94e9-c0319688a307.png">

We think it might be something to do with postgres refreshing the indexes, and possibly the jsonb index is so large or heavy that it causes a lot of slowness which is making the db not able to gc quick enough? I'm really unsure what it might be, I investigated a bit on possibilities such as the autovacuum being the cause, might it seems like it might not be that because the new table "successful_build_outputs" that we added the jsonb column to does not update or delete any rows, so there shouldn't be any dead tuples for it to clean.

**Comment by clarafu** [comment]
After doing more investigation, we narrowed it down to not being dead tuples being cleaned up with autovacuum and probably isn't checkpoints because checkpoints should run more often (5 minutes). We were thinking it might have something to do with the index for the jsonb column, since it must be a really big index and constantly being updated with new rows being added to the table. 

This lead me to find this one article that was literally a life saver (if you want to read it it is here https://www.pixlee.com/blog/hunting-down-phantom-write-spikes-in-rds-postgres/). They basically ran into the same problem as me and going down the same path of checking if it was the checkpoints, autovacuum, etc that is causing this and figuring out it was none of them because it was actually caused by the GIN index. The GIN index is really great for speeding up reads but when there are inserts into the table that has the GIN index, it actually does not update the index on the spot but rather leaves it to later and does a batch insert into the index in order to speed up the inserts. This actually caused our db to end up doing huge batch inserts and slowing everything down drastically whenever it happened because of the large amount of changes that batch insert needed to do due the large amount of inserted rows.

There are a couple of things that can be done to fix this issue, you can either make the auto-vacuum run more often or disable the feature that does batch updating the index rather than updating the index everytime we insert. We tried disabling the batch feature first to see the affect and so far it has turned out to be great! The scheduling time no longer sawtooths and the times dropped down to 100-300 ms per job vs before it was 500-1000 ms. The image below shows the difference between before and after (separated by the black vertical line) we added the disabling of the batch feature.

<img width="706" alt="Screen Shot 2019-07-23 at 3 27 33 PM" src="https://user-images.githubusercontent.com/19290703/61741306-916ece80-ad5e-11e9-9e74-f49c144a5285.png">

As a little discovery on why we were seeing a sawtooth looking metrics on our scheduling time, we think that it was caused by the fact that the GIN index defaults to doing the batch updating the index. The way it works is that it will add newly inserted rows into a list of pending entries which is unsorted and whenever a SELECT happens on that table and it tries to use the GIN index, it will first scan the unsorted pending list and then will scan the index. As a result, the larger the unsorted pending list is, the longer it will take to scan.

Also the db connections have gone down, as shown in the image below where the black vertical line is when the change to the index was added.

<img width="708" alt="Screen Shot 2019-07-23 at 3 27 43 PM" src="https://user-images.githubusercontent.com/19290703/61741295-8caa1a80-ad5e-11e9-9b88-95f595d065d8.png">

The number of builds created (we think that's the metric at least) is also climbing to approx 43k per hour compared to before where it averaged 35k per hour. These metrics are showing huge improvements especially if you factor in the amount of builds that this deployment currently has which is about 10 million builds in total. 😄

**Comment by kcmannem** [comment]
🐏 optimizer, you should just write your own dB at this point

**Comment by jchesterpivotal** [comment]
If and when we get to using partitioned tables, [the v11 docs](https://www.postgresql.org/docs/11/ddl-partitioning.html#DDL-PARTITIONING-DECLARATIVE-EXAMPLE) say that you can apply an index which itself be partitioned. I expect that most build scheduling is looking at recent records, so partitioning over time should further reduce the search cost.

**Comment by clarafu** [comment]
We added metrics to each of the garbage collection component (resource caches, builds, containers, volumes, etc) in order to see how long each takes to fully complete and how the metrics look when the autovacuum starts. The graph below shows the time it takes each gc component to run and the vertical line is approximately where the autovacuum on the builds table started.

<img width="720" alt="Screen Shot 2019-07-25 at 1 42 06 PM" src="https://user-images.githubusercontent.com/19290703/61896071-264e0500-aee2-11e9-8ec4-7f3551272fd6.png">

You can see that all the lines slowly go up, meaning that they are all taking longer to run during the autovacuum. The autovacuum on the builds table ended up taking around 1300 seconds to run and once it ended, the time it took all the gc components to run went back to normal. (You can see a sudden drop back down on the graph) We presume that when an autovacuum runs for a big table that has many indexes (in this case the builds table) it slows down all other queries to the db possibly because the autovacuum takes up a lot of the db CPU? Taking into consideration that the garbage collector runs each component in series and the container and volume gc is the last to run, it means that it has to slowly finish each component before getting to the container gc which might be the cause of the workers periodically hitting max containers.

The solution that we tried was to parallelize each gc component so that they run on their own intervals and have their own dedicated connection pools. This way they will never compete with each other and it doesn't have to wait for all the other gc components to finish before running the container gc. After we deployed this change and observed when an autovacuum kicked off for a large table, we saw that the container count for the workers did not spike at all.

Now that we fixed the max container issue, we also want to look into having queries not be affected by autovacuum runs. Right now, we are still seeing spikes in many of our metrics.

<img width="706" alt="Screen Shot 2019-07-25 at 1 57 44 PM" src="https://user-images.githubusercontent.com/19290703/61897095-54ccdf80-aee4-11e9-8efc-12f542bda9e0.png">
<img width="709" alt="Screen Shot 2019-07-25 at 1 57 52 PM" src="https://user-images.githubusercontent.com/19290703/61897137-6c0bcd00-aee4-11e9-8a28-9b1e2f34ec47.png">
<img width="711" alt="Screen Shot 2019-07-25 at 1 58 19 PM" src="https://user-images.githubusercontent.com/19290703/61897105-57c7d000-aee4-11e9-8022-b847c6c3244a.png">
<img width="712" alt="Screen Shot 2019-07-25 at 1 58 14 PM" src="https://user-images.githubusercontent.com/19290703/61897106-57c7d000-aee4-11e9-875a-945828b384d9.png">
<img width="705" alt="Screen Shot 2019-07-25 at 1 58 02 PM" src="https://user-images.githubusercontent.com/19290703/61897107-58606680-aee4-11e9-978e-fb73a1b97352.png">
<img width="702" alt="Screen Shot 2019-07-25 at 1 58 26 PM" src="https://user-images.githubusercontent.com/19290703/61897104-57c7d000-aee4-11e9-87ff-cee178396e01.png">

Each of these graphs show the metrics at the same time range, and you can see that all the graphs have two distinctive spikes except for the worker container count. We might want to look into possible indexes that we can remove or tune from large tables in order to speed up the autovacuums or some postgres configurations that we can adjust to allow for autovacuums to not affect the db that much.

**Comment by clarafu** [comment]
Something to keep an eye on is the fact that we don't order the versions saved into the `successful_build_outputs` table if it is the same resource within the same build. This will result in a user possibly seeing different versions being used as a passed constraint for their upstream jobs, rather than if we always ordered it from latest to oldest versions (but this will introduce extra joining to the resource versions table and will add a lot of overhead to the queries).

We can see if anybody complains. :D

**Comment by jchesterpivotal** [comment]
Could you elaborate on the last one? On its face I think folks would be surprised to see reordering.

**Comment by clarafu** [comment]
@jchesterpivotal It would have to be a situation where someone has a job that has two inputs that are the same resource but different versions. For example,

```
jobs:
- name: example
   plan:
   - get: input-1
      resource: resource-1
   - get: input-2
      resource: resource-1
      version: {some: ref}
```

If this job became a passed constraint for `resource-1` in an upstream job, either the latest version or the pinned version could be used as the input version for the upstream job.

@vito maybe u can have a say in this.

**Comment by vito** [comment]
It feels like a bit of an edge case, and one where I'm not super convinced that picking the newest version is technically the 'right thing', either. Just imagining a scenario where someone is pinning `input-2` to an older version than `input-1` until one day when they pin to a *newer* version than `input-1`.
