### ISSUE TITLE
Run Topgun on PKS

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#3643]
[@cirocosta  here]

Hey,

<br />

In March, Josh Ghiloni wrote a nice [blog post][blog-post] highlighting how to
run Concourse on [PKS][pks], showing some of the details (`StorageClasses`) and
other minutia.

As part of getting Concourse ready for Kubernetes installations would require
us being through in terms of installation on PKS as well (e.g., see
http://greenplum-kubernetes.docs.pivotal.io/1-2/installing.html and more PKS specific https://docs.pivotal.io/runtimes/pks/1-4/installing.html), it'd be good
to be prepared for it.

Having our current Topgun tests running against a PKS-deployed environment
would then teach us what are the basic needs to get Concourse up and running on
such environment, and forcing us to see where things differ.

*note: This GitHub issue might eventually lead to other stories, which is
perfectly fine (and even deriseable).*

**Acceptance Criteria**

- [x] document the steps necessary to get the environment up
- [x] list limitations and issues
- [ ] have a subset (or all) topgun tests running

Thanks!

[blog-post]: https://medium.com/concourse-ci/installing-concourse-5-0-on-pivotal-container-service-using-helm-9f20e4e1b8bf
[pks]: https://docs.pivotal.io/runtimes/pks/1-4/index.html

**Comment by taylorsilva** [comment]
# Issue Status
###### Keep editing this comment with the current status of the issue

***

### Task List

- [ ] Get a VSphere environment (currently waiting for it to be deployed by toolsmiths)
  - [ ] Remove the PAS tile
  - [ ] Install PKS on it: https://docs.pivotal.io/runtimes/pks/1-4/installing.html
  - [ ] Install Concourse on PKS ([blog post for help](https://medium.com/concourse-ci/installing-concourse-5-0-on-pivotal-container-service-using-helm-9f20e4e1b8bf))

**Comment by taylorsilva** [comment]
### Notes from Installing Enterprise PKS on vSphere (without NSX-T)

**Comment by taylorsilva** [comment]
### Running Topgun/k8s on PKS

Doing a naive first run:
```bash
env CHARTS_DIR=/Users/pivotal/workspace/charts CONCOURSE_IMAGE_NAME=concourse/concourse CONCOURSE_IMAGE_TAG=5.2 ginkgo -nodes=4 .
``` 
and got
```
Error: release topgun-pi-974137-1 failed: timed out waiting for the condition
```
from each test.

**Comment by cirocosta** [comment]
Thanks for the very detailed report, @taylorsilva !

Regarding `storageClass`es: it seems that as an administrator of the k8s
cluster, you're able to set what the default `storageClass` is:
https://kubernetes.io/docs/concepts/storage/storage-classes/#the-storageclass-resource.

Regarding `nodeSelector`, perhaps we could conditionally run a given table or
set of entries from the table based on something that identifies that we're
targetting either GKE, PKS on vSphere, AWS etc 🤔 

wdyt?

**Comment by cirocosta** [comment]
Hey,

As we now have more specific issues regarding the point that is missing being addressed (see https://github.com/concourse/concourse/issues/4098), I'll close this issue so we can keep the conversation more specific.

Thank you!
