### ISSUE TITLE
Test per-pipeline credential lookup using Kubernetes credential management

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#3808]
Hey,

@mhuangpivotal  and I noticed that the k8s credential management tests are missing one use case that we support: having pipeline-scoped secrets.

https://github.com/concourse/concourse/blob/0ecb0381931e47ed9ac77091bdf0a92c21c2113b/topgun/k8s/kubernetes_creds_mgmt_test.go#L73

Having this test is important as people are probably already making use of such feature as it's already documented here: https://github.com/helm/charts/tree/c4107a5b7e32dd7040e64f219051eb9a2c7ca743/stable/concourse#kubernetes-secrets

Thanks!

**Comment by taylorsilva** [comment]
# Issue Status
###### Keep editing this comment with the current status of the issue

***

### Task List

- [ ] Manually test that pipeline-scoped secrets work as expected
- [ ] Write tests to cover pipeline-scoped secrets
- [ ] Create a PR and wait for it to be merged
