### ISSUE TITLE
[Spike] Discover the step interface for the following steps;

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#3998]
## Resource
- Check
- Get
- Put

## Generic Script
- Task

As a result of this spike, we should be able to achieve the step execution logic with Kubernetes as a replacement for Garden and Baggageclaim.

### Findings so far

* Putting a "seam" in as a NewK8sWorker is too late, because by that time, a lot of assumptions about Garden have already been baked in
* Putting the seam in the exec package by splitting off a new K8sTaskStep is working a little better, and we're also able to eliminate some unnecessary configuration from the task input, such as container scheduling strategy and worker pools

# v1

#### Hello World
- [x] Execute command on container using the task's image ref, command, and args (echo "hello world")
- [x] Report status of the result so Concourse goes green/red on success/fail
- [x] Get logs from pod to show up in Concourse

#### Schedule task that pulls an input
- [ ] Get a pod to pull a resource artifact from a blobstore

#### Schedule task that produces an output
- [ ] Upload something to the blobstore

# v2

### Task
- [ ] Prove that step B can pick up an output from step A in the same job
- [ ] Pass inputs to k8s
- [ ] Configurable secrets
- [ ] Outputs
- [ ] Work out a way to manage .kube/config and keep it working for local dev?? Or at least document how to run locally.

### Get
- [ ] Execute get `in` script with resource's image ref
- [ ] Upload output to blobstore

**Comment by deniseyu** [comment]
@ddadlani @kcmannem @xtreme-sameer-vohra @nader-ziada  we pushed some WIP code to this branch: https://github.com/concourse/concourse/tree/spike-02-3998

**Comment by deniseyu** [comment]
## End of week 1 of spiking

After spending one week hacking around with plugging Kubernetes in as the runtime, we've made the following observations:

- Splitting out the Kubernetes-specific behaviour at the `step` level is probably the correct level of abstraction
- A Kubernetes Pod is probably the correct unit of execution for a task
- It is fairly straightforward to fill in a Pod ContainerSpec using existing values we get from a Concourse buildplan, with existing structs. Yay!
- By using a blobstore within the IaaS to persist task outputs, inputs, and resources, we can simplify volume-to-volume streaming of resources through the ATC, which may also enable us to simplify our database schema. This means that a "Kubernetes runtime" will not need baggageclaim. We will need to assess performance impacts of this model when we have more production-ready code!

### Things to figure out later

- Scheduling steps that run in sequence. We hacked this with InitContainers for the spike, but the real implementation will have to address how to schedule container B when container A is finished successfully. Kubernetes by default schedules all non-init containers within the same pod to start in parallel.
- Authentication: We manually set up service accounts and wrote secrets into the Kubernetes secret store. We will need to find a cleaner and less manual way to do this, and in the specific case of GKS clusters (possibly AKS/EKS, but we haven't checked) we need to check that the correct set of credentials are active, because a default set of cluster admin credentials is automagically mounted on every container
- Sidecar processes for containers: We don't have a way to keep containers alive right now, as they are 100% scheduled by pods. We will need to find a way to keep pods that ran failed steps, considering that Kubernetes can garbage-collect pods.
- A better way to communicate with the blobstore. We hacked around with the `gsutil` CLI but may want to look at [Stow](https://github.com/graymeta/stow) and other libraries
- Log streaming and websockets stuff that we didn't bother with for the spike

cc @ddadlani @kcmannem @xtreme-sameer-vohra @nader-ziada @vito

**Comment by vito** [comment]
@deniseyu Awesome!

Would [`go-cloud`](https://github.com/google/go-cloud) be another appropriate for the blobstore communication bit? Haven't looked at it much myself but there was a lot of noise about it a while back.

**Comment by kcmannem** [comment]
We've divided up the comment Denise made into separate stories and are going to continue progress within those for updates.
