### ISSUE TITLE
[Epic] Implement Super Admin Privilege

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#4192]
## Description

Take the current `Admin` privilege and give it all permissions. All checkboxes on our docs permissions page (https://concourse-ci.org/user-roles.html) should be checked-off for the Admin "role".

WIP Branch: [`super-admin-user`][branch]

## Stories
- [ ] [atc/api] Increase scope of Admin privilege #4193
- [ ] [Web] Confirm UI functionality for Admin user #4194
- [ ] [fly] Confirm functionality for Admin user #4195
- [ ] [fly] Add `--team-name` for all Fly commands #4196
- [ ] [docs] Update docs with new admin privilege #4197 

[branch]: https://github.com/concourse/concourse/tree/super-admin-user

**Comment by taylorsilva** [comment]
Follow along here: https://github.com/concourse/concourse/projects/42
