### ISSUE TITLE
[atc/api] Increase scope of Admin privilege

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#4193]
Epic #4192 
### Description/Context

We want to update the API handlers that care about what teams a user belongs to. The accessor.IsAuthorized() should always return true if the user is Admin. Any handlers that care about the teams that a user is part of should check if the user is an admin and instead perform their action for/with all teams in mind.

Tip: search for usages of `acc.TeamNames()`, those are the handlers you likely need to change

### Task List

- Investigate and **potentially modify** the following methods to behave properly for an admin user:
  - [x] Modify ListAllPipelines
  - [x] Modify ListAllJobs
  - [x] Modify ListBuilds
  - [x] Modify ListAllResources
  - [x] Modify ListWorkers

### Acceptance Criteria
- [x] No handler should return unauthorized if a user is `Admin`
- [x] Web UI displays all pipelines when a user is `Admin`
- [ ] ~~Fly CLI should be able to log into any team and perform any action~~
  - will work on this in the Fly CLI story

**Comment by taylorsilva** [comment]
# Issue Status

- Created a branch [`super-admin-user`][branch] with some wip code
- Our current implementation idea is that each API handler will have to do something like what we find in the `SetTeam()` function:

https://github.com/concourse/concourse/blob/5824dfd73cba6a3d9a256a2317f45a92478aa2b4/atc/api/teamserver/set.go#L55-L66

- For testing, when trying to add to the existing test suite it's really easy to start faking everything by accident. We'll need to be careful about how we test Admin behaviour

Next Step: Focus on testing and implementing a single API handler. We started with the `ListAllPipeline()` handler. We think it'll be good to focus on implementing just this one handler and seeing what we learn from it.

[branch]: https://github.com/concourse/concourse/tree/super-admin-user

**Comment by taylorsilva** [comment]
We used this bash script (placed in the root of the concourse repo) after doing `docker-compose up --build -d` to set-up a team and private pipeline. Helped with quickly testing how the web ui is behaving.

```bash
#!/bin/bash

fly -t local login -u test -p test -n main
fly -t local set-team -n team1 --local-user=guest
fly -t local sp -p hello -c examples/hello-world-every-minute.yml

fly -t local login -u guest -p guest -n team1
fly -t local sp -p hello-team1 -c examples/hello-world-every-minute.yml
```
