### ISSUE TITLE
[fly] Add `--team-name` for all Fly commands

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#4196]
Epic #4192 

Currently the only way for users to interact with multiple teams with Fly is to create multiple targets.
This story will leave this workflow possible (users may have scripts that switch targets based on teams)
and will enable a new "single target, many teams" workflow.

If a user wants to change their default team, they can login with the same target into a different team.

Another thing to note is that we already have the `--team-name` and `-n` flags for some commands. We should continue to use both of these flags everywhere.

### Single-team scoped Commands
For single-team scoped commands the following should be possible for each command. This ensures a user's existing script/workflow will still work.

```bash
# use default team
fly -t ci <command> <command-options>
# use another team
fly -t ci <command> <command-options> --team-name team3
```

- [ ] abort-build
- [x] hijack
- [ ] resources
- [ ] check-resource-type
- [ ] check-resource
- [ ] resource-versions
- [ ] watch
- [ ] checklist
- [ ] clear-task-cache
- [ ] execute
- [ ] expose-pipeline
- [ ] destroy-pipeline
- [ ] get-pipeline
- [ ] set-pipeline
- [ ] hide-pipeline
- [ ] pause-pipeline
- [ ] unpause-pipeline
- [ ] rename-pipeline
- [ ] order-pipelines
- [x] jobs
- [x] trigger-job
- [x] pause-job
- [x] unpause-job

PR: https://github.com/concourse/concourse/pull/4406
**PR is ready for review and can be merged**

Remaining commands should be submitted as new PR's. One PR per command to make it easier for others to review.

### Multi-team scoped commands
For these commands, they currently behave like the previous single-team commands. They hit a `/api/v1/teams/...` endpoint and return the result. We should change the behaviour of the `--team-name` to accept **one or more** team names by declaring the flag multiple times.
We can also implement a `--all-teams` flag to just get data for all teams in Concourse.

The following should be possible for the below commands:
```bash
# use default team
fly -t ci <command> <command-options>
# return data for specified team
fly -t ci <command> <command-options> --team-name team1
# return data for all teams given
fly -t ci <command> <command-options> --team-name team1 --team-name team2 -n team3
# return data for all teams in Concourse
fly -t ci <command> <command-options> --all-teams
```

- [x] containers
- [ ] volumes
- [ ] pipelines
- [x] builds (`--all` has been implemented, enhancement for `--team`)

Some of these commands already take a long time, `fly volumes` takes 9s to return for the main team on ci.concourse-ci.org. It may be more efficient to create a new API endpoint that returns this data for a subset/all teams.

PR: https://github.com/concourse/concourse/pull/4324 - For `containers` only

Create new PR's for `volumes`, and `pipelines`. Smaller PR's are easier for others to review.

### N/A
These commands already focus on one team and only work for owners of the main team (Admins). They all have the --team-name flag already.
You don't need to be logged into the main team to run these commands either, they Just Work(TM). These commands should not be changed.
- set-team
- destroy-team
- rename-team

## Acceptance Criteria
- All single-team and multi-team commands take an **optional** `--team-name` and `-n` flag and execute their API calls under that team
- Multi-team commands take these **optional** flags:
  - `--team-name` flag which takes in a list of team names and returns data for only those teams
  - `--all-teams` flag, boolean, that will return the relevant data for all teams
- Multi-team commands should display some kind of waiting text, like "fetching data..." before they start hitting the Concourse API because it can take a long time to return this data for even one team.

**Comment by kallisti5** [comment]
omg yes.  We have a team per thing (continious builds, release builds, etc)  i end up creating like 6 targets all for the same server and having to log into each.. it's complex.

**Comment by pivotal-bin-ju** [comment]
**Dev Note**

@YoussB And I :

- Refactored the source code and test case for subcommand `containers`
  - removed `IsSuperAdmin`, `AsTeam` from interface `target`
  - did not verify team name in fly any more
  - add `--all-teams` parameter
  - refactored the test case with customizable handler list due to viable api calls from different test cases.

**Next Step**
- Make a list of `fly` commands that is applicable to `--team`.
- Think about the test coverage of `containers`. 
  - At least we need to cover `super admin` due to `--all-team` should be able to list all the containers of all teams in this concourse cluster.
  - Common user (non super admin) should be able to list the containers (with `--team`)in the team list.
- Make this pattern applicable to the other subcommands.

**Comment by zoetian** [comment]
*Dev Note*

@pivotal-bin-ju and I 

- we divided all the previous `team-scoped` commands into 2 types: 
    i.e. scoped by multiple teams or single team (pipeline/ job/ build/ resource level)
- refactored the `suite_test.go` for multiple teams scope commands (`containers`, `volumes`)
- added tests for these commands

*Next Step:*
- we left the `pipelines` changes half-done (see the last commit), so this still need to have proper test cases
- continue working on the rest of the `single-team-scoped` command lines

**Comment by pivotal-bin-ju** [comment]
*Dev Note*
@zoetian and I:
- finished subcommand `pipelines`. and fixed the minor ui bug for displaying `team name` of the command `pipelines` if the parameter `--team` is applied.
- asked the opinion on the team scope cli command line format on discuss (https://discuss.concourse-ci.org/t/feedbacks-wanted-fly-cli-team-scope-command-format/1689/1).
- changed the parameter `--teams` to `--team` according to the convention.

**Comment by taylorsilva** [comment]
I'm thinking of re-writing this story to make the acceptance criteria clearer. Right now we're trying to code a solution and figure out what makes sense for the users (operators and devs). We need to figure out what makes sense for our two main user groups first and then we can continue coding this feature.

**Comment by taylorsilva** [comment]
For transparency, here's the original text of this issue

---

Epic #4192 

### Description
To make the Admin privilege easier to use, so they don't have to login and logout to switch teams, each command should support an optional `-n` or `--team` (the existing team parameter short-name) to override the current default team.

### Acceptance Criteria
- [ ] Any team-scoped commands should accept a `-n` or `--team` parameter

Acc. to the previous issue (https://github.com/concourse/concourse/issues/4195)
All the team-scoped commands are:

[1] multiple teams scoped *PR* (#4324)
- [x] execute
- [x] containers
- [x] volumes
- [x] set-team
- [x] destroy-team
- [x] rename-team
- [x] pipelines

[2] single team scoped (https://github.com/concourse/concourse/pull/4406)
- [ ] abort-build
- [ ] hijack
- [x] resources
- [ ] check-resource-type
- [ ] check-resource
- [ ] resource-versions
- [ ] watch
- [ ] checklist
- [ ] clear-task-cache
- [ ] expose-pipeline
- [ ] destroy-pipeline
- [ ] get-pipeline
- [ ] set-pipeline
- [ ] hide-pipeline
- [ ] pause-pipeline
- [ ] unpause-pipeline
- [ ] rename-pipeline
- [ ] order-pipelines
- [x] jobs
- [ ] trigger-job
- [ ] pause-job
- [ ] unpause-job


### Notes

- the `build` command already has a `--team, -n` flag. May be wise to re-use this across all other commands

**Comment by pivotal-bin-ju** [comment]
Please see the discuss from [here]( https://discuss.concourse-ci.org/t/feedbacks-wanted-fly-cli-team-scope-command-format/1689/10?u=pivotal-bin-ju)

**Comment by zoetian** [comment]
*Dev Note*

Up till today, we created PR1 #4324 and PR2 #4406 for the first few commands.
However, there are still tons of refactor and test cases changes going on. Below is a self-checklist in case I miss any important details:

- [ ] finish refactor on both PR1 & PR2 on fully using `loginATCServer` in `fly/integration/suite_test.go` to reduce the duplicates among the codebase
- [ ] double check the possibility to get rid of the `atcServer` in PR1
- [ ] apply `pagination` on both PR's (user can pass `-c, count` to determine the number of containers/ volumes/ pipelines/ jobs they want to display. Default is `50`)

**Comment by zoetian** [comment]
After some discussion, we decided to 

- create global endpoints for "plural commands" (i.e. containers, pipelines)
- no need to use `count`
- use the current team as default for `builds` command 
- specify which team we want to display

**Comment by pivotal-bin-ju** [comment]
**Dev Note**

We made some code changes to db queries in `atc/db/container_repository.go` to get containers by users' teams. 

We used this sql statement to test locally for selecting containers by team name:

```
(select distinct c.id, c.handle, c.worker_name, c.hijacked, c.discontinued, c.state, c.team_id, w.team_id from containers c
 join workers w ON c.worker_name = w.name
 join resource_config_check_sessions rccs ON rccs.id = c.resource_config_check_session_id
 join resources r ON r.resource_config_id = rccs.resource_config_id
 join pipelines p ON p.id = r.pipeline_id
 join teams t ON t.id = p.team_id
where p.team_id=1 and(w.team_id=1 or w.team_id is null)
) union
(select distinct c.id, c.handle, c.worker_name, c.hijacked, c.discontinued, c.state, c.team_id, w.team_id from containers c
 join workers w ON c.worker_name = w.name
 join resource_config_check_sessions rccs ON rccs.id = c.resource_config_check_session_id
 join resource_types rt ON rt.resource_config_id = rccs.resource_config_id
 join pipelines p ON p.id = rt.pipeline_id
 join teams t ON t.id = p.team_id
where p.team_id=1 and(w.team_id=1 or w.team_id is null)
) union (
select c.id, c.handle, c.worker_name, c.hijacked, c.discontinued, c.state, c.team_id, 20 from containers c 
where c.team_id =1
);
```

**Next Step**
- figure out how to use the above sql to get all containers cross teams
- modify the interface for both `atc/db/container.go` and `atc/container.go` to use `teamName` for displaying from db to in api/present
- finish the `AllContainers` and `VisibleContainers` in `atc/db/container_repository.go`

cc @zoetian

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**
@taylorsilva  and I:
- refactored the sql statements and related functions for `AllContainers` and `VisibleContainers`.
- on presentation layer, `team_name` is included in json response in the global `/api/v1/containers` api now.

**TODO**
- test coverage for `AllContainers` and `VisibleContainers`
- `fly` cli is going to call `api/v1/containers` when `--all` parameter is given for the command `containers`.
- `fly` cli will display the column `team_name` when calling the global `containers` api. 
- apply the same pattern to `volumes`.
- need to have a look at the command `pipelines`(this command shows private pipelines in the current team and public pipelines in other teams).

**Comment by pivotal-bin-ju** [comment]
**DEV NOTE**
@deadlysyn and I:
- implemented `fly` command `ListAllContainers` against the api change `/api/v1/containers`.
- add a display column `team` for the command `fly containers`

**TODO**
- parameter handling of `--all, `teams` for  the fly command `containers`. In  last commit, those parameters are not handled.
- test cases  for `AllContainers` and `VisibleContainers`
- the column `team` only be displayed for `fly` command `containers` when multi-team is involved. (`--all`, `--teams`)
- apply the same pattern to `volumes`.
- need to have a look at the command `pipelines`(this command shows private pipelines in the current team and public pipelines in other teams).

**Comment by zoetian** [comment]
**DEV NOTE**

For the first PR #4324 

- [ ] fixes the `atc/api/container_test.go` to pass unit test
- [ ] discuss the backward compatibility with Lindsay on whether we should use `--team` or `--team-name` (right now `fly -t $TARGET builds` is using `--team`, whereas command `set-team` and `get-team` is using `--team-name`) 
- [ ] continue the work for `volumes` and `builds`

**Comment by taylorsilva** [comment]
### Dev Note

Spent a bunch of time cleaning up the two feature branches for this issue. You can find both feature branches in the two PR's listed in the first comment of this issue.

Both PR's had their commits cleaned up. The PR for #4406 is ready to be merged in. Moving forward we should make one PR for each fly command that we implement.

For the second PR (#4324) it's only going to be about the new `api/v1/containers` endpoint and implementation to `fly`. The `volumes` and `pipelines` commands/endpoints will be implemented and submitted in other branches/PR's. Makes reviewing easier for others.
