### ISSUE TITLE
epic: implement Garden API for containerd

### ISSUE THREAD

**Issue by deniseyu** [concourse/concourse#4783]
As an incremental step towards using `containerd` natively for Concourse workers,
we're going to implent a Garden backend that's backed by `containerd`.

On the worker side, the backend will be shipped alongside `gdn`, with the switch
between one and the other possible through the use of a feature flag:
`--garden-use-containerd`.

- [x] Backend
  - [x] `Start()`: https://github.com/concourse/concourse/pull/4752
  - [x] `Stop()`: https://github.com/concourse/concourse/pull/4779
  - [x] `Ping()`: https://github.com/concourse/concourse/pull/4752
  - [x] `Capacity()`: noop
  - [x] `Create()`: https://github.com/concourse/concourse/pull/4779
  - [x] `Destroy(handle)`: 
    - https://github.com/concourse/concourse/pull/4784
    - https://github.com/concourse/concourse/pull/4881
  - [x] `Containers()`: https://github.com/concourse/concourse/pull/4779
  - [x] `BulkInfo()`: noop
  - [x] `BulkMetrics()`: noop
  - [x] `Lookup()`
    - https://github.com/concourse/concourse/pull/4784
    - https://github.com/concourse/concourse/pull/4881
<br />

- [ ] Container
  - [x] `Handle()`: #4913
  - [x] `Stop()`: #5114
  - [x] `Info()`: #5114
  - [x] `Run()`: #5114
  - [x] `Attach()`: #5114
  - [x] `Property`-related: #5114
  - [x] `Lookup`: #5114
  - [ ] `SetGraceTime()`:
  - no-ops
    - [x] `CurrentLimits()` (Bandwidth, CPU, Disk)?
    - [x] `Limit*()` (Bandwidth, CPU, Disk)?
    - [x] `StreamIn()`
    - [x] `StreamOut()`
    - [x] `Metrics()`

<br />

- [x] Process
  - [x] `ID()`: #5114
  - [x] `Wait()`: #5114
  - [x] `SetTTY()`: #5114
  - [x] `Signal()`: #5114 

<br />

References:

* [Garden Container interface](https://github.com/cloudfoundry/garden/blob/master/container.go)
* [Houdini implementation](https://github.com/vito/houdini/blob/master/container.go)
* [Alex's spike code from before](https://github.com/concourse/concourse/blob/containerd-impl/gcontainerd/container.go)

**Comment by deniseyu** [comment]
We are going to defer the bulk reporting functionality because those all depend on a `Container` to be implemented and able to report its own stats first. For later reference, here is Guardian's implementation of these bulk methods: https://github.com/cloudfoundry/guardian/blob/6b021168907b2f2ae25cf54acae8b454b430332f/gardener/container.go

**Comment by deniseyu** [comment]
Chatted with @xtreme-sameer-vohra about whether we should do any cleanup when `Stop()`ing -- it seems like in the current world, we don't do anything when terminating the client connection to the Garden server. We're guessing now (will verify later) that this is because this normally happens as part of the `land-worker` or `retire-worker` flow, and later on in the lifecycle of that worker, all machine resources will be destroyed by the daemon spinning down and/or the worker VM (or k8s deployment) going away. Doing resource cleanup as part of the backend's `Stop()` implementation would be surprising. So we'll just leave it as is, and revisit this when we're ready to implement garbage collection later.

**Comment by cirocosta** [comment]
Hey, 

I just updated the issue to make the title and body more consistent with the intent of capturing all of the work on implementing the containerd backend for the garden api.

thx!
