### ISSUE TITLE
release v5.7.2

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4838]
Just opening this to keep tabs on the upcoming v5.7.2 release and communicate any updates on it externally.

Included:

* #4804
* #4808
* #4817 
* [`registry-image` resource v0.8.2](https://github.com/concourse/registry-image-resource/releases/tag/v0.8.2), which fixes `DIGEST_INVALID` errors (among others)

TODO:

* [x] Merge #4808 into `master`
* [x] Merge #4817 into `master` 
* [x] Add release notes for #4808 on `master` => #4840
* [x] Add release notes for #4817 on `master` => #4840
* [x] Backport #4808 to `release/5.7.x` => #4842
* [x] Backport #4817 to `release/5.7.x` => #4842
* [x] Add release notes for #4808 `release/5.7.x` => #4842
* [x] Add release notes for #4817 `release/5.7.x` => #4842
* [x] :shipit:

**Comment by vito** [comment]
shipped it!
