### ISSUE TITLE
Release v5.8.0

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#4859]
- [x] add all relevant PRs/issues to milestone
- [x] review open PRs
- [x] packaging
    - [x] bosh - concourse/concourse-bosh-release#80
    - [x] helm concourse/concourse-chart#33, @deniseyu is handling the conjur and microsoft login flags
- [x] docs
    - [x] `set_pipeline` - concourse/docs#281
    - [x] customize roles - concourse/docs#282
    - [x] per-pipeline credential managers (`var_source`) - @vito is writing
- [x] review release notes - dry-run generating them and assess duplication with older patches - #4906
    - [x] `set_pipeline`
    - [x] customize roles
    - [x] per-pipeline credential managers (`var_source`) #4979
    - [x] talk about incomplete feature-flagged containerd work: #4779, #4778, #4752, #4853, #4784
    - [x] revisit CF auth flags discussion: #4729, #4712
    - [x] @pivotal-jwinters #4720
    - [x] german postgres #4701
- [x] wait for git resource 1.6.3
- [x] babysit pipeline
- [x] :shipit:

**Comment by evanchaoli** [comment]
@pivotal-jamie-klassen Can we include #4858? That is a tiny fix.

**Comment by zoetian** [comment]
small updates: 
- added `documented` tag for PR `4865`
- added the release notes for `4701` (interesting bug)

**Comment by pivotal-jamie-klassen** [comment]
last-minute thoughts from @evanchaoli https://github.com/concourse/concourse/pull/4777#discussion_r358216367

**Comment by evanchaoli** [comment]
> last-minute thoughts from @evanchaoli [#4777 (comment)](https://github.com/concourse/concourse/pull/4777#discussion_r358216367)

@pivotal-jamie-klassen Are you going to release 5.8.0 today? I suppose this should not impact the release schedule. If @vito agrees with the change, the change can be done in 5 minutes; or if @vito disagrees, then you may go ahead release 5.8.0, and leave the discussion to next release.

**Comment by zoetian** [comment]
We're just trying right now to figure out why `k8s-check-helm-params` complains about a missing `CONFIG_RBAC` parameter, but `bosh-check-props` does not

**Comment by zoetian** [comment]
TIL be careful what is in the current directory before you run `helm package` https://github.com/helm/helm/issues/4574#issuecomment-417877356

**Comment by vito** [comment]
Someone requested we get https://github.com/concourse/git-resource/pull/290 in, I'll ship it as v1.7.0 and we'll see if it makes it into the pipeline. Not a blocker, since folks can just use the resource through `resource_types:` anyway.

**Comment by radoslav-tomov** [comment]
> Someone requested we get [concourse/git-resource#290](https://github.com/concourse/git-resource/pull/290) in, I'll ship it as v1.7.0 and we'll see if it makes it through the pipeline. Not a blocker, since folks can just use the resource through `resource_types:` anyway.

Not really. We are shipping in a self-contained type of deployment with pre-compiled bosh releases and we are running them in a location with no internet connectivity to docker hub.  All docker images are consumed from an internal registry.  We have a workaround, but it is not pretty. If it does get into 5.8.0 we will try to adopt it as fast as possible :). 

Thanks again anyways. This change and your support & consideration are much appreciated.

**Comment by pivotal-jamie-klassen** [comment]
@radoslav-tomov FWIW git-resource v1.7.0 is definitely going to be packaged with Concourse v5.8.0

**Comment by pivotal-jamie-klassen** [comment]
it's shipped!

**Comment by radoslav-tomov** [comment]
@pivotal-jamie-klassen  Great news.  I'll give a try tomorrow.
