### ISSUE TITLE
Implement Garden Container interface using containerd container API

### ISSUE THREAD

**Issue by deniseyu** [concourse/concourse#4877]
We'll need to have the containerd API talk like a Garden container, [similar to how Houdini works](https://github.com/vito/houdini/blob/master/container.go), so that we can get something working end to end.

- [x] Implement `Handle()` #4913
- [x] Implement `Stop()` https://github.com/concourse/concourse/issues/4918
- [ ] Implement `Info()`
- [ ] Implement `Run()`
- [ ] Implement `Attach()`
- [ ] Implement `Property` management methods (`Property()`, `SetProperty()`, `Properties()`)
- [ ] Fix `Lookup` partial implementation in backend

Check if we still need these:

- [ ] Implement `Current*Limits()` (Bandwidth, CPU, Disk)?
- [ ] Implement `Limit*()` (Bandwidth, CPU, Disk)?
- [ ] Implement `StreamIn()`?
- [ ] Implement `StreamOut()`?
- [ ] Implement `Metrics()`?
- [ ] `SetGraceTime()`?

References:

* [Garden Container interface](https://github.com/cloudfoundry/garden/blob/master/container.go)
* [Houdini implementation](https://github.com/vito/houdini/blob/master/container.go)
* [Alex's spike code from before](https://github.com/concourse/concourse/blob/containerd-impl/gcontainerd/container.go)

**Comment by cirocosta** [comment]
Hey,

I just updated https://github.com/concourse/concourse/issues/4783 to have all the methods so that we keep track of it all in that single issue.

Thanks!
