### ISSUE TITLE
Archiving pipelines through `fly`

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5055]
This epic represents implementing the RFC 33 (concourse/rfcs#33) entirely as specified.

This epic involves the "core" domain for actually implementing the 'archived pipeline' semantics, for implementing `fly archive-pipeline`, and for implementing the automatic archiving behavior for pipelines which are configured through the `set_pipeline` step.

Later on this project will involve the "UX" domain for determining how archived pipelines are shown (and hidden) in the web UI.

**Comment by taylorsilva** [comment]
Remaining items...

**Given**
```
$ fly -t dev set-pipeline -p test -c topgun/pipelines/custom-types.yml
$ fly -t dev archive-pipeline -p test
```

**Then**
* [ ] API action `GetConfig` will `404`; when a pipeline is archived its config is removed to avoid leaking sensitive information.
  * Currently:
    ```
    HTTP/1.1 200 OK
		{"config":{"jobs":[{"name":"","plan":null}]}}
    ```
  * Desired:
    ```
    $ fly -t dev get-pipeline -p test
    <some error>
    ```
* [ ] API action `CreateJobBuild` and `ScheduleJob` will error; archived pipelines must consume no scheduling resources, not even the build starter.

  * Currently:
    ```
    CreateJobBuild

    POST /api/v1/teams/main/pipelines/archived-2/jobs/test/builds HTTP/1.1
    2020/04/13 12:22:01 HTTP/1.1 200 OK

    ScheduleJob

    PUT /api/v1/teams/main/pipelines/archived-2/jobs/test/schedule HTTP/1.1
    2020/04/13 12:20:40 HTTP/1.1 200 OK
    ```
  * Desired:
    ```
    $ fly -t dev trigger-job -j test/job
    <some error>
    ```
* [ ] API action `ScheduleJob` will error; archived pipelines must consume no scheduling resources, not even the build starter.

  * Currently:
    ```
    PUT /api/v1/teams/main/pipelines/archived-2/jobs/test/schedule HTTP/1.1
    HTTP/1.1 200 OK
    ```
  * Desired:
    ```
    $ fly -t dev schedule-job -j test/job
    <some error>
    ```
* [ ] `CheckResource` and `CheckResourceType` will error; archived pipelines must consume no scheduling resources, including queuing checks.

  * Currently:
    ```
    CheckResource

		POST /api/v1/teams/main/pipelines/archived-2/resources/interval/check HTTP/1.1
    {"from":null}
		HTTP/1.1 201 Created

		CheckResourceType

    POST /api/v1/teams/main/pipelines/archived-2/resource-types/time/check HTTP/1.1
    {"from":null}
    HTTP/1.1 201 Created

    ```
  * Desired:
    ```
    $ fly -t dev check-resource -r test/resource-name
    <some error>
    $ fly -t dev check-resource-type -r test/resource-name
    <some error>
    ```
* [ ] `PinResourceVersion`, `UnpinResource`, `EnableResourceVersion`, `DisableResourceVersion`, and `SetPinCommentOnResource` will error; archived pipelines are read-only.
	all should probably be revisited:
  * Currently (only tested one, assumed the rest behave the same):
    ```
    PinResourceVersion

    PUT /api/v1/teams/main/pipelines/archived-2/resources/interval/versions/3/pin
    HTTP/1.1 200 OK
    ```
  * Desired:
    ```
    $ fly -t dev pin-resource -r test/resource-name -v version --comment "some comment"
    <some error>
    $ fly -t dev unpin-resource -r test/resource-name
    <some error>
    $ fly -t dev enable-resource-version -r test/resource-name -v version
    <some error>
    $ fly -t dev disable-resource-version -r test/resource-name -v version
    <some error>
    ```
