### ISSUE TITLE
Release v6.0

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5063]
The outcome of this epic is to make a v6.0 beta available as a GitHub release (specifically a pre-release).

* [x] Upgrade old prod environment
* [x] Upgrade wings.pivotal.io
* [x] Merge `release/6.0.x` into `master`
* [x] Documentation
* [x] Release notes
* [x] Upgrade new prod environment (ci.concourse-ci.org)
  * Wait a bit and monitor the metrics
* [x] Upgrade Hush House environment (hush-house.pivotal.io)
* [x] Once a candidate makes it through the pipeline, ~~manually create a pre-release~~ publish a pre-release using the pipeline

**Comment by vito** [comment]
Upgrading Prod was a little shakey:

```
E 2020-01-28T14:40:03.954240Z [1930268]: [3-1] db=atc,user=atc ERROR:  deadlock detected at character 26 
I 2020-01-28T14:40:03.954833Z [1930268]: [4-1] db=atc,user=atc DETAIL:  Process 1930268 waits for AccessShareLock on relation 16563 of database 16408; blocked by process 1930310. 
I 2020-01-28T14:40:03.955018Z 	Process 1930310 waits for AccessExclusiveLock on relation 16624 of database 16408; blocked by process 1930268. 
I 2020-01-28T14:40:03.955180Z 	Process 1930268: SELECT j.name, j.id FROM jobs j WHERE j.pipeline_id = $1 
I 2020-01-28T14:40:03.955428Z 	Process 1930310: ALTER TABLE pipelines 
I 2020-01-28T14:40:03.955688Z 	    DROP COLUMN schedule_requested, 
I 2020-01-28T14:40:03.955914Z 	    DROP COLUMN last_scheduled 
I 2020-01-28T14:40:03.956088Z [1930268]: [5-1] db=atc,user=atc HINT:  See server log for query details. 
I 2020-01-28T14:40:03.956384Z [1930268]: [6-1] db=atc,user=atc STATEMENT:  SELECT j.name, j.id FROM jobs j WHERE j.pipeline_id = $1 
E 2020-01-28T14:40:04.699603Z [1930130]: [19-1] db=atc,user=atc ERROR:  column "last_scheduled" does not exist at character 81 
I 2020-01-28T14:40:04.700359Z [1930130]: [20-1] db=atc,user=atc STATEMENT:   
I 2020-01-28T14:40:04.700710Z 			UPDATE pipelines 
I 2020-01-28T14:40:04.700964Z 			SET last_scheduled = now() 
I 2020-01-28T14:40:04.701163Z 			WHERE id = $1 
I 2020-01-28T14:40:04.702457Z 				AND now() - last_scheduled > ($2 || ' SECONDS')::INTERVAL 
I 2020-01-28T14:40:04.702748Z 		 
```

Might want to defer actually dropping the column until a (much?) later migration in order to avoid this deadlock.

It eventually worked after being in `CrashLoopBackoff` for a while.

**Comment by vito** [comment]
Seeing the following scheduler logs:

```
8 errors occurred:
	* schedule job: get build inputs: adopt inputs and pipes: sql: no rows in result set
	* schedule job: get build inputs: adopt inputs and pipes: sql: no rows in result set
	* schedule job: get build inputs: adopt inputs and pipes: sql: no rows in result set
	* schedule job: get build inputs: adopt inputs and pipes: sql: no rows in result set
	* schedule job: get build inputs: adopt inputs and pipes: sql: no rows in result set
	* schedule job: get build inputs: adopt inputs and pipes: sql: no rows in result set
	* schedule job: get build inputs: adopt inputs and pipes: sql: no rows in result set
	* schedule job: get build inputs: adopt inputs and pipes: sql: no rows in result set
```

**Comment by vito** [comment]
Our Prometheus metrics need to be updated for the new algorithm.

**Comment by vito** [comment]
Here are the jobs that haven't been scheduled, following on the thread from https://github.com/concourse/concourse/issues/5063#issuecomment-579287434:

```
atc@34:atc> select p.name, j.name, j.last_scheduled, j.schedule_requested from jobs j, pipelines p where p.id = j.pipeline_id and schedule_requested > last_scheduled order by last_scheduled asc;
+------------------+-----------------------------+-------------------------------+-------------------------------+
| name             | name                        | last_scheduled                | schedule_requested            |
|------------------+-----------------------------+-------------------------------+-------------------------------|
| concourse        | publish-binaries            | 1970-01-01 00:00:00+00        | 2020-01-28 14:40:34.372373+00 |
| release-5.5.x    | patch                       | 1970-01-01 00:00:00+00        | 2020-01-28 14:46:43.555333+00 |
| concourse        | publish-bosh-release        | 1970-01-01 00:00:00+00        | 2020-01-28 14:42:02.741336+00 |
| release-5.2.x    | patch                       | 1970-01-01 00:00:00+00        | 2020-01-28 14:40:34.420261+00 |
| release-5.2.x    | publish-binaries            | 1970-01-01 00:00:00+00        | 2020-01-28 14:40:35.62152+00  |
| concourse        | bosh-bump                   | 1970-01-01 00:00:00+00        | 2020-01-28 14:40:35.174428+00 |
| release-5.2.x    | publish-image               | 2020-01-28 14:40:35.410452+00 | 2020-01-28 14:45:44.582209+00 |
| release-5.5.x    | publish-image               | 2020-01-28 14:45:44.582209+00 | 2020-01-28 14:46:43.555333+00 |
| monitoring-stats | create-and-run-new-pipeline | 2020-01-28 15:12:28.161141+00 | 2020-01-28 15:14:47.060394+00 |
| monitoring-stats | fly-hijack-failing-build    | 2020-01-28 15:13:36.463848+00 | 2020-01-28 15:14:47.060394+00 |
| monitoring-stats | run-existing-pipeline       | 2020-01-28 15:13:36.463848+00 | 2020-01-28 15:14:47.060394+00 |
+------------------+-----------------------------+-------------------------------+-------------------------------+
SELECT 11
Time: 0.045s
```

Ignoring the `monitoring-stats` results, which seem to be working fine, that leaves us with 8 jobs which matches up with the number of errors from before.

I went on to investigate `concourse/publish-binaries`. Surprisingly, a new build has been created for it:

```
atc@34:atc> select * from builds where id = 399963;
-[ RECORD 1 ]-------------------------
id                 | 399963
name               | 2
status             | pending
scheduled          | True
start_time         | <null>
end_time           | <null>
schema             | <null>
private_plan       | <null>
completed          | False
job_id             | 60
reap_time          | <null>
team_id            | 1
manually_triggered | False
interceptible      | True
nonce              | <null>
public_plan        | {}
pipeline_id        | 6
drained            | False
create_time        | 2020-01-28 14:41:01.689053+00
aborted            | False
rerun_of           | <null>
rerun_number       | 0
inputs_ready       | False
needs_v6_migration | True
SELECT 1
Time: 0.036s
```

Note the `create_time` and `manually_triggered: false`.

This must be the work of the new algorithm. It's surprising that a new build was created, and it's a little concerning because this job is quite "destructive" (it's one of our shipping/publishing jobs).

A new build must have been created because new inputs are available, so here's what they are:

```
$ fly -t ci curl /api/v1/teams/main/pipelines/concourse/jobs/publish-binaries/inputs | jq '.[] | {name, version}'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1747  100  1747    0     0  10040      0 --:--:-- --:--:-- --:--:--  9982
{
  "name": "release-notes",
  "version": {
    "ref": "3294b1f400df1bb6ede52585e3946dce3736e490"
  }
}
{
  "name": "concourse",
  "version": {
    "ref": "4adfcb19cc9dfb22db861608ef8b7003e01ce1dc"
  }
}
{
  "name": "darwin-rc",
  "version": null
}
{
  "name": "linux-rc",
  "version": null
}
{
  "name": "unit-image",
  "version": {
    "digest": "sha256:a21d79ebd578b0db8fbc419570e81b2f20182bd92832143f476dc3ccb1e65bd7"
  }
}
{
  "name": "version",
  "version": {
    "number": "5.8.0-rc.40"
  }
}
{
  "name": "windows-rc",
  "version": null
}
{
  "name": "ci",
  "version": {
    "ref": "cb0a4fb983825ce275e4f6dec2caa02cb6ced6d0"
  }
}
```

Comparing that to the inputs with the current build...:

![Screenshot from 2020-01-28 10-26-28](https://user-images.githubusercontent.com/1880/73277819-ac604680-41b8-11ea-95ca-c465b1c18c53.png)

We can see a few things:

* `concourse` and `unit-image` are the same version. Good!
* `ci` and `release-notes` have new versions. This is fine, as they're unconstrained. Neither inputs are `trigger: true` so this is not the root cause of the build being created.
* `linux-rc`, `darwin-rc`, and `windows-rc` have no version. :thinking: This is probably why we're seeing those errors. 
* `version` is `5.8.0-rc.40` instead of `5.8.0` :scream: 

Now I'm going to look into those last two bullet points.

**Comment by vito** [comment]
Let's get the boring point out of the way first:

> * `linux-rc`, `darwin-rc`, and `windows-rc` have no version. thinking This is probably why we're seeing those errors.

These three resources now only have one version in their history, and it's not the version that the builds want, so they're just gonna be pending forever. Really we should change these resources because they're an incorrect use of the GCS/S3 resource; the filenames don't contain any sensible version number.

On to the mystery of `publish-image` jobs...:

Looking at `publish-image` in `release-5.5.x`, it looks like it suffered from the same fate. A build actually ran - and errored, thankfully - again with a RC version instead of the final version:

![Screenshot from 2020-01-28 10-47-26](https://user-images.githubusercontent.com/1880/73279742-94d68d00-41bb-11ea-8eff-734bf0fdfd5e.png)

The logs for the previous build has been reaped (hence https://github.com/concourse/hush-house/commit/80031654208a74312055442172c4e1a5164ea5da), however I can at least recover the inputs through the database:

```sql
atc@34:atc> select b.id, p.name, j.name, b.name from jobs j, pipelines p, builds b where b.job_id = j.id and j.name = 'publish-image' and p.id = j.pipeline_id and b.status = 'succeeded';
+--------+---------------+---------------+--------+
| id     | name          | name          | name   |
|--------+---------------+---------------+--------|
| 479    | release-5.7.x | publish-image | 1      |
| 8227   | release-5.7.x | publish-image | 2      |
| 265037 | concourse     | publish-image | 1      |
| 335    | release-5.2.x | publish-image | 1      |
| 121214 | release-5.2.x | publish-image | 2      |
| 385    | release-5.5.x | publish-image | 1      |
| 128644 | release-5.5.x | publish-image | 2      |
| 129558 | release-5.5.x | publish-image | 3      |
+--------+---------------+---------------+--------+
SELECT 8
Time: 0.044s
atc@34:atc> select * from build_resource_config_version_inputs where build_id = 129558;
+------------+---------------+----------------------------------+----------------------------------+--------------------+
| build_id   | resource_id   | version_md5                      | name                             | first_occurrence   |
|------------+---------------+----------------------------------+----------------------------------+--------------------|
| 129558     | 233           | fe67fcf0a4aa0c31b149b01d885b4d51 | latest-version                   | <null>             |
| 129558     | 228           | 63081d906763d53ae34279da09c46b52 | concourse-rc-image               | <null>             |
| 129558     | 220           | b31e9b69fea05e5cd08910c0919dec48 | concourse                        | <null>             |
| 129558     | 232           | bdbeb85a9fcd6f6c9578bcdc6a21348c | version                          | <null>             |
| 129558     | 221           | 60161a2af3a44ac98dfabe9e67b8bb44 | ci                               | <null>             |
| 129558     | 234           | fe67fcf0a4aa0c31b149b01d885b4d51 | latest-of-same-major-version     | <null>             |
| 129558     | 229           | 4adb54662b1b2acdb5e8204eab476b12 | concourse-rc-image-ubuntu-rootfs | <null>             |
| 129558     | 229           | 4adb54662b1b2acdb5e8204eab476b12 | concourse-rc-image-ubuntu        | <null>             |
+------------+---------------+----------------------------------+----------------------------------+--------------------+
SELECT 8
Time: 0.043s
atc@34:atc> select * from resource_config_versions where version_md5 = 'bdbeb85a9fcd6f6c9578bcdc6a21348c';
+---------+---------------------+----------------------------------+----------------------------------------+---------------+----------------------------+
| id      | version             | version_md5                      | metadata                               | check_order   | resource_config_scope_id   |
|---------+---------------------+----------------------------------+----------------------------------------+---------------+----------------------------|
| 9810226 | {"number": "5.5.7"} | bdbeb85a9fcd6f6c9578bcdc6a21348c | [{"Name": "number", "Value": "5.5.7"}] | 22027         | 484                        |
+---------+---------------------+----------------------------------+----------------------------------------+---------------+----------------------------+
SELECT 1
Time: 0.074s
```

This shows that the prior build ran (correctly) with 5.5.7.

It looks like something is broken with #4285 - possibly specifically in the case of incremental migrations. Going to investigate the `successful_build_outputs` table for the upstream jobs next and see if the data is wrong.

**Comment by vito** [comment]
Quick note: here are all the builds/jobs to investigate:

```
$ fly -t ci builds --since '2020-01-28 09:32:11' | grep pending
399979  release-5.5.x/publish-image                   5      pending    n/a                       n/a                       n/a    main      
399978  release-5.5.x/patch                           3      pending    n/a                       n/a                       n/a    main      
399977  release-5.2.x/publish-image                   3      pending    n/a                       n/a                       n/a    main      
399968  concourse/publish-bosh-release                2      pending    n/a                       n/a                       n/a    main      
399964  concourse/bosh-bump                           37     pending    n/a                       n/a                       n/a    main      
399963  concourse/publish-binaries                    2      pending    n/a                       n/a                       n/a    main      
399962  release-5.2.x/publish-binaries                4      pending    n/a                       n/a                       n/a    main      
399961  release-5.2.x/patch                           5      pending    n/a                       n/a                       n/a    main      
```

**Comment by vito** [comment]
Investigating `successful_build_outputs` yields the following:

```
atc@34:atc> select b.id, p.name, j.name, b.name from jobs j, pipelines p, builds b where b.job_id = j.id and j.name = 'shipit' and p.id = j.pipeline_id and b.status = 'succeeded';
+--------+---------------+--------+--------+
| id     | name          | name   | name   |
|--------+---------------+--------+--------|
| 476    | release-5.7.x | shipit | 1      |
| 8212   | release-5.7.x | shipit | 2      |
| 265022 | concourse     | shipit | 2      |
| 281    | release-5.2.x | shipit | 1      |
| 121203 | release-5.2.x | shipit | 2      |
| 381    | release-5.5.x | shipit | 1      |
| 128616 | release-5.5.x | shipit | 2      |
+--------+---------------+--------+--------+
SELECT 7
Time: 0.049s
atc@34:atc> select * from successful_build_outputs where build_id = 128616;
+------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>
| build_id   | job_id   | outputs                                                                                                                                                                                                                                                          >
|------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>
| 128616     | 125      | {"220": ["b31e9b69fea05e5cd08910c0919dec48"], "228": ["63081d906763d53ae34279da09c46b52"], "229": ["4adb54662b1b2acdb5e8204eab476b12"], "232": ["bdbeb85a9fcd6f6c9578bcdc6a21348c", "c21339be7e38700b5025fcae7bd2848a"], "235": ["826a4c31e2eabb15131a25c2106d321>
+------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>
SELECT 1
Time: 0.044s
atc@34:atc> select outputs->'232' from successful_build_outputs where build_id = 128616;
+--------------------------------------------------------------------------+
| ?column?                                                                 |
|--------------------------------------------------------------------------|
| ["bdbeb85a9fcd6f6c9578bcdc6a21348c", "c21339be7e38700b5025fcae7bd2848a"] |
+--------------------------------------------------------------------------+
SELECT 1
Time: 0.042s
```

Here we see our friend `bdbeb85a9fcd6f6c9578bcdc6a21348c` from https://github.com/concourse/concourse/issues/5063#issuecomment-579314903 which we know to be 5.5.7 (the correct and desired version).

But who is this `c21339be7e38700b5025fcae7bd2848a` guy?

```
atc@34:atc> select * from resource_config_versions where version_md5 = 'c21339be7e38700b5025fcae7bd2848a';
+---------+---------------------------+----------------------------------+----------------------------------------------+---------------+----------------------------+
| id      | version                   | version_md5                      | metadata                                     | check_order   | resource_config_scope_id   |
|---------+---------------------------+----------------------------------+----------------------------------------------+---------------+----------------------------|
| 9764302 | {"number": "5.5.7-rc.23"} | c21339be7e38700b5025fcae7bd2848a | [{"Name": "number", "Value": "5.5.7-rc.23"}] | 22026         | 484                        |
+---------+---------------------------+----------------------------------+----------------------------------------------+---------------+----------------------------+
SELECT 1
Time: 0.076s
```

That's the version that was chosen for the build (which errored).

I wonder if we just have the order wrong? :thinking: If the correct version was listed last, would it have been chosen?

Looking at the code, it looks like listing the outputs first *is* the behavior we want...:

https://github.com/concourse/concourse/blob/d98a69f4ba24c34bdf88d5b7d386a486f7665761/atc/db/build.go#L414-L503

...so why isn't the algorithm choosing this version? :thinking: :thinking:

**Comment by vito** [comment]
Found it.

https://github.com/concourse/concourse/blob/d98a69f4ba24c34bdf88d5b7d386a486f7665761/atc/db/versions_db.go#L215-L217

This little sucker undoes the hard-earned ordering semantics.

Here's a repro case:

```go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strconv"

	"github.com/concourse/concourse/atc/db"
)

func main() {
	outputsJSON := `
{
    "220": [
        "b31e9b69fea05e5cd08910c0919dec48"
    ],
    "228": [
        "63081d906763d53ae34279da09c46b52"
    ],
    "229": [
        "4adb54662b1b2acdb5e8204eab476b12"
    ],
    "232": [
        "bdbeb85a9fcd6f6c9578bcdc6a21348c",
        "c21339be7e38700b5025fcae7bd2848a"
    ],
    "235": [
        "826a4c31e2eabb15131a25c2106d3215"
    ],
    "236": [
        "826a4c31e2eabb15131a25c2106d3215"
    ],
    "237": [
        "7d21b4ebc9f28c7787a35de3f55a4f25"
    ],
    "238": [
        "1d082ec7ea9bfb0802e8bb1ea1b2782e"
    ],
    "241": [
        "fd0c89c396f71a7df76e0a6992350113"
    ],
    "247": [
        "333a8e9fd288d082bc21b51c8e225bd5"
    ],
    "254": [
        "fef7512deb07389c5f00df6b435e75d6"
    ],
    "255": [
        "53db290431008c2eb2294df0fe547f25"
    ]
}`

	outputs := map[string][]string{}
	err := json.Unmarshal([]byte(outputsJSON), &outputs)
	if err != nil {
		panic(err)
	}

	algorithmOutputs := []db.AlgorithmVersion{}
	for resID, v := range outputs {
		for _, version := range v {
			resourceID, err := strconv.Atoi(resID)
			if err != nil {
				panic(err)
			}

			algorithmOutputs = append(algorithmOutputs, db.AlgorithmVersion{
				ResourceID: resourceID,
				Version:    db.ResourceVersion(version),
			})
		}
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")

	fmt.Println("----------------------- BEFORE SORT")
	err = enc.Encode(algorithmOutputs)
	if err != nil {
		panic(err)
	}

	// XXX: sketchy sketchy? does this preserve outputs > inputs?
	sort.Slice(algorithmOutputs, func(i, j int) bool {
		return algorithmOutputs[i].ResourceID < algorithmOutputs[j].ResourceID
	})

	fmt.Println("----------------------- AFTER SORT")
	err = enc.Encode(algorithmOutputs)
	if err != nil {
		panic(err)
	}
}
```

Output:

```
----------------------- BEFORE SORT
[
  {
    "ResourceID": 247,
    "Version": "333a8e9fd288d082bc21b51c8e225bd5"
  },
  {
    "ResourceID": 254,
    "Version": "fef7512deb07389c5f00df6b435e75d6"
  },
  {
    "ResourceID": 255,
    "Version": "53db290431008c2eb2294df0fe547f25"
  },
  {
    "ResourceID": 220,
    "Version": "b31e9b69fea05e5cd08910c0919dec48"
  },
  {
    "ResourceID": 229,
    "Version": "4adb54662b1b2acdb5e8204eab476b12"
  },
  {
    "ResourceID": 232,
    "Version": "bdbeb85a9fcd6f6c9578bcdc6a21348c"
  },
  {
    "ResourceID": 232,
    "Version": "c21339be7e38700b5025fcae7bd2848a"
  },
  {
    "ResourceID": 236,
    "Version": "826a4c31e2eabb15131a25c2106d3215"
  },
  {
    "ResourceID": 241,
    "Version": "fd0c89c396f71a7df76e0a6992350113"
  },
  {
    "ResourceID": 228,
    "Version": "63081d906763d53ae34279da09c46b52"
  },
  {
    "ResourceID": 235,
    "Version": "826a4c31e2eabb15131a25c2106d3215"
  },
  {
    "ResourceID": 237,
    "Version": "7d21b4ebc9f28c7787a35de3f55a4f25"
  },
  {
    "ResourceID": 238,
    "Version": "1d082ec7ea9bfb0802e8bb1ea1b2782e"
  }
]
----------------------- AFTER SORT
[
  {
    "ResourceID": 220,
    "Version": "b31e9b69fea05e5cd08910c0919dec48"
  },
  {
    "ResourceID": 228,
    "Version": "63081d906763d53ae34279da09c46b52"
  },
  {
    "ResourceID": 229,
    "Version": "4adb54662b1b2acdb5e8204eab476b12"
  },
  {
    "ResourceID": 232,
    "Version": "bdbeb85a9fcd6f6c9578bcdc6a21348c"
  },
  {
    "ResourceID": 232,
    "Version": "c21339be7e38700b5025fcae7bd2848a"
  },
  {
    "ResourceID": 235,
    "Version": "826a4c31e2eabb15131a25c2106d3215"
  },
  {
    "ResourceID": 236,
    "Version": "826a4c31e2eabb15131a25c2106d3215"
  },
  {
    "ResourceID": 237,
    "Version": "7d21b4ebc9f28c7787a35de3f55a4f25"
  },
  {
    "ResourceID": 238,
    "Version": "1d082ec7ea9bfb0802e8bb1ea1b2782e"
  },
  {
    "ResourceID": 241,
    "Version": "fd0c89c396f71a7df76e0a6992350113"
  },
  {
    "ResourceID": 247,
    "Version": "333a8e9fd288d082bc21b51c8e225bd5"
  },
  {
    "ResourceID": 254,
    "Version": "fef7512deb07389c5f00df6b435e75d6"
  },
  {
    "ResourceID": 255,
    "Version": "53db290431008c2eb2294df0fe547f25"
  }
]
```

Note the order of the `"ResourceID": 232` entries has been swapped. :boom:

**Comment by vito** [comment]
(This nondeterministic order also explains why *another* pending build was queued up for `publish-image`.)

**Comment by vito** [comment]
Prod is stuck scheduling one of the jobs.

Opened https://github.com/concourse/concourse/issues/5092 to track making the scheduler not grind to a halt due to a single job, and will be picking that up. I'm also refactoring the algorithm and integrating tracing which should help figure this out (https://github.com/concourse/concourse/issues/5094).

Looking at the goroutine stack, it doesn't seem to get stuck on any call in particular - it looks like a logic error, i.e. it's stuck in some sort of loop.

I also created https://github.com/concourse/concourse/issues/5093 since now this has me worried that we'll have our hands tied if this happens in an environment we don't have intimate access to.

**Comment by vito** [comment]
Ready to go.

TODO:

* [ ] Upgrade Hush House once more
* [ ] Merge release notes (#5353)
* [ ] Ship it!
* [ ] Switch the Blog theme
* [ ] Switch the Discuss theme
* [ ] Deploy Resource Types section (https://github.com/concourse/resource-types-website/pull/204)

**Comment by vito** [comment]
DONE!
