### ISSUE TITLE
epic: continuous delivery of containerd-based workers 

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#5178]
### challenge

Currently, we neither exercise our [`containerd`]-based implementation of the
garden interface as much as we do for`gdn` in a continuous manner, nor update
the dependencies in a continuous fashion.

Not continuously updating our dependencies imply in us being exposed to
potential integration problems later on, as well as being at mercy of not
getting security patches in a timely manner.

Not having our end-to-end tests exercising those workers mean that certain
scenarios not captured by the very specific `containerd`-integration might go
unnoticed, leaving us to potential regressions, and not inspiring much
confidence as we integrate our code.

So far, the only non-unit tests that we have running to validate `containerd` is
the set of integration tests that exercise `containerd` from the perspective of
a consumer of the `garden` interface (see concourse/ci#253), and dependencies
are manually bumped.

### a better world

It'd be much better if all of that was automated, as it currently is for `gdn`.

### stories

- [x] Have `testflight` tests running against containerd-based workers
  (concourse/ci#267)
- [x] Have `bin-smoke` tests running against containerd-based workers
  (concourse/ci#284)
- [x] Package `containerd` binaries into concourse's distribution
- [x] Automatically bump `containerd` and its deps (concourse/concourse#4993)
  - [x] update cni https://github.com/concourse/concourse/issues/5110
  - [x] update containerd and its dependencies (there's recently been a new
    release of `containerd`, as well as `runc`)

### acceptance

- [x] we're able to have containerd-based workers registering against a cluster
  and being able to "do the work"
- [x] testflight tests against a containerd-based worker pass

[`testflight`]:
https://github.com/concourse/concourse/blob/master/testflight/README.md
[`containerd`]: https://github.com/containerd/containerd

**Comment by taylorsilva** [comment]
Waiting for https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bin-smoke-containerd/ to pass and then this epic is done

**Comment by taylorsilva** [comment]
waiting for https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight-containerd/builds/1 to pass and THEN this epic is done
