### ISSUE TITLE
epic: `gdn`-like functionality for `containerd`-based workers

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#5179]
Despite having the [`garden`] interface implementeed (see #4783), there
are certain features of [`gdn`] (the Linux implementation of Garden that
we've been using for a long time) that need to be implemented to have a
seamless transition from `gdn` to [`containerd`].

For instance, in [`hush-house`] itself, we leverage the ability to set
the CIDR of the network under which containers are placed, as well as an
IP that we want `gdn` to block.

```yaml
- name: CONCOURSE_GARDEN_NETWORK_POOL
value: "10.254.0.0/16"
- name: CONCOURSE_GARDEN_DENY_NETWORK
value: "169.254.169.254/32"
```

https://github.com/concourse/hush-house/blob/290f5fdecc0c160147e6fef7c00349c6690f0a56/deployments/with-creds/ci/values.yaml#L71-L76

### challenge

It's not possible to just swap `gdn` by `containerd` and get the same benefits as we had
before.

### a better world

in a better world, we have the ability to seamlessly switch between `gdn` and
`containerd`without losing very necessary features that we rely on today.

### stories

- [ ] support the use of concourse worker's DNS server https://github.com/concourse/concourse/issues/5139
- [ ] make cni network config configurable https://github.com/concourse/concourse/issues/5140
- [ ] support configuring default dns servers https://github.com/concourse/concourse/issues/5138

### acceptance

- [ ] we're able to have our environments' workers using `containerd`without losing
      functionality.

[`hush-house`]: https://github.com/concourse/hush-house
[`gdn`]: https://github.com/cloudfoundry/guardian
[`containerd`]: https://github.com/containerd/containerd
[`garden`]: https://github.com/cloudfoundry/garden

**Comment by muntac** [comment]
@cirocosta As mentioned [here](https://concourse-ci.org/concourse-worker.html#troubleshooting-and-fixing-dns-resolution) by default Guardian carries over the `etc/resolv.conf` of the host. Do we want to emulate this behaviour for `containerd` as well?

If the answer is yes, I'm not sure if any of the issues listed so far cover this functionality.

The link also mentions that for certain Linux distros like `systemd-resolved` have a special nameserver `127.x.x.x`, which gets stripped out by Guardian from the `resolv.conf`, sometimes causing the container to have no DNS entries. If we are do inherit `resolv.conf` in the `containerd` world, would we also want to remove `127.x.x.x` nameservers?

**Comment by muntac** [comment]
The list of [Garden Routes](https://github.com/cloudfoundry/garden/blob/master/routes/routes.go) appears to be comprehensively mirrored in the [Garden client](https://github.com/concourse/concourse/blob/master/atc/worker/gclient/connection/connection.go) of the `atc/worker` package.

While the ability to use all endpoints is listed in `gclient/connection.go` and its wrapper `gclient/container.go`, from a preliminary skim it looks like only a subset of the functionality is used in actual Concourse logic.

It may be useful to identify which endpoints are being used, and if the functionality that they require on the Garden server side has been fully implemented.
