### ISSUE TITLE
epic: leverage `containerd`-specific features

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#5180]
Having the very same base functionality that we'd have from [`gdn`]
implemented for [`containerd`] (#4783, #5178 and #5179), and validated
that our implementation covers our basic needs, we can now start
actually leveraging the unique capabilities that `containerd` can bring
to the table, to:

- make `concourse` more aligned with industry standards,
- reduce some of the work that it might not have to do (given some of
  the funcionality offered by `containerd`).
- be more performant.

### stories

- [ ] can we use the snapshotter to replace baggageclaim volume drivers?  #4363
- [ ] not have to bring our own init #5135
- [ ] investigate use of `firewalld` rather than `iptables` #5136
- [ ] rethink what 'privileged' means for us
- [ ] have `registry-image` resource default to OCI: #4367
- [ ] have `docker-image` resource default to OCI: #4368

**Comment by taylorsilva** [comment]
Keeping this as reference for now. Would love to see most of this stuff implemented, in one form or another.
