### ISSUE TITLE
Action Platform Automation PRs and Topgun Credhub Integration

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#5211]
**Summary**

We have two action items this week to assist the Platform Automation team: 

1.  The Platform Automation team has posted a series of PRs over the last two weeks. Can we look into these and approve/comment/merge? 

PRs:
* [x] [Have a AZs become parameterized](https://github.com/concourse/concourse-bosh-deployment/pull/212)
* [x] [Include Credhub and UAA versions](https://github.com/concourse/concourse-bosh-deployment/pull/211)
* [x] [ensure postgres connections are secure between UAA, Credhub, and Concourse](https://github.com/concourse/concourse-bosh-deployment/pull/210)
* [x] [include higher canary timeouts for UAA](https://github.com/concourse/concourse-bosh-deployment/pull/208)
* [x] [opsfile to enable bosh release offline mode](https://github.com/concourse/concourse-bosh-deployment/pull/207)

2. Our current Topgun Credhub testing is using mutual TLS instead of UAA. What we'd like to do is pair with an engineer from Platform Automation and perform the following:

* [x] Assist Platform Automation with setting up their own local topgun deployment
* [x] Replace mutual TLS with UAA in our credhub topgun tests
* [x] Ensure the metadata including the version of Credhub and UAA tested are dumped into the manifest file for `concourse-bosh-deployment`

**Comment by cirocosta** [comment]
- [ ] update the version of BOSH cli: https://github.com/concourse/ci/issues/278
