### ISSUE TITLE
containerd: organize containerd flags prior to making containerd GA

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#5407]
Currently, we're using some existing `CONCOURSE_GARDEN_*` flags for configuring the `containerd` runtime. This makes it unclear to the user which flags are actually used by `containerd`, and which have no effect. This might allow for ambiguous configurations that could lead to edge cases that are difficult to debug (e.g. an unused flag in a user's deployment in the past caused unpredictable behaviour and was hard to track down).

Some ideas to consider: 

- have separate set of flags for Guardian vs containerd runtimes
- ~have common flags for functionality common to all runtimes under the Concourse namespace. e.g. for setting custom DNS server use `CONCOURSE_DNS_SERVER`~
- having default values wherever possible to make it easy to get Concourse up and running
- have validation that prevents user from specifying Guardian and containerd flags simultaneously

--------------------------
EDIT:

**Requirements**

Add additional `containerd` specific flags (preferably prefixed `CONCOURSE_CONTAINERD`) for the following `CONCOURSE_GARDEN` flags:
- [ ] [CONCOURSE_GARDEN_DNS_PROXY_ENABLE](https://github.com/concourse/concourse/blob/88a99ac185df381987cb51a54a0f4d7ffbdf73ff/worker/workercmd/containerd.go#L151) - support added in https://github.com/concourse/concourse/pull/5465

- [ ] [CONCOURSE_GARDEN_DNS_SERVER](https://github.com/concourse/concourse/blob/88a99ac185df381987cb51a54a0f4d7ffbdf73ff/worker/workercmd/worker_linux.go#L31) - support added in https://github.com/concourse/concourse/pull/5445

- [ ] [CONCOURSE_GARDEN_DENY_NETWORK] - support added in #5829 

- [ ] [CONCOURSE_GARDEN_MAX_CONTAINERS] - support added in #5836 

Prevent mixed usage of Guardian and containerd flags
- [ ] Ensure [CONCOURSE_CONTAINER_NETWORK_POOL](https://github.com/concourse/concourse/blob/88a99ac185df381987cb51a54a0f4d7ffbdf73ff/worker/workercmd/containerd.go#L31) (support added in https://github.com/concourse/concourse/pull/5486) only works for `containerd`. https://github.com/concourse/concourse/pull/5486#issuecomment-620039187 mentioned that this is currently working when using Guardian as well.

- [ ] when using the `concourse worker` command validate that the container runtime flags being configured belong to the chosen runtime e.g. throw an error if `CONCOURSE_GARDEN` flags are being used when `CONCOURSE_USE_CONTAINERD` is enabled.

**Comment by muntac** [comment]
My current understanding is that all the `CONCOURSE_GARDEN_` flags relate to `guardian` specific features as outlined in the `gdn` CLI. They aren't defined anywhere in the `Garden` interface. Perhaps, it would've been more accurate to prefix all those flags as `CONCOURSE_GUARDIAN_` originally.

Either way, this strengthens the case for having `containerd` specific flags as none of the related functionality is defined at the Garden level.

**Comment by YoussB** [comment]
blocked on #5534 and #5226 

cc @muntac

**Comment by muntac** [comment]
TODO: Currently the BOSH release and Helm chart do not expose the same set of flags to the user. As part of this issue we should revisit the reasons for this, and resolve any differences that should not be there.
