### ISSUE TITLE
Epic 1: Rename CI and Create New Repo

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#5493]
**Summary**

We currently have separate clusters for our `ci`, sandbox (manual testing), and automated testing environments. We'd like to look into housing all environments under the same cluster. As an added bonus, it might be interesting to attempt to the deploy the environment via kapp. Before we can do this we'd need to ensure that all environments are on helm 3, as of right now only `ci` is so we can start there.  

It might also make sense to house our whole stack in one repo. This can be a private repo for now and named 'greenpeace'. In the future we may switch this to a public repo and change the name. 

**Action Items**
* [x] Create a new private repo named greenpeace to house all of our various deployments
  * [ ] Document how bootstrapping is done
* [x] Create new cluster via terraform and deploy `ci` via kapp
* [ ] Automate this deployment process
  * [ ] New Epic under #5541

**Comment by scottietremendous** [comment]
@vito - Feel free to edit/fill in any blanks

**Comment by scottietremendous** [comment]
@vito - We should update the acceptance criteria for this and look to split the issue into smaller components.

**Comment by pivotal-jamie-klassen** [comment]
#5508

**Comment by vito** [comment]
Here's an update on secret management, in case anyone wants to provide feedback.

The problem statement: we need this pipeline to have access to credentials which are used for e.g. the Helm deploy of Concourse. Many credentials can be generated, but some - like the GitHub oAuth client ID and secret - just have to be passed right in.

Currently we store these secrets as a note in LastPass which is then written to a `.values.yml` prior to the Helm deploy. However having the pipeline access LastPass isn't practical.

So far we only have one credential - the GCP credentials - so we've been just passing it in as a pipeline var, which then gets passed to Terraform:

```yaml
resources:
- name: production
  type: terraform
  source:
    env_name: production
    backend_type: gcs
    backend_config:
      bucket: concourse-greenpeace
      prefix: terraform
      credentials: ((gcp_credentials_json))
    vars:
      credentials: ((gcp_credentials_json))
```

When bootstrapping, these values are just be provided via a local `vars.yml`, and for production we would find a way to put them into Vault (once it's deployed).

One downside of continuing this pattern for the rest of the secrets is that we would have to provide every secret as a variable to Terraform, which could become unwieldy if we ever have to run `terraform` commands outside of the pipeline. We'd also have to keep updating the pipeline config each time we add a secret, which seems like an easy step to forget.

So, we're currently investigating Google's Secret Manager service and fetching the credentials through the [Terraform `google_secret_manager_secret_version` data source](https://www.terraform.io/docs/providers/google/d/datasource_google_secret_manager_secret_version.html) to fetch credentials. The idea here is that we would just manage these secrets in GCP ourselves. This solves the bootstrapping problem, since we can already assume that GCP is there. It also lets us avoid using LastPass, which we've had weird syncing issues with in the past.
