### ISSUE TITLE
[SPIKE] Investigate DataDog Dashboard Terraform

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#5528]
**Summary**

As part of our overall goal to provide users with the ability to reason about the health of their Concourse deployment(s), we wanted to investigate the possibility of providing configuration files within a accessible repo that would easily set-up a Datadog metrics dashboard for users. 

Originally, we set out to do this via documentation, but @cirocosta pointed us towards a feature in DataDog that would allow users to potentially copy/paste configuration files/snippets that we would provide. As such, there may be a way in which we can have users easily bootstrap a DataDog metrics dashboard that has all of the panels and widgets which would emulate what we use currently on CI/Hush-House. This would involve a lot less toil and documentation from an end-user perspective. 

**Requirements**

- [x] Look into [Datadog Dashboard Terraform](https://www.terraform.io/docs/providers/datadog/r/dashboard.html) 
- [x] Select a metric from CI/Hush House and see if we can set it up on both BOSH and Helm
- [x] Check with @vito to confirm where these configuration files should be stored. Seeing as at first we won't want to package and ship via Pivnet, this will probably be a separate repo from the core Concourse repo. 

**Acceptance Criteria** 

- [x] Confirm whether we can provide the configuration files to both BOSH and Helm users
- [x] Confirm potential repo/location for configuration files
- [ ] If functionality is confirmed, @scottietremendous to create new spike to select a suitable list of metrics to select as a first pass of the feature

**Comment by pivotal-izabela-gomes** [comment]
The findings of this spike were captured in this [repo](https://github.com/pivotal-izabela-gomes/observability-config). It currently re-creates the dashboards we have in Datadog for CI, Hush-House and our old production CI deployed by bosh. The root module invokes the dashboard module 3 times (for CI, Hush-House and old prod) and the dashboard module creates 2 dashboards for each instance: 

1. One dashboard for metrics emitted by Concourse itself (all graphs currently under Web Nodes, Worker Nodes, Containers and Volumes groups in our [existing Datadog dashboard](https://app.datadoghq.com/dashboard/u4v-xsz-yyk/concourse-k8s))

1. One dashboard for system metrics (all graphs under System Stats group).

In the main.tf we pass information to the module about [prefix](https://github.com/concourse/concourse-chart/blob/41337692588cc66b99f7c7ade33353ac1f97597c/values.yaml#L629) for all metrics, as well as others labels (see [this](https://github.com/concourse/hush-house/blob/c7ad85387b28713882c195de70df9fc51ab67482/deployments/with-creds/ci/values.yaml#L125) and [also this](https://github.com/concourse/hush-house/blob/c7ad85387b28713882c195de70df9fc51ab67482/deployments/with-creds/hush-house/values.yaml#L98) to be used to filter metrics. We do that for all three environments and will end up with 6 dashboards in total.

Some notes about the findings:
TBD

**Comment by pivotal-izabela-gomes** [comment]
A comment was added to #5561 with details about the next steps going forward using Terraform Datadog Provider.
