### ISSUE TITLE
Epic 2: Continuously Deploy CI and Vault

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5541]
As part of the same pipeline that continuously runs `terraform apply` to create the `production` cluster (as described in #5508), we should also deploy CI using the Concourse Helm chart.

We can use the [Helm Terraform provider](https://www.terraform.io/docs/providers/helm/index.html) to accomplish this, which will result in us having a single terraform deployment to manage everything (infrastructure, helm releases).

There are several sub-tasks that we'll need to accomplish to have a working CI Concourse deployment:

- [x] Generate secrets (encryption key, admin local user password, host key, worker key, session signing key)
- [x] Create CloudSQL deployment (for CI)
- [x] Create k8s namespaces (ci, vault, datadog)
- [x] Create Concourse Helm release with a templated `values.yml`
- [x] Create Vault service account with limited access
- [x] Create k8s secrets: ~postgres creds~, ~gcp service account creds~ (not needed), vault certs
- [x] Create GCS bucket for as vault backend
- [x] Create Vault Helm release with a templated `values.yml`

**Sub-Issues**

- Vault
  - [x] Somehow automate initialization of Vault (`vault operator init`, get root token, setup cert auth?)
  - [x] Generate Vault certs (self-signed)
  - [x] TODO: match the properties described in https://github.com/pivotal/concourse-ops/wiki/Operating-Vault
  - [x] Create new issue around this

**Acceptance Criteria**

* [x] Have a running CI Concourse deployment deployed via terraform
* [x] Have a pipeline running somewhere redeploy CI

**Comment by aoldershaw** [comment]
Our initial plan was to have CI redeploy itself (i.e. have a pipeline running in CI that will run the Terraform for CI/the production cluster as a whole). We realized this wouldn't work (at least not in a stable way) - if we redeploy CI, the workers that are redeploying CI may fail, and we could be left in a weird state.

To avoid this, we introduced a second cluster called `dispatcher` that has its own Concourse and Vault. It's solely responsible for managing the other clusters and the deployments to those clusters (currently, the only other cluster is `production`, but there will likely be others in the future).

`dispatcher` is running at [dispatcher.concourse-ci.org](dispatcher.concourse-ci.org). It's all automated using Terraform in the [greenpeace](https://github.com/concourse/greenpeace/tree/master/terraform/dispatcher) repo.

CI is running at [ci-test.concourse-ci.org](ci-test.concourse-ci.org) (placeholder name for now so as not to mess with actual CI). Currently, GitHub Auth doesn't work for CI, since we are still using the GitHub OAuth app for the actual CI deployment (which redirects to [ci.concourse-ci.org](ci.concourse-ci.org)). However, you can authenticate using the basic auth with the admin password (stored in Google Secret Manager).
