### ISSUE TITLE
Terraform Datadog Helm release

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5561]
I'm not sure what exactly is entailed here and beyond for configuring datadog.

**Comment by cirocosta** [comment]
### desired outcome

What we intend here is to have metrics from both Concourse and the infrastructure (being on top of k8s, mostly container-related statistics) being sent to Datadog so that our Datadog dashboards work properly.

The way that we've been going about doing that so far has been by leveraging Datadog's Helm Chart (see https://github.com/helm/charts/blob/master/stable/datadog/README.md), which creates a DaemonSet that deploys its agent across all hosts in the cluster, thus, gathering container statistics from all of machines, as well as providing a unix socket that those wanting to submit custom metrics to it can do so via that socket.



```

machine1-----------------------------------
        datadog pod------------------------
                container------------------
                        dd agent
                                listens for conns on /var/run/datadog/dsd.socket
                                captures metrics about container in the machine
                                        (mounts /sys/fs/cgroup, /proc/ and docker.sock)

        concourse pod ---------------------
                container------------------
                        concourse web
                                writes metrics to /var/run/datadog/dsd.socket

```

ps.: this desired outcome is *different* from https://github.com/concourse/concourse/issues/5528 - all we want here is to be able to gather the metrics and forward them to datadog. In #5528, the asumption is that the data already exists in datadog, and then there we want to be able to have the dashboards that consume that data be described as code.


### extra context

In today's setup, `requirements.yaml` references the datadog chart:

```yaml
- name: datadog
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 1.39.5
```

which is what gives us the ability to submit to Kubernetes the definition of the daemonset that will materialize the pods across all machines.

As the agents need to be able to send the metrics they collect & receive to our account, we provide to the datadog chart the apiKey, which turns into a secret, which is then consumed by the agents:

```
## .values.yaml
datadog:
  datadog:
    apiKey: 08d215b0f1bf8f39b338349d63a2ba5d
```

Given that we want to submit Concourse metrics to it, we tell it to listen for `dogstatsd` metrics on a unix socket at a known location:

```yaml
datadog:
  datadog:
    useDogStatsDSocketVolume: true
```

Knowing the location where the unix socket lives in the host, in `concourse` we can have it mounted (so that they both point at the same socket):

```yaml
    additionalVolumes:
      - name: dsdsocket
        hostPath:
          path: /var/run/datadog
    additionalVolumeMounts:
      - name: dsdsocket
        mountPath: /var/run/datadog
```

with the `web` container having the socket accessible as a file in the `/var/run/datadog` directory, all that we need to do to finish the setup is to have Concourse enabling the datadog emitter, pointing it to the socket:

```
      datadog:
        enabled: true
        # horrible hack; we need a proper way to configure unix sockets
        agentHost: unix
        agentPort: ///var/run/datadog/dsd.socket
```

**Comment by pivotal-izabela-gomes** [comment]
### Describe our existing datadog dashboards as code

This task assumes that the data/metrics already exist in datadog and all we want is to be able to create (and re-create) dashboards on Datadog using (Terraform Datadog Provider)[https://www.terraform.io/docs/providers/datadog/index.html]. 

Some of the initial work/investigation was done as part of the spike  #5528 . The conclusion was that our dashboards can be recreated by calling a Terraform module and passing information about the Concourse instance that we want to monitor (metric labels and deployment tool utilized to deploy Concourse). The spike repo contains a module that creates 2 dashboards for a Concourse instance: one dashboard has all the graphs under the groups `Web Nodes`, `Worker Nodes`, `Containers and Volumes` (according to our current Datadog setup as of May 30th, 2020). The other dashboard contains all graphs under `System Stats` group. The later has different metrics depending on what deployment tool was used to deploy Concourse (bosh or helm). The list below describes what remains to be done as part of this issue:

- [ ] Select which metrics we actually want to keep

- [ ] Confirm if the current System Stats metrics make sense for both (bosh)[https://github.com/pivotal-izabela-gomes/observability-config/blob/master/dashboards/systemstats_bosh.tf] and for (helm)[https://github.com/pivotal-izabela-gomes/observability-config/blob/master/dashboards/systemstats_bosh.tf]

- [ ] Add the (Terraform module)[https://github.com/pivotal-izabela-gomes/observability-config] to the (hush-house)[https://github.com/concourse/hush-house] repo, so we can start using it ourselves to bootstrap our DataDog metrics dashboard

- [ ] Look into (versioned modules)[https://www.terraform.io/docs/configuration/modules.html#module-versions]  

- [ ] Inform our team that any changes and additions to our dashboards should be done via Terraform module, or I should say, reflected in the hush-house repo as code

- [ ] Update docs to include instructions on how use the Terraform module to bootstrap Datadog dashboards for Concourse

**Comment by jamieklassen** [comment]
@cirocosta can you comment on the choice between
* mounting a unix domain socket (per the [Kubernetes section of the Agent docs](https://docs.datadoghq.com/agent/kubernetes/?tab=helm#dogstatsd-custom-metrics))
* accessing a UDP port via the downward API (per the [Helm tab of the Agent section of the DogStatsD docs](https://docs.datadoghq.com/developers/dogstatsd/?tab=helm#agent)) 
* having the datadog agent scrape the prometheus endpoint directly (per the [Prometheus subsection of the Kubernetes section of the Agent docs](https://docs.datadoghq.com/agent/kubernetes/prometheus/) -- I can imagine there might be data conversion issues here)

I think I've probably answered my own question here as I learned more about how the datadog docs are organized. If you started by looking up "kubernetes datadog agent" the docs kinda make it seem like the unix domain socket is the only solution... Nonetheless, maybe there was some stability or portability concern that motivated your choice.

**Comment by izabelacg** [comment]
Not sure where this reminder belongs... If here or as an issue / note in the [greenpeace project](https://github.com/concourse/concourse/projects/110) or [here](https://github.com/concourse/concourse/projects/117).

As part of setting up datadog in greenpeace land, make sure to:

- update vault (datadog_api_key and datadog_app_key) to a datadog account different than our current one (used for hush-house and ci), so that metrics sent during `test phase` won't end up in our "production" datadog.

- and/or update [metrics attribute](https://github.com/concourse/hush-house/blob/82fe5b5de0985670b13d6782bda16bf7bd70b3a3/deployments/with-creds/ci/values.yaml#L128) and/or [datadog prefix](https://github.com/concourse/concourse-chart/blob/a895447beca6328001cc36769c3b2702aa45a045/values.yaml#L630) on greenpeace to different value than what's currently being used for hush-house and ci as a way to distinguish greenpeace info from ci/hush-house info in datadog

**Comment by izabelacg** [comment]
Hey @YoussB , should this issue be closed? I see it was moved to Done in [Epic #5900](https://github.com/concourse/concourse/projects/117#card-42280283).

**Comment by aoldershaw** [comment]
Now that we use Wavefront for our metrics, this is no longer needed
