### ISSUE TITLE
Archived Pipelines in Web UI

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#5648]
### Problem

- Concourse’s dashboard UI is a sophisticated front end experience for monitoring and interacting with pipelines, jobs, resources, and build logs. However, as customers push their Concourse usage to extreme scale, performance on the dashboard suffers.
- Specific roles require more advanced workflow possibilities to reduce the amount of manual effort involved in navigating the dashboard UI

### Proposed Solutions

- Advanced loading, caching, and updating strategies to improve speed and decrease bandwidth
- Pipeline favouriting, **archiving**, and sorting capabilities to reduce the toil and cognitive overload of navigating thousands of pipelines on a daily basis
- Build logs that load only the most pertinent info by default, with more available on demand
- Stripped down, operations-focused version of the dashboard for maximum performance

### Related efforts

See #5434 - Favourite Pipelines

### Current Status

- Pipeline caching, lazy loading implemented in 6.0.0
- Favorite Pipelines and Archiving Pipelines initiative research and design phase underway
- Archiving Pipelines back-end engineering work in flight

### Tasks

- [x] #5635 - Alter pipeline tile for archived pipelines
- [x] #5637 - Alter sidebar pipeline list item for archived pipelines
- [x] #5640 - Create toggle switch for archived pipelines

**Comment by aoldershaw** [comment]
This has been implemented (see https://github.com/concourse/concourse/pull/5715), but it was easy enough to go with the "view selector" approach, so I went ahead and opened the following PRs:

* https://github.com/concourse/concourse/pull/5760
  * archived pipelines don't display action buttons on pipeline/build/job/resource views
  * drag and drop is fixed when there are archived pipelines
  * **note:** it does not implement #5635 
* https://github.com/concourse/concourse/pull/5761
  * view selector in sidebar
  * sidebar style changes per #5478 
  * **note:** selecting archived pipelines in the view selector does not modify what's displayed in the dashboard (it only filters in the sidebar). do we want to also change the filtering in the dashboard @matthewpereira (in which case we'd want #5635)?
