### ISSUE TITLE
v10 loose ends

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#5661]
### Summary
There are a number of engineering tasks which need to be completed to enable other v10 functionality in q3 and q4.

### Related tasks
- [ ] https://github.com/concourse/concourse/projects/68#card-33595214
- [ ] https://github.com/concourse/concourse/projects/68#card-33595138
- [ ] https://github.com/concourse/concourse/projects/68#card-33595019
- [ ] https://github.com/concourse/concourse/projects/68#card-33595037
- [ ] https://github.com/concourse/concourse/projects/68#card-33595037
- [ ] https://github.com/concourse/concourse/projects/68#card-33594926
