### ISSUE TITLE
Installation and Upgrade Guides for v6.3.0

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#5691]
### Background

Concourse v6.3.0 is about to go into commercial support. As per our enterprise release process, we will need to update the existing enterprise documentation, specifically the upgrade and installation guides. 

### Summary

As part of this process we will need to update the following:

#### Helm

- [x] Add v6.3.x Installation Guides - #5693 
- [x] Add upgrade guide for v5.5.x to 6.3.x - #5692 

#### BOSH

- [x] Add v6.3.0 Installation Guides - #5695 
- [x] Add upgrade guide for v5.5.x to 6.3.x - #5694

### Acceptance Criteria

- [x] Complete the issues above
- [x] Get sign-off from Scott and/or Matthew

**Comment by xtremerui** [comment]
After sync up with @matthewpereira , we know that `develop` branch is used for staging and the latest is branch `v5`. 

All the work for v6 doc should branch from `v6` (that is branch of v5 now) and pull request back to `v6`.
