### ISSUE TITLE
Web UI Performance

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#5712]
### Problem

- Concourse’s dashboard UI is a sophisticated front end experience for monitoring and interacting with pipelines, jobs, resources, and build logs. However, as customers push their Concourse usage to extreme scale, performance on the dashboard suffers.
- Specific roles require more advanced workflow possibilities to reduce the amount of manual effort involved in navigating the dashboard UI

### Proposed Solutions
- Build logs that load only the most pertinent info by default, with more available on demand
- Stripped down, operations-focused version of the dashboard for maximum performance

### Historical context
#5032 - What information should we have on the dashboard?
#5193 - Preloading dashboard info

### Specific origin
#5341 - The dashboard page results in very high web memory consumption node when the number jobs is very large 

### Current efforts
- [x] #5405 - Implement and backport ListAllJobs endpoint capability
- [x] #5429 - Rate limit API requests
- [x] #5466 - Retry ListAllJobs endpoint on 503 error
- [ ] #5556 - Allow showing job info on demand
