### ISSUE TITLE
web: pipeline instances UI

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#5921]
## Summary

The goal of this issue is to facilitate interaction with pipeline instances in the web UI.

## RFC

"Instanced pipelines group together pipelines which share a common template configured with different ((vars)). They provide a simple two-level hierarchy and automatic archiving of instances which are no longer needed."
https://github.com/concourse/rfcs/blob/master/034-instanced-pipelines/proposal.md

### CI monitor (dashboard) view

![Pipeline Tiles showing Instance Groups](https://user-images.githubusercontent.com/6372810/90684163-bd94a180-e235-11ea-9aef-8128784be866.png)

Instance groups are shown in the sidebar and on the main CI monitor dashboard view, with a modified pipeline tile or sidebar list item representing the group. Pipeline tiles and sidebar list items get a badge element showing the count of instances they contain. 

For example (understanding this would be done right in elm rather than CSS):

```css
.pipeline__badge {
    background: #f2f2f2;
    border-radius: 4px;
    color: #222;
    display: inline-block;
    font-size: 14px;
    letter-spacing: 0;
    margin-right: 8px;
    padding: 0px 5px;
    text-align: center;
}
```

### New Instance Group view
![Instance Group View](https://user-images.githubusercontent.com/6372810/90687149-65ac6980-e23a-11ea-8818-0d91501ee09b.png)

Clicking on an instance group in the sidebar or the dashboard highlights the group in the sidebar and reveals a new view in the dashboard: the contents of the instance group (the instances) are displayed in modified pipeline tiles which show each instance variable in the 'header' area.

The header breadcrumbs should update to show that the user is now viewing the instance group, as seen in the screenshot above.

### Pipeline View

![Pipeline View with composite instance title](https://user-images.githubusercontent.com/6372810/90684169-bf5e6500-e235-11ea-9939-7a7db24919ed.png)

When viewing an instance, the title is made up of a composite of the properties set for that instance's `((vars))`. Users can click in the header's breadcrumbs or on the sidebar to navigate back to either the instance group view or the CI monitor view. 

### CI Monitor Dashboard
- [x] Instance *groups* are represented by pipeline tiles decorated with a badge that represents the count of how many instances they contain
- [ ] ~Users are able to favorite instance groups in the CI Monitor dashboard view~

### Sidebar
- [x] Users can see instance *groups* listed in the sidebar
- [x] Instance groups have an icon differentiating them from regular pipelines (number badge)
- [ ] ~Users are able to favorite instance groups in the sidebar~

### Instance group view
- [x] Clicking an instance group in the dashboard or sidebar navigates to a new view representing the contents of the instance
- [x] Instances are represented by modified pipeline tiles that show the configured `((vars))` in the header (note: let's chat about this, maybe we just use the `<instance group name>-<instance var 1>[-<instance var 2>][...]` syntax for simplicity's sake
- [ ] ~In this view the instance group name is shown in the header breadcrumbs to signal where the user is~

### Pipeline view
- [x] Instances have breadcrumbs in the top header where their instance name is listed using the `<instance group name>-<instance var 1>[-<instance var 2>][...]` syntax
- [x] Users can click the breadcrumbs to navigate back to the instance group

### Search
- [x] Users can search for instances via a group name (implicitly)
- [ ] ~Users can search for instances via any of the instance variable names they're configured with~
- [x] ~Users can search for instances via interpolated instance variables~ (not in a structured way)

## Related PRs

#5896 - WIP Pipeline Instances api and `fly` code

## Reference Issues:
#5664 - Pipeline Instances Product Epic 
#5808 - Pipeline Instances Discussion

**Comment by aoldershaw** [comment]
Note: need to fix drag/drop reordering - the UI sends an ordered list of pipeline names. 92fc5774cbda1b7733ed370b9b19ed1e8463001c has it take an ordered list of pipeline refs, but maybe it'd be easier to just take an ordered list of pipeline ids

**Comment by aoldershaw** [comment]
How do we want to display instanced pipelines on the HD view?

1. The instance group itself (perhaps just the name and badge)?
2. When you click into an instance group?

For 2, maybe we just disable the HD view on the instance group page

**Comment by aoldershaw** [comment]
Some thoughts/questions about search:

1. Should search for e.g. pipeline status filter down within the instance group? For instance, if you search `status: failing`, should the instance group tile only display the pipelines that are failing? (the alternative being displaying the full instance group card if any instance within it is failing)
    1. If so, should this also change the badge number?
    1. If so, when you navigate to the instance group view, should this filter persist (i.e. still only display failing instances)
1. If we're searching by instance vars (by name or value), what if we just unfolded the instance groups inline? What I mean by this is displaying the instance group view for **all** of the instance groups that match the instance var filter with a header like `team_name / instance_group_name`, in the same way we currently display a team's pipelines as groups. This would mean that there doesn't need to be a separate view for instance groups - clicking on an instance group header could just be a shorthand for some search query. For this to work, we'd need more expressive filtering (#3573 and #3010 are prerequisites)...

**Comment by aoldershaw** [comment]
re: favouriting instance groups - what if instead of favouriting instance groups, users could just favourite the individual pipeline instances? If an instance group contains favourited pipeline(s), the instance group card appears in the favourites section with only the favourited pipelines appearing in the "preview". Perhaps the instance group view could also have its own favourites section...

I'm thinking of use cases for pipeline instances, and it's not obvious when you'd care about all instances at once. If you're seeing a release through, you'd want to favourite just that release pipeline; if you authored a PR, you'd want to favourite the individual PR pipeline; etc. Favouriting a few select instances out of a large instance group makes the instance group card in the favourites section more useful, since you can navigate to the desired pipeline in a single click.

I'm sure there are some cases where favouriting an entire group would make sense, though...

**Comment by chenbh** [comment]
Tech debt: migrate dashboard tooltip logic from JS to Elm
