### ISSUE TITLE
Web UI/UX Accessibility and Experience

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#5964]
# Problem

Concourse's user interface is a lean, minimal, effective tool for monitoring and interacting with pipelines, tasks, and build logs. Feedback from surveys and interviews suggests that (along with its open source nature, its flexible feature set and reproducibility) the web UI is a major reason for choosing Concourse over other CI/CD tools. However, we often learn during feedback sessions and interviews with our users that certain elements of the interface are cryptic or difficult to understand without guidance, or can be frustrating in use due to being hard to read or click on. In addition, in our 2020 community survey responses, the second largest category of feedback users provided was directed toward the web UI.

This suggests that the user interface could be more self-explanatory (either by augmenting visual elements with labels or tooltips, or by better adhering to [various UX best practices](https://lawsofux.com/)) or bolstered through additional documentation.

# User cases

The web UI is a core aspect of the Concourse experience, and affects the vast majority of users. It also represents the product's success from a brand experience point of view.

# Outcomes

- Increase accessibility and usability throughout the app
- Lower apprehension about getting started for users or teams thinking about adopting Concourse
- Decrease the time to proficiency in new users and ease the perceived learning curve
- Increase the fluency of average users so that they can take advantage of useful but 'hidden' features and get more out of the product

# List of quick fixes to be built into issues

* [x] #5974 Text/Icon Contrast correction
* [x] #5970 Change 'menu' icon in header
* [x] #5971 CI monitor/Pipeline tile enhancements
* [x] #5972 Pipeline view enhancements
* [x] #issue WIP - Margins and padding on build log view (margin bottom between steps 10px > 12px, padding left on step label 6px > 8px, etc)
* [x] #5969 Search/filtering overhaul

# List of larger epics to be built into issues

* [ ] Add view selector sidebar enhancement
