### ISSUE TITLE
Pipeline view enhancements

### ISSUE THREAD

**Issue by matthewpereira** [concourse/concourse#5972]
## Summary

Update the current appearance/behavior of Concourse's pipeline view to achieve the following:

- [x] Create tooltips for all action buttons (play/pause, and deactivated elements like resource pin icon in pipeline view) in the top right hand part of the viewport
- [x] Ensure foreground/background colours of the action buttons mentioned above are consistent with contrast rules throughout the rest of the app for default and hover states
- [ ] Uniform padding (top, right, bottom, left) on jobs/resources in pipeline string diagrams

## Todo:

**Pipeline View state:**
![Screen Shot 2020-11-23 at 1 37 00 PM](https://user-images.githubusercontent.com/6372810/100001348-09089f80-2d91-11eb-972d-ffcadc07a888.png)

* Top right icons (pin, favorite, play/pause) get tooltips

**Current padding (12px, 14px, 12px, 14px, with 20px between icon and text):**
![Screen Shot 2020-11-23 at 1 49 16 PM](https://user-images.githubusercontent.com/6372810/100002675-e6778600-2d92-11eb-8d84-937183e31449.png)

**Proposed padding (8px, 8px, 8px, 8px, with 16px between icon and text):**
![Screen Shot 2020-11-23 at 1 50 23 PM](https://user-images.githubusercontent.com/6372810/100002672-e5deef80-2d92-11eb-872d-6f7da493c21e.png)

## Context

* Part of #5964 Web UI/UX experience

**Comment by chenbh** [comment]
We tried to make the padding more consistent, but ran into some weird SVG bounding box calculation issues on Firefox that make things look wonky:

Firefox:
![Screen Shot 2021-01-13 at 3 07 08 PM](https://user-images.githubusercontent.com/17577073/104505074-5e06ac00-55b1-11eb-8856-ffad7bd41fcd.png)

Chrome:
![Screen Shot 2021-01-13 at 3 07 02 PM](https://user-images.githubusercontent.com/17577073/104505095-64952380-55b1-11eb-8cf6-4907e1972a43.png)

Firefox has more right padding because the bounding box of the text node seems to be incorrect.

It's also difficult to measure the padding in exact pixels because SVG seems to use some other unit, so we'd have to guesstimate

**Comment by matthewpereira** [comment]
@chenbh That's totally fine - I thought it would be worth investigating, and if the rendering method is too imprecise, we can move on to more important things. :)

Do you want to pair up on making the action buttons in the top bar (pin, favorite, play/pause) consistent in their foreground/background colours and tooltips?
