### ISSUE TITLE
ToDo as part of next commerical release

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#7070]
- [ ] Update boarding pass to remove mentions of our custom postgress image: http://boarding-pass.concourse-ci.org/commercial-helm-release.html
- [ ] Update enterprise docs to note this as a breaking change
- [ ] Check if any changes need to be made to the enterprise release pipeline, mainly removing publishing of the postgres image from the pipeline
