### ISSUE TITLE
Concourse v7.4.0 Commercial Release

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#7689]
We're currently eying Concourse v7.4.0 as our next commercial release on Tanzu Network. Barring any unforeseen issues, we will need to do two things:

- [x] Submit Concourse v7.4.0 to OSM for review
- [x] Update our enterprise documentation for the Bosh, Helm, and Platform Automation Releases. 
- [x] Test upgrade/downgrade from/to 6.7.x on BOSH
- [ ] Test upgrade/downgrade from/to 6.7.x on TKGi

Updating the documentation typically this requires the following:

- [x] [Release Notes](https://github.com/concourse/concourse/issues/7690)
- [x] [BOSH Installation Docs](https://github.com/concourse/concourse/issues/7691)
- [x] [BOSH Upgrade Docs](https://github.com/concourse/concourse/issues/7692)
- [x] [Helm Installation Docs](https://github.com/concourse/concourse/issues/7693)
- [x] [Helm Upgrade Docs](https://github.com/concourse/concourse/issues/7694)
- [x] [Platform Automation Installation Docs](https://github.com/concourse/concourse/issues/7695)
