### ISSUE TITLE
Worker Overloaded - Container Placement Strategy

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#8317]
## Summary

With so much work done around enhancing container placement over the past 1-2 years, I think there are enough tools in place to implement a strategy to avoid overloading workers. Still not perfect but I think it'll be an improvement!

The idea is this: workers can tell if they're over burdened. Web nodes cannot tell, besides making assumptions via proxy data like the number of containers on a given worker. Existing placement strategies use this approach. 
I propose a new placement strategy where a worker can indicate if it's overloaded or not which would take it out of consideration for container placement until it reports back that it's no longer overloaded.

### What is "overloaded"?

I want to start with a simple definition of "overloaded" which can mature over time and as folks see how the strategy works in the wild. To start I suggest keeping it simple and checking how much CPU and memory are being used, averaged over a period of time, 30s maybe? A percentage as the threshold is probably the easiest way to express this, though I understand that's not how cpu usage is "really" calculated. This will probably be the hackiest part of this whole endeavour since a lot of this stuff is OS dependent. Maybe there's a library somewhere that'll do most of this for us?

### Everything else

Everything else is pretty straight-forward Concourse plumbing code at this point. Will add a column to the workers table indicating whether the worker is overloaded. Add a new placement strategy that will remove workers where `overload == true`. Add a new API endpoint, on the worker side I think, that'll report back to the web node if it's overloaded. And lastly, add a new go routine that will track average cpu+memory usage over time.  

Thoughts? Wdyt?

---

Working branch at https://github.com/concourse/concourse/tree/worker-overload/8317
### TODO

- [x] Add db column
- [x] Add placement strategy that checks column
- [ ] Figure out direction info needs to flow between web and worker (worker tells web it's overloaded or web asks if worker is overloaded? Is there existing structure for one of these already?)
  - [ ] Worker can tell web node when it's overloaded. Worker has a TSA client
  - [ ] Add TSA command called `overloaded` for a worker to state whether it's overloaded or not. Needs to link to an API endpoint.
  - [ ] Concern: could the worker (in the db) get stuck in an overloaded state and never switch back out? Should there be a "reset" switch somewhere? Maybe the worker should always report its overloaded status every few mins?
- [ ] Use weighted moving average to determine if overloaded (?) https://github.com/VividCortex/ewma

**Comment by marco-m** [comment]
@taylorsilva I am very happy to see this idea 😍 . This will help a lot and could even make obsolete in some cases the placement strategy that my team contributed, limit-active-tasks.

Some random thoughts:

I wonder if there is a way to make this somehow customizable / easy to experiment with different notions of overload, while at the same time keeping the default simple and the implementation simple. To give an idea, maybe something like https://github.com/antonmedv/expr or https://github.com/hashicorp/go-plugin.

I also wonder if there is a way to make the approach more "forecasting", more looking in the future than in the past. If I think at my classic workload, I have tasks that last 30mins and consume all the available CPU and threads (C++ builds with ninja, which eats all cores it finds). The workers are protected from overload by limit-active-task = 1. At the same time, since the placement strategy is only one for a whole Concourse deployment, we also have a lot of waste (all the non-C++ build tasks, which could be run in parallel on the same worker).

With such workload and many waiting tasks, If I were to switch to this new strategy, I think that would observe a racing sawtooth pattern: an idle worker would get 1 task, then would get immediately another from the queue, then would go in overload, then would run the two tasks (each one starving the other), then, as soon as it becomes idle again, the pattern would repeat.

Maybe the load estimation should not be based on the last 30s, but more on something like an exponentially weighted moving average, see https://github.com/VividCortex/ewma.

**Comment by taylorsilva** [comment]
> I wonder if there is a way to make this somehow customizable / easy to experiment with different notions of overload, while at the same time keeping the default simple and the implementation simple. To give an idea, maybe something like https://github.com/antonmedv/expr or https://github.com/hashicorp/go-plugin.

I definitely want to make the "notion of overload" customizable for operators to adjust. I don't think I'll get there with this initial version of the feature but I want to ideally leave the code setup in a way that it can be expanded for further customization.

Didn't think of the forecasting idea. My initial thought is that forecasting wouldn't work well because there's no way (that I know of at least) to know if any given process is about to consume a lot or a little CPU/memory. Like I can know something is about to read a file from disk, but I don't know how much memory that'll take up unless I take the extra step of checking the file size. Even though, the program reading the file could do something smart and not load the entire file into memory. Would be nice to see if there's prior work in forecasting CPU/memory given current CPU/memory. Very interesting idea though.

**Comment by taylorsilva** [comment]
> Maybe the load estimation should not be based on the last 30s, but more on something like an exponentially weighted moving average, see for example https://github.com/VividCortex/ewma.

Great suggestion! Maybe something like this will be the initial implementation.

**Comment by marco-m** [comment]
Yes, forecasting is a tough one and I was partially dumping by brain. One possibility is to have the worker, each time it ends a task, report how heavy it found it. The ATC could keep an average of the heaviness per pipeline/job/task, and then use that number to forecast the load it would put on a worker :-) But I totally agree with the idea of starting small and see how it goes :-)

**Comment by marco-m** [comment]
>  Concern: could the worker (in the db) get stuck in an overloaded state and never switch back out? Should there be a "reset" switch somewhere? Maybe the worker should always report its overloaded status every few mins?

Maybe this should somehow be integrated in the notion of stalled worker / unhealthy worker ? For example, for my builds, it can happen that the worker gets so overloaded to become unresponsive and thus be considered stalled by Concourse.

**Comment by taylorsilva** [comment]
That's a good thought. Right now I'm building it out with `overloaded` being a separate field on the worker. I think I'm going to stick with that and not add it as a possible `status` or change the notion of `stalled`/unhealthy.

One reason is that it's the web nodes that decide if a worker is unhealthy, based on when the worker last responded. `overloaded` works the opposite of `stalled`; the **worker** tells the web nodes that it is not healthy. And ideally it should not be the same "unhealthy", it should be a "on the verge of being unhealthy so please back off".

The `status` field is currently tied to the notion of a workers lifecycle: https://concourse-ci.org/internals.html#worker-lifecycle
and I don't see `overloaded` being part of that lifecycle in any meaningful way. I'm imagining most workers would ideally have a status of `running` and then `overloaded` would be true/false for some set of workers depending on their current container workloads.

**Comment by taylorsilva** [comment]
Coming back to this after a long break...

The more I thought about this the more I came to realize that it probably wouldn't work well in practice.

I starting thinking about the most common scenario where things go wrong for Concourse workers: when A LOT of containers need to suddenly be scheduled at once. The idea I had for this new strategy would fail in that scenario because there are plenty of times, like Marco's example, where a worker can only take on one task of a certain workload. Measuring if a worker is overloaded via CPU/memory usage would likely end up being a "oops, too late" answer to this problem.
